// Hilfe-Seite und Tutorials. Texte auf Deutsch; Übersetzung über sprachen/*.js bzw. de/en/sv direkt im Eintrag.
(function () {
// Tutorials: jedes führt über die echten Seiten und markiert das Feld, um das es geht.
// s = Seite, t = data-tour-Ziel, card = Kachel vorher aufklappen, prep = Vorbereitung.
const TUTORIALS = [
  { id: "product", need: ["page_new", "create"],
    title: { de: "Ein Produkt anlegen", en: "Create a product", sv: "Skapa en produkt" },
    text: { de: "Vom leeren Formular bis zum gespeicherten Produkt mit Mindestbestand und Verantwortung.", en: "From the empty form to a saved product with minimum stock and an owner.", sv: "Från tomt formulär till sparad produkt med minsta lager och ansvarig." },
    steps: [
      { s: "new", t: "np-name", h: { de: "Namen eingeben", en: "Enter a name", sv: "Ange namn" },
        b: { de: "Unter Stammdaten → Produktverwaltung. Gib dem Produkt einen eindeutigen Namen, so wie es im Regal steht — etwa „Kaffeebohnen 1 kg\".", en: "Under Master data → Product management. Give the product a clear name, the way it sits on the shelf — e.g. “Coffee beans 1 kg”.", sv: "Under Grunddata → Produkthantering. Ge produkten ett tydligt namn, så som den står på hyllan — t.ex. ”Kaffebönor 1 kg”." } },
      { s: "new", t: "np-ean", h: { de: "EAN erfassen", en: "Add the EAN", sv: "Ange EAN" },
        b: { de: "Die EAN steht unter dem Strichcode. Eintippen oder „Scannen\" wählen — die Kamera liest sie direkt von der Verpackung.", en: "The EAN is printed under the barcode. Type it or choose “Scan” — the camera reads it straight off the package.", sv: "EAN står under streckkoden. Skriv in den eller välj ”Skanna” — kameran läser den direkt från förpackningen." } },
      { s: "new", t: "np-resp", h: { de: "Verantwortung festlegen", en: "Choose who is responsible", sv: "Välj ansvarig" },
        b: { de: "Die verantwortliche Person bekommt die Mail, sobald der Mindestbestand unterschritten wird. Stellvertretungen stehen im CC.", en: "The responsible person gets the email as soon as stock drops below the minimum. Deputies are copied in.", sv: "Den ansvariga får mejlet så fort lagret går under minimum. Ersättare får kopia." } },
      { s: "new", t: "np-min", h: { de: "Mengen festlegen", en: "Set the amounts", sv: "Ange mängder" },
        b: { de: "Mindestbestand: ab hier wird bestellt. Istbestand: was jetzt im Regal liegt. Bestellmenge: wie viel eine Bestellung normalerweise umfasst.", en: "Minimum stock: reorder from here. Current stock: what is on the shelf now. Order quantity: what one order usually contains.", sv: "Minsta lager: härifrån beställs det. Aktuellt lager: det som finns nu. Beställningsmängd: vad en beställning brukar omfatta." } },
      { s: "new", t: "np-units", h: { de: "Quantitäten wählen", en: "Pick the units", sv: "Välj enheter" },
        b: { de: "In welchen Gebinden kommt die Ware — Stück, Kiste, Palette? Die Standardquantität ist die, in der gezählt und bestellt wird.", en: "Which packaging does it come in — piece, crate, pallet? The standard unit is the one used for counting and ordering.", sv: "Vilka förpackningar kommer varan i — styck, back, pall? Standardenheten används för räkning och beställning." } },
      { s: "new", t: "np-place", h: { de: "Lagerort und Details", en: "Location and details", sv: "Lagerplats och detaljer" },
        b: { de: "Lagerort, MHD, Preis und Lieferant helfen beim Finden und Nachbestellen. Außer dem Namen ist alles freiwillig.", en: "Location, best-before date, price and supplier help with finding and reordering. Everything except the name is optional.", sv: "Lagerplats, bäst före, pris och leverantör hjälper vid sökning och beställning. Allt utom namnet är frivilligt." } },
      { s: "new", t: "np-save", h: { de: "Speichern", en: "Save", sv: "Spara" },
        b: { de: "„Produkt speichern\" legt es an und öffnet die Detailseite. Danach unter Stammdaten → QR-Codes das Etikett drucken und ans Regal kleben.", en: "“Save product” creates it and opens its detail page. Then print the label under Master data → QR codes and stick it on the shelf.", sv: "”Spara produkt” skapar den och öppnar detaljsidan. Skriv sedan ut etiketten under Grunddata → QR-koder och sätt den på hyllan." } }
    ] },
  { id: "book", need: ["page_products"], needAny: ["withdraw", "refill"],
    title: { de: "Ausbuchen und nachfüllen", en: "Withdraw and refill", sv: "Ta ut och fylla på" },
    text: { de: "Am Regal scannen, Menge eingeben, buchen — so bleibt der Bestand stimmig.", en: "Scan at the shelf, enter an amount, book it — that keeps stock accurate.", sv: "Skanna vid hyllan, ange mängd, bokför — så stämmer lagret." },
    steps: [
      { s: "scan", t: "scan-box", h: { de: "QR-Code scannen", en: "Scan the QR code", sv: "Skanna QR-koden" },
        b: { de: "Am Regal den QR-Code scannen. Auf dem Handy ist „Scannen\" immer unten rechts. Alternativ die Artikel-ID oder EAN eintippen.", en: "Scan the QR code on the shelf. On a phone, “Scan” is always at the bottom right. Or type the item ID or EAN.", sv: "Skanna QR-koden på hyllan. På mobilen finns ”Skanna” alltid nere till höger. Eller skriv in artikel-ID eller EAN." } },
      { s: "detail", t: "book-qty", h: { de: "Menge eingeben", en: "Enter the amount", sv: "Ange mängd" },
        b: { de: "Die Detailseite des Produkts öffnet sich. Menge mit − und + oder per Tastatur eingeben. Gezählt wird in der Standardquantität.", en: "The product's detail page opens. Enter the amount with − and + or the keyboard. It counts in the standard unit.", sv: "Produktens detaljsida öppnas. Ange mängden med − och + eller tangentbordet. Det räknas i standardenheten." } },
      { s: "detail", t: "book-withdraw", h: { de: "Entnahme buchen", en: "Book a withdrawal", sv: "Bokför uttag" },
        b: { de: "Zieht die Menge vom Bestand ab. Fällt er unter den Mindestbestand, kommt das Produkt auf die Bestellliste und die verantwortliche Person wird benachrichtigt.", en: "Subtracts the amount from stock. If it drops below the minimum, the product goes on the order list and the responsible person is notified.", sv: "Drar av mängden från lagret. Går det under minimum hamnar produkten på beställningslistan och den ansvariga meddelas." } },
      { s: "detail", t: "book-refill", h: { de: "Nachfüllung buchen", en: "Book a refill", sv: "Bokför påfyllning" },
        b: { de: "Neue Ware eingeräumt? Menge eingeben und „Nachfüllung buchen\". Der Status wird dabei zurückgesetzt.", en: "Put new goods away? Enter the amount and choose “Book refill”. The status is reset.", sv: "Ställt in nya varor? Ange mängden och välj ”Bokför påfyllning”. Statusen återställs." } },
      { s: "detail", t: "book-mhd", h: { de: "MHD mitgeben", en: "Add the best-before date", sv: "Ange bäst före" },
        b: { de: "Bei Lebensmitteln vor dem Nachfüllen das MHD eintragen. Entnommen wird später immer zuerst die älteste Ware.", en: "For food, enter the best-before date before refilling. Withdrawals always use the oldest stock first.", sv: "För livsmedel, ange bäst före innan påfyllning. Uttag tar alltid den äldsta varan först." } }
    ] },
  { id: "memo", need: ["page_memo"],
    title: { de: "Einen Merkzettel verwenden", en: "Use a checklist", sv: "Använda en minneslista" },
    text: { de: "Produkte, die du immer wieder zusammen holst, einmal sammeln und später mit einem Haken ausbuchen.", en: "Collect products you always fetch together once, then book them out with a tick.", sv: "Samla produkter du ofta hämtar tillsammans och bokför dem sedan med en bock." },
    steps: [
      { s: "memo", t: "memo-new", h: { de: "Merkzettel anlegen", en: "Create a checklist", sv: "Skapa minneslista" },
        b: { de: "Ein Merkzettel sammelt Produkte für einen wiederkehrenden Anlass — etwa den Wochenputz oder eine Baustelle. Er startet mit „Neuer Merkzettel\".", en: "A checklist collects products for a recurring job — the weekly clean or a site visit. Start with “New checklist”.", sv: "En minneslista samlar produkter för ett återkommande tillfälle — veckostädningen eller ett bygge. Börja med ”Ny minneslista”." } },
      { s: "memo", t: "memo-name", prep: "memoNew", h: { de: "Namen vergeben", en: "Give it a name", sv: "Ge den ett namn" },
        b: { de: "Ein kurzer Name, unter dem du den Merkzettel wiederfindest.", en: "A short name so you can find it again.", sv: "Ett kort namn så att du hittar den igen." } },
      { s: "memo", t: "memo-search", prep: "memoNew", h: { de: "Produkte hinzufügen", en: "Add products", sv: "Lägg till produkter" },
        b: { de: "Produkt suchen oder mit dem Knopf daneben scannen, Menge wählen und „Zum Merkzettel hinzufügen\". Beliebig oft wiederholen.", en: "Search a product or scan it with the button next to it, choose the amount and “Add to checklist”. Repeat as often as needed.", sv: "Sök en produkt eller skanna med knappen bredvid, välj mängd och ”Lägg till i minneslistan”. Upprepa så ofta du vill." } },
      { s: "memo", t: "memo-save", prep: "memoNew", h: { de: "Speichern", en: "Save", sv: "Spara" },
        b: { de: "„Speichern\" legt den Merkzettel ab. Gebucht wird dabei noch nichts.", en: "“Save” stores the checklist. Nothing is booked yet.", sv: "”Spara” lagrar listan. Inget bokförs ännu." } },
      { s: "memo", t: "memo-list", h: { de: "Abhaken und ausbuchen", en: "Tick off and book out", sv: "Bocka av och bokför" },
        b: { de: "Beim Holen jede Position abhaken — das bucht die Entnahme sofort. Oder alles auf einmal mit „Alle abhaken und ausbuchen\". Ein Versehen lässt sich rückgängig machen.", en: "Tick each line as you fetch it — that books the withdrawal at once. Or everything with “Tick all and book out”. Mistakes can be undone.", sv: "Bocka av varje rad när du hämtar — uttaget bokförs direkt. Eller allt på en gång. Misstag kan ångras." } }
    ] },
  { id: "order", need: ["page_orders"],
    title: { de: "Eine Bestellung abwickeln", en: "Handle an order", sv: "Hantera en beställning" },
    text: { de: "Für verantwortliche Personen: von der Bestellmail bis zur eingebuchten Lieferung.", en: "For responsible people: from the order email to the booked delivery.", sv: "För ansvariga: från beställningsmejlet till den bokförda leveransen." },
    steps: [
      { s: "orders", t: "ord-list", card: "list", h: { de: "Die Bestellliste", en: "The order list", sv: "Beställningslistan" },
        b: { de: "Fällt ein Produkt unter den Mindestbestand, bekommst du als verantwortliche Person eine Mail. Der Link darin öffnet diese Liste mit allem, was fehlt.", en: "When a product drops below the minimum, you get an email as the responsible person. Its link opens this list with everything missing.", sv: "När en produkt går under minimum får du som ansvarig ett mejl. Länken öppnar den här listan med allt som saknas." } },
      { s: "orders", t: "ord-orderall", card: "list", h: { de: "Bestellen und markieren", en: "Order and mark", sv: "Beställ och markera" },
        b: { de: "Beim Lieferanten bestellen — die Menge steht in der Standardquantität dabei — und die Positionen hier „in Bestellung\" setzen. So weiß das Team, dass sich jemand kümmert.", en: "Order from the supplier — the amount is shown in the standard unit — and set the lines to “ordered” here, so the team knows it is handled.", sv: "Beställ hos leverantören — mängden visas i standardenheten — och sätt raderna som ”beställda” här, så vet teamet att någon tar hand om det." } },
      { s: "orders", t: "ord-open", h: { de: "Offene Bestellungen", en: "Open orders", sv: "Öppna beställningar" },
        b: { de: "Hier stehen alle bestellten Produkte. Kommt eine andere Menge als bestellt, die Zahl anpassen; bei Lebensmitteln das MHD der Lieferung eintragen.", en: "All ordered products are listed here. If a different amount arrives, adjust it; for food, enter the delivery's best-before date.", sv: "Här står alla beställda produkter. Kommer en annan mängd, justera den; för livsmedel, ange leveransens bäst före." } },
      { s: "orders", t: "ord-receive", h: { de: "Lieferung einbuchen", en: "Book the delivery", sv: "Bokför leveransen" },
        b: { de: "„Zurück in Bestand\" bucht die gelieferte Menge ein — einzeln oder alle zusammen. Reicht der Bestand danach noch nicht, kommt das Produkt wieder auf die Bestellliste.", en: "“Back to stock” books in the delivered amount — one by one or all at once. If stock is still short, the product returns to the order list.", sv: "”Tillbaka i lager” bokför den levererade mängden — en i taget eller alla. Räcker lagret inte, hamnar produkten på listan igen." } },
      { s: "orders", t: "ord-person", card: "pl", h: { de: "Deine Liste", en: "Your list", sv: "Din lista" },
        b: { de: "Unter „Bestelllisten je Person\" siehst du, welche Produkte in deiner Verantwortung liegen und was Stellvertretungen übernehmen.", en: "“Order lists per person” shows which products you are responsible for and what deputies cover.", sv: "”Beställningslistor per person” visar vilka produkter du ansvarar för och vad ersättare tar hand om." } }
    ] }
];

// Hilfetexte. Als Daten, damit die Suche filtern kann.
const HELP_TOPICS = [
  { kicker: "Erste Schritte", title: "Lager einrichten", items: [
    { q: "Wie lege ich Lagerorte an?",
      a: ["Einstellungen → Lagerorte. Namen eintragen, „Lagerort anlegen\" drücken. Die Liste speist die Auswahl beim Anlegen eines Produkts und alle Filter.",
          "Löschen geht nur, solange kein Produkt darin liegt — sonst wäre der Ort eines Produkts plötzlich leer. Der Zähler rechts zeigt, wie viele Produkte betroffen sind."],
      go: "settings", linkLabel: "Zu den Lagerorten" },
    { q: "Wie lege ich ein Produkt an?",
      a: ["Stammdaten → Produktverwaltung. Pflicht ist nur der Name; alles andere lässt sich später ergänzen.",
          "Gleiche Namen sind erlaubt, solange sich Lagerort oder Quantität unterscheiden — „Wasser 0,5 l\" kann im Keller und in der Küche liegen. Stimmen Name, Lagerort und Quantität überein, bleibt der Knopf gesperrt."],
      go: "new", linkLabel: "Produkt anlegen" },
    { q: "Wie lege ich Quantitäten und die Standardquantität fest?",
      a: ["Einstellungen → Quantitäten: Gebinde wie Flasche, Kasten oder Palette anlegen und angeben, wie viele der kleineren darin stecken — 1 Kasten = 12 Flaschen.",
          "Im Produkt die passenden Quantitäten anhaken und eine als Standardquantität wählen. In ihr werden Bestand, Mindestbestand und Bestellmenge gezeigt, gebucht und in Mails genannt; was nicht aufgeht, steht in den kleineren Quantitäten daneben."],
      go: "settings", linkLabel: "Zu den Quantitäten" },
    { q: "Wie übernehme ich eine bestehende Liste?",
      a: ["Stammdaten → Produktverwaltung, Karte „Viele Produkte aus einer Tabelle importieren\". Vorlage herunterladen — leer oder mit dem heutigen Bestand —, in Excel ausfüllen und wieder hochladen. Gelesen werden Excel (.xlsx) und CSV.",
          "Istbestand, Mindestbestand und Bestellmenge stehen in der Standardquantität des Produkts. Zeilen mit Fehlern werden vor dem Übernehmen einzeln angezeigt."],
      go: "new", linkLabel: "Zum Import" },
    { q: "Wie bekomme ich QR-Etiketten an das Regal?",
      a: ["Stammdaten → QR-Codes. Format wählen (2×4 bis 5×13 je Blatt oder Endlosrolle 62 mm), Produkte auswählen, drucken.",
          "Der Code enthält nur die Produktkennung, keine Bestände. Ein Etikett bleibt also gültig, auch wenn sich alles andere ändert."],
      go: "qr", linkLabel: "Zu den Etiketten" }
  ]},
  { kicker: "Täglicher Betrieb", title: "Buchen und scannen", items: [
    { q: "Wie buche ich eine Entnahme?",
      a: ["Lager → Scannen, Code mit der Handykamera erfassen oder die Nummer eintippen. Menge eingeben, Entnahme oder Nachfüllung wählen, buchen.",
          "Der Bestand ändert sich sofort. Jede Buchung bleibt mit Person und Zeitpunkt im Bestandsverlauf nachvollziehbar."],
      go: "scan", linkLabel: "Zum Scannen" },
    { q: "Wie buche ich Kisten und Einzelflaschen zusammen?",
      a: ["Auf dem Buchungsschirm zählt das Hauptfeld in der Standardquantität. Darunter steht für jede weitere Quantität ein eigenes Feld — zwei Kästen und drei Flaschen ergeben automatisch die richtige Gesamtmenge.",
          "Welche Quantitäten ein Produkt hat, steht in seinem Detail unter „Bearbeiten\"."],
      go: "scan", linkLabel: "Zum Buchen" },
    { q: "Ein Produkt wird nicht mehr geführt — löschen?",
      a: ["Besser deaktivieren: im Produktdetail den Schalter „Aktiv\" ausschalten. Das Produkt verschwindet aus Listen, Filtern und Bestellvorschlägen, bleibt aber für die verantwortliche Person grau sichtbar.",
          "So bleibt der Verlauf erhalten. Gelöschte Produkte würden auch ihre Buchungen mitnehmen."] },
    { q: "Wie trage ich das Mindesthaltbarkeitsdatum ein?",
      a: ["Beim Nachfüllen und in offenen Bestellungen gibt es ein Feld „MHD\". Jede Lieferung behält ihr eigenes Datum.",
          "Entnommen wird nach „first in, first out\": das älteste MHD zuerst."] }
  ]},
  { kicker: "Benachrichtigungen", title: "Mindestbestand und Mails", items: [
    { q: "Wer bekommt die Warnmail?",
      a: ["Die verantwortliche Person des Produkts, in CC die Stellvertretungen. Beides steht im Produktdetail unter „Verantwortung\".",
          "Ist niemand eingetragen, geht die Mail an die inhabende Person."] },
    { q: "Sofort oder gesammelt?",
      a: ["Einstellungen → Benachrichtigungen. „Sofort\" verschickt bei jeder Unterschreitung eine Mail. Täglich, wöchentlich oder monatlich fasst alles zu einer Bestellliste zu einer festen Uhrzeit zusammen.",
          "Bei vielen kleinen Entnahmen ist die Sammelmail ruhiger — eine Liste statt zwanzig Einzelmails."],
      go: "settings", linkLabel: "Zu den Benachrichtigungen" },
    { q: "Es kommt keine Mail an.",
      a: ["Einstellungen → Systemdienste → Mailversand prüfen: Testmail an die eigene Adresse schicken, dann „Antworten abrufen\". Dort steht die Antwort des Maildienstes im Klartext.",
          "201 heißt angenommen. 401 heißt falscher Schlüssel, 400 heißt Absenderadresse nicht freigeschaltet. Bleibt die Tabelle leer, ist die Anwendung nicht mit der Datenbank verbunden.",
          "Bestätigungs- und Passwortmails laufen über einen anderen Weg als die Warnmails. Die vollständige Anleitung dazu liegt im Dokument „Registrierung und Mail\"."],
      go: "settings", linkLabel: "Zu den Systemdiensten" },
    { q: "Wie verschicke ich die Bestellliste sofort?",
      a: ["Einstellungen → Benachrichtigungen → „Bestellliste jetzt mailen\". Inhaber und Lagerleitung bekommen alles unter Mindestbestand, die Mengen in der Standardquantität jedes Produkts."],
      go: "settings", linkLabel: "Zu den Benachrichtigungen" }
  ]},
  { kicker: "Auswertung", title: "Verlauf, Preise, Umsatz", items: [
    { q: "Wie sehe ich, was sich verbraucht?",
      a: ["Lager → Bestandsverlauf. Produkt und Zeitraum wählen; die Grafik zeigt den Bestand, die Tabelle darunter jede einzelne Buchung.",
          "Über „Als Excel exportieren\" wandert derselbe Stand als CSV auf die Festplatte."],
      go: "history", linkLabel: "Zum Bestandsverlauf" },
    { q: "Wie trage ich eine Preisänderung ein?",
      a: ["Lager → Bestandsverlauf, Karte „Preisverlauf und Umsatz\". Produkt wählen, Datum unter „Gültig ab\" setzen, neuen Preis eintragen.",
          "Alte Preise bleiben erhalten. Jede Entnahme wird mit dem Preis gerechnet, der an ihrem Tag gültig war — eine Erhöhung verfälscht also nicht rückwirkend den Umsatz."],
      go: "history", linkLabel: "Zum Preisverlauf" },
    { q: "Wie bekomme ich den Umsatz mehrerer Produkte?",
      a: ["In derselben Karte die Produkte anklicken, die zusammengerechnet werden sollen. Ohne Auswahl rechnet das Programm über alle aktiven Produkte.",
          "Oben stehen Umsatz, entnommene Menge und Anzahl der Preisänderungen; die Tabelle schlüsselt nach Produkt auf. „Umsatz als CSV\" gibt alles heraus."],
      go: "history", linkLabel: "Zum Umsatz" },
    { q: "Was zeigt der Bestandswert?",
      a: ["In der Karte „Preisverlauf und Umsatz\": Bestand × Preis, der an dem Tag galt, über den gewählten Zeitraum. Bei einem einzelnen Produkt zeigt die gestrichelte Linie den Wert des Mindestbestands.",
          "Tage mit Preisänderung sind als Raute markiert. Ein Klick darauf — oder auf die Zeile in der Tabelle „Preisänderungen\" — zeigt alten und neuen Preis."],
      go: "history", linkLabel: "Zum Bestandswert" }
  ]},
  { kicker: "Organisation", title: "Team, Rechte, Merkmale", items: [
    { q: "Wie hole ich Kollegen dazu?",
      a: ["Verwaltung → Team & Rechte → einladen. Die Person bekommt eine Mail mit einem Link, der drei Stunden gilt, und richtet ihr Passwort selbst ein.",
          "Rollen sind Vorlagen: Lagerleitung darf verwalten, Mitarbeitende dürfen buchen, Leser dürfen nur sehen. Einzelne Rechte lassen sich pro Person davon abweichend setzen."],
      go: "team", linkLabel: "Zu Team & Rechte" },
    { q: "Wie ändere ich einen Namen?",
      a: ["Verwaltung → Team & Rechte, Person auswählen, Name eintragen und „Änderungen übernehmen\" drücken. Erst dann gilt der neue Name überall — auch bei Verantwortlichkeiten und Stellvertretungen.",
          "Solange etwas nicht übernommen ist, steht das ausdrücklich daneben."],
      go: "team", linkLabel: "Zu Team & Rechte" },
    { q: "Wie arbeite ich mit Abteilungen?",
      a: ["Einstellungen → Abteilungen: Abteilungen anlegen und Personen zuordnen. Eine Person kann in mehreren Abteilungen sein.",
          "Oben in der Menüleiste wird die Abteilung gewechselt. Produkte, Bestellungen, Events, Merkzettel und Verlauf zeigen dann nur ihre Daten; „Ganze Firma\" zählt alles zusammen."],
      go: "settings", linkLabel: "Zu den Abteilungen" },
    { q: "Wie kopiere ich Produkte in eine andere Abteilung?",
      a: ["Stammdaten → Produktverwaltung: ein oder mehrere Produkte auswählen, Zielabteilung wählen, kopieren. Die Kopie bekommt eine eigene Kennung und einen neuen QR-Code; der Bestand wird getrennt geführt.",
          "Das Etikett der Kopie neu drucken — sonst bucht der Scan im ursprünglichen Produkt."],
      go: "new", linkLabel: "Zur Produktverwaltung" },
    { q: "Was sieht welche Abteilung?",
      a: ["Einstellungen → Sichtbarkeit je Abteilung: Lagerorte, Quantitäten und Merkmale lassen sich für einzelne Abteilungen ausblenden. Wer dort arbeitet, bekommt sie in Auswahllisten nicht angeboten."],
      go: "settings", linkLabel: "Zu den Einstellungen" },
    { q: "Wie benenne ich einen Lagerort um?",
      a: ["Einstellungen → Lagerorte, beim Lagerort „Umbenennen\" wählen. Alle Produkte an diesem Ort ziehen automatisch mit."],
      go: "settings", linkLabel: "Zu den Lagerorten" },
    { q: "Warum ist eine Seite für mich gesperrt?",
      a: ["Welche Seiten und Aktionen jemand nutzen darf, legt die Rolle fest; einzelne Rechte können je Person abweichen. Freigeben kann, wer das Recht „Rechte ändern\" hat.",
          "Die Hilfe ist für alle immer offen."] },
    { q: "Wozu sind eigene Merkmale gut?",
      a: ["Einstellungen → Eigene Merkmale. Damit lässt sich erfassen, was dieses Lager braucht und kein anderes: Gefahrstoffklasse, Prüfdatum, Regalhöhe.",
          "Jedes Merkmal kann eine Regel tragen — eine Warnmail auslösen, auf die Bestellliste wandern, eine Entnahme sperren oder auf das Etikett gedruckt werden."],
      go: "settings", linkLabel: "Zu den Merkmalen" }
  ]},
  { kicker: "Einkauf", title: "Bestellliste und Bestellungen", items: [
    { q: "Wie entsteht die Bestellliste?",
      a: ["Lager → Bestellungen. Jedes aktive Produkt unter Mindestbestand steht dort bei der verantwortlichen Person — verschiebbar zu jeder anderen. Oben lässt sich nach Abteilung filtern.",
          "„Alle mit Bestellmenge in Bestellung\" übernimmt die hinterlegte Bestellmenge. Sie steht zuerst in der Standardquantität; nur was darin nicht aufgeht, kommt in die kleineren Quantitäten."],
      go: "orders", linkLabel: "Zu den Bestellungen" },
    { q: "Die Ware ist da — was jetzt?",
      a: ["In der offenen Bestellung die gelieferte Menge prüfen, bei Bedarf das MHD eintragen und zurück in den Bestand buchen. Der Bestand steigt, das Produkt verlässt die Bestellung."],
      go: "orders", linkLabel: "Zu den Bestellungen" }
  ]},
  { kicker: "Planung", title: "Events", items: [
    { q: "Wie plane ich ein Event?",
      a: ["Lager → Events: Name, Datum, Ort und die benötigten Artikel mit Menge eintragen. Beim Anlegen entsteht die Bedarfsliste mit den Fehlmengen gegenüber dem heutigen Bestand.",
          "„Bestellung abschicken\" setzt die Fehlmengen auf die Bestelllisten der Verantwortlichen."],
      go: "events", linkLabel: "Zu den Events" },
    { q: "Was zeigt die Vorschau?",
      a: ["Alle kommenden Events — oder die eines Zeitraums — zusammengerechnet und gegen den heutigen Bestand gestellt. „Nur noch nicht bestellte\" blendet aus, was schon unterwegs ist. Das Ergebnis lässt sich als Excel exportieren."],
      go: "events", linkLabel: "Zu den Events" }
  ]},
  { kicker: "Konto", title: "Anmeldung und Sprache", items: [
    { q: "Passwort vergessen?",
      a: ["Auf der Anmeldeseite „Passwort vergessen?\" wählen. Der Link in der Mail gilt 15 Minuten."] },
    { q: "Wie schütze ich mein Konto zusätzlich?",
      a: ["In den Einstellungen Zwei-Faktor einrichten. Danach fragt die Anmeldung zusätzlich einen Code aus der Authenticator-App ab."],
      go: "settings", linkLabel: "Zu den Einstellungen" },
    { q: "Wie ändere ich die Sprache?",
      a: ["Oben rechts in der Menüleiste DE, EN oder SV wählen."] }
  ]}
];

(window.SC = window.SC || {}).hilfe = { TUTORIALS, HELP_TOPICS };
})();
