// Englisch — Übersetzungen der Oberfläche.
// Links steht der deutsche Originaltext (genau wie in der Oberfläche), rechts die Übersetzung.
// Fehlt ein Eintrag, erscheint automatisch der deutsche Text.
(window.SC = window.SC || {}).sprachen = window.SC.sprachen || {};
window.SC.sprachen.en = {
  // Beschriftungen, Knöpfe, Meldungen
  texte: {
    " oder die Stellvertretung.": " or the deputies.",
    "15 Personen": "15 people",
    "2 000 Artikel": "2,000 items",
    "3 Personen": "3 people",
    "300 Artikel": "300 items",
    "4 von 128": "4 of 128",
    "Abgelehnt": "Rejected",
    "Adresse fehlt": "Address missing",
    "Adresse prüfen": "Check the address",
    "Alle": "All",
    "Alle Arten": "All types",
    "Alle Felder sind änderbar.": "Every field can be changed.",
    "Alle Lagerorte": "All locations",
    "Alle Lieferanten": "All suppliers",
    "Alle Personen": "All people",
    "Alle Produkte": "All products",
    "Alle Zeilen übernommen": "All rows taken over",
    "Alle anderen Sitzungen wurden abgemeldet.": "All other sessions were signed out.",
    "Alle auswählen": "Select all",
    "Als bestellt markieren": "Mark as ordered",
    "Anfrage läuft noch — in ein paar Sekunden erneut abrufen.": "Still in flight — fetch again in a few seconds.",
    "Angelegt, aber nicht verschickt": "Created, but not sent",
    "Angemeldet als Marie Kohl": "Signed in as Marie Kohl",
    "Anhalten": "Stop",
    "Anmeldung fehlgeschlagen": "Sign-in failed",
    "Ansehen": "View",
    "Antwort am nächsten Werktag": "Reply the next working day",
    "Antwort von Brevo": "Reply from Brevo",
    "Antworten abrufen": "Fetch replies",
    "Anzahl": "Count",
    "Artikel auswählen": "Select items",
    "Artikel in der Auswahl": "items in the selection",
    "Artikel unbegrenzt": "Unlimited items",
    "Artikel vermerkt": "items noted",
    "Artikel zusammengefasst": "items combined",
    "Artikel-ID auf dem Etikett": "Item ID on the label",
    "Auf Etikett drucken": "Print on label",
    "Aufgefüllt": "Refilled",
    "Ausblenden": "Hide",
    "Auswahl": "Selection",
    "Auswahl leeren": "Clear selection",
    "Auswahl zurücksetzen": "Reset selection",
    "Bedarfsliste erstellt": "Requirement list created",
    "Bedarfsliste exportiert": "Requirement list exported",
    "Bedarfslisten für Events": "Requirement lists for events",
    "Beim Lieferanten öffnen": "Open at the supplier",
    "Beliebig kombinierbar. Leer heißt: alles.": "Combine freely. Empty means everything.",
    "Benachrichtigungen und Bestandsverlauf laufen wieder.": "Notifications and stock history are running again.",
    "Benötigt": "Needed",
    "Bestand danach": "Stock afterwards",
    "Bestand im Zeitverlauf": "Stock over time",
    "Bestand ok": "Stock ok",
    "Bestand umgerechnet": "Stock converted",
    "Bestandsverlauf dieses Produkts ansehen": "View this product's stock history",
    "Bestandsverlauf exportiert": "Stock history exported",
    "Bestandsverlauf mit Grafik": "Stock history with chart",
    "Bestellliste exportiert": "Order list exported",
    "Bestellung zurücknehmen": "Undo order",
    "Betreff": "Subject",
    "Bild gespeichert": "Image saved",
    "Bild hochladen": "Upload image",
    "Bild wird noch geladen …": "Image still loading …",
    "Bilder und Datenblätter je Artikel": "Images and data sheets per item",
    "Bitte eine vollständige E-Mail-Adresse eintragen.": "Please enter a complete email address.",
    "Bot-Prüfung bei Anmeldung und Registrierung": "Bot check on sign-in and registration",
    "Brauchen wir besondere Geräte?": "Do we need special devices?",
    "Brevo hat die Mail angenommen.": "Brevo accepted the message.",
    "Buchung sperren, wenn gesetzt": "Block booking when set",
    "CC: ": "CC: ",
    "Das Passwort erfüllt die Vorgaben von Supabase nicht.": "The password does not meet Supabase's requirements.",
    "Datei nicht lesbar": "File not readable",
    "Datenbank in einer EU-Region": "Database in an EU region",
    "Datenquelle": "Data source",
    "Datum": "Date",
    "Deaktiviert": "Deactivated",
    "Demo": "Demo",
    "Demo-Modus": "Demo mode",
    "Demo: lokal ablegen": "Demo: store locally",
    "Der Link gilt 15 Minuten.": "The link is valid for 15 minutes.",
    "Derzeit kostenlos": "Free for now",
    "Deutsch": "German",
    "Die Anzahl muss eine ganze Zahl ab 2 sein.": "The count must be a whole number of 2 or more.",
    "Die Datei ist leer.": "The file is empty.",
    "Die ersten fünf Schritte": "The first five steps",
    "Dienstag": "Tuesday",
    "Diese Datei kann der Browser nicht lesen": "The browser cannot read this file",
    "Diese Einheit gibt es schon.": "That unit already exists.",
    "Dieses Gerät erlaubt das Licht nicht über den Browser.": "This device does not allow the light from the browser.",
    "Donnerstag": "Thursday",
    "Drei Handgriffe, kein Papier.": "Three moves, no paper.",
    "Eigene Daten jederzeit als CSV heraus": "Your own data out as CSV at any time",
    "Eigene Merkmale": "Custom attributes",
    "Eigene Merkmale mit Regeln": "Custom attributes with rules",
    "Ein Lager, eine Stunde Einrichtung.": "One stockroom, one hour of setup.",
    "Eine Firma sieht nur ihre eigenen Zeilen.": "A company sees only its own rows.",
    "Eine Spalte pro Feld, inklusive eigener Merkmale.": "One column per field, custom attributes included.",
    "Eingefügte Liste": "Pasted list",
    "Einheit": "Unit",
    "Einheit anlegen": "Create unit",
    "Einheiten dieses Produkts": "Units of this product",
    "Einladung gesendet": "Invitation sent",
    "Einrichtung": "Setup",
    "Einträge": "entries",
    "Einzelnes Produkt": "Single product",
    "Endlosrolle · 62 mm breit": "Continuous roll · 62 mm wide",
    "English": "English",
    "Entnahme": "Withdrawal",
    "Entnommen": "Withdrawn",
    "Entsperren": "Unblock",
    "Erkannt und zugeordnet.": "Recognised and matched.",
    "Erledigen": "Do it",
    "Erst Artikel und Mengen hinzufügen.": "Add items and quantities first.",
    "Erst arbeiten, dann zahlen.": "Work first, pay later.",
    "Erst eine CSV-Datei wählen.": "Choose a CSV file first.",
    "Es wurde keine Kamera gefunden.": "No camera was found.",
    "Etiketten 62 mm": "Labels 62 mm",
    "Etiketten drucken": "Print labels",
    "Etiketten in allen Formaten": "Labels in every format",
    "Etikettformat": "Label format",
    "Event": "Event",
    "Event anlegen und Bedarfsliste erstellen": "Create an event and its requirement list",
    "Events": "Events",
    "Excel- und CSV-Import": "Excel and CSV import",
    "Excel-Import": "Excel import",
    "Excel-Import, Events, Bestandsverlauf": "Excel import, events, stock history",
    "Fehler": "Error",
    "Fehlmengen berechnet": "Shortfalls calculated",
    "Fehlt": "Missing",
    "Feinrechte pro Person": "Fine-grained rights per person",
    "Feld steht ab jetzt in jedem Produkt.": "The field is now on every product.",
    "Firma, Personen, Produkte und Verlauf entfernt": "Company, people, products and history removed",
    "Fragen": "Questions",
    "Freitag": "Friday",
    "Funktionen": "Features",
    "Für das Lager gedacht, nicht für die Buchhaltung.": "Made for the stockroom, not for accounting.",
    "Für ein Lager und ein kleines Team": "For one stockroom and a small team",
    "Für gewachsene Lagerstrukturen": "For grown stockroom structures",
    "Gelesen, aber kein Produkt mit dieser Kennung.": "Read, but no product with that identifier.",
    "Gelöscht": "Deleted",
    "Geplante Events": "Planned events",
    "Gesamter Zeitraum": "Whole period",
    "Gescannt": "Scanned",
    "Grund: ": "Reason: ",
    "Gültig ab": "Valid from",
    "Hilfe": "Help",
    "Hinzufügen": "Add",
    "Im Demo-Modus wird nichts verschickt.": "Nothing is sent in demo mode.",
    "In Bestellliste aufnehmen": "Add to order list",
    "In config.js ist SUPABASE_ANON_KEY leer.": "SUPABASE_ANON_KEY is empty in config.js.",
    "In config.js ist SUPABASE_URL leer.": "SUPABASE_URL is empty in config.js.",
    "Inhabende Person": "Owner",
    "Ist bestellt": "Is ordered",
    "Ja / Nein": "Yes / No",
    "Jede Buchung bleibt mit Person und Zeit nachvollziehbar": "Every booking stays traceable with person and time",
    "Kamera aus": "Camera off",
    "Kamera läuft": "Camera running",
    "Kamera nicht verfügbar": "Camera not available",
    "Kamera starten": "Start camera",
    "Kamera starten, dann den Code am Regal erfassen": "Start the camera, then capture the code on the shelf",
    "Kamera starten, dann einen Code vor die Linse halten.": "Start the camera, then hold a code in front of the lens.",
    "Kein Konto zu dieser Adresse": "No account for this address",
    "Kein Tracking, keine Werbe-Cookies": "No tracking, no advertising cookies",
    "Keine Bewegungen für diese Auswahl.": "No movements for this selection.",
    "Keine Verbindung zu Supabase.": "No connection to Supabase.",
    "Keine Zeile erkannt": "No row recognised",
    "Konto aktiv": "Account active",
    "Kopfzeile und mindestens eine Produktzeile einfügen.": "Paste a header row and at least one product row.",
    "Kurz gesagt": "In short",
    "Können wir unsere bestehende Liste übernehmen?": "Can we bring our existing list over?",
    "Laden fehlgeschlagen": "Loading failed",
    "Lagerleitung": "Stock manager",
    "Lagerort anlegen": "Create location",
    "Lagerorte": "Locations",
    "Lesezugriff": "Read access",
    "Letzte 12 Monate": "Last 12 months",
    "Letzte 3 Monate": "Last 3 months",
    "Letzte 30 Tage": "Last 30 days",
    "Licht": "Light",
    "Licht an": "Light on",
    "Licht aus": "Light off",
    "Link senden": "Send link",
    "Link verfallen": "Link expired",
    "Löst aus": "Triggers",
    "Mail an ": "Mail to ",
    "Mail ist unterwegs": "The mail is on its way",
    "Mailversand": "Mail delivery",
    "Mailversand prüfen": "Check mail delivery",
    "Mehrere Lager, mehrere Schichten": "Several stockrooms, several shifts",
    "Meistbewegte Artikel": "Most moved items",
    "Menge buchen": "Book quantity",
    "Menge oben eintragen oder hier nach Einheiten aufteilen.": "Enter the quantity above, or split it into units here.",
    "Merkmal": "Attribute",
    "Merkmal anlegen": "Create attribute",
    "Min.": "Min.",
    "Mindestbestand und Mail": "Minimum stock and mail",
    "Mit verbundenem R2 landet die Datei im Bucket der Firma.": "With R2 connected the file lands in the company's bucket.",
    "Mitarbeitende Person": "Worker",
    "Mittwoch": "Wednesday",
    "Montag": "Monday",
    "Nachbestellen": "Reorder",
    "Nachfüllung": "Refill",
    "Name des Events": "Event name",
    "Name des Merkmals": "Attribute name",
    "Name fehlt": "Name missing",
    "Name ist frei.": "The name is free.",
    "Neuer Bestand: ": "New stock: ",
    "Neuer Lagerort": "New location",
    "Neuer Preis": "New price",
    "Neues Event": "New event",
    "Neues Event planen": "Plan a new event",
    "Nicht gespeichert": "Not saved",
    "Nicht möglich": "Not possible",
    "Nichts gefunden": "Nothing found",
    "Nichts zu importieren": "Nothing to import",
    "Noch keine Artikel": "No items yet",
    "Noch nicht übernommen.": "Not applied yet.",
    "Nur verantwortliche Person": "Responsible person only",
    "Oder Code eingeben": "Or type the code",
    "Ohne Datenbank wird nichts verschickt.": "Without a database nothing is sent.",
    "Ohne Namen kann nicht gespeichert werden.": "Nothing is saved without a name.",
    "Ohne Namen wird nicht gespeichert.": "Nothing is saved without a name.",
    "Ohne Namen wird nicht übernommen.": "Nothing is applied without a name.",
    "Passwort geändert": "Password changed",
    "Passwort vergessen?": "Forgot password?",
    "Passwort wiederholen": "Repeat password",
    "Passwort zurücksetzen": "Reset password",
    "Passwort-Mail gesendet": "Password mail sent",
    "Person entfernt": "Person removed",
    "Personen unbegrenzt": "Unlimited people",
    "Pflichtfeld — ohne Namen wird nicht gespeichert.": "Required — nothing is saved without a name.",
    "Positionen": "Positions",
    "Preis eintragen": "Enter price",
    "Preis heute": "Price today",
    "Preisverlauf und Umsatz": "Price history and revenue",
    "Preisänderungen": "Price changes",
    "Produkt ausgewählt": "product selected",
    "Produkt deaktivieren": "Deactivate product",
    "Produkt wieder aktivieren": "Reactivate product",
    "Produktart": "Product type",
    "Produkte ausgewählt": "products selected",
    "Produkte exportiert": "Products exported",
    "Produkte importiert": "products imported",
    "Produktname auf dem Etikett": "Product name on the label",
    "Profil": "Profile",
    "Profil und Feinrechte": "Profile and fine-grained rights",
    "Profildaten und Rechte darf nur die inhabende Person ändern.": "Only the owner may change profile data and rights.",
    "QR-Etiketten in fünf Formaten": "QR labels in five formats",
    "R2 · privat, signierter Zugriff": "R2 · private, signed access",
    "Rechte unten ankreuzen": "Tick the rights below",
    "Regel aktiv: ": "Rule active: ",
    "Registrierung": "Registration",
    "Registrierung fehlgeschlagen": "Registration failed",
    "Rollen und Rechte": "Roles and rights",
    "Rollen und Rechte pro Person": "Roles and rights per person",
    "Sammelmail: ": "Digest mail: ",
    "Scan, Mindestbestand, Bestellliste": "Scan, minimum stock, order list",
    "Scan-Entnahme": "Scan withdrawal",
    "Schlüssel abgelehnt — brevo_api_key in sc_config prüfen.": "Key rejected — check brevo_api_key in sc_config.",
    "Schon vorhanden": "Already there",
    "Sehen andere Firmen unsere Daten?": "Can other companies see our data?",
    "So läuft es": "How it works",
    "Spalten erkannt": "columns recognised",
    "Sperren": "Block",
    "Stammdaten": "Master data",
    "Stand gespeichert.": "Saved as shown.",
    "Status setzen darf nur ": "The status may only be set by ",
    "Status zurückgesetzt": "Status reset",
    "Status: ist bestellt": "Status: ordered",
    "Stellvertretung 1": "Deputy 1",
    "Stellvertretung 2": "Deputy 2",
    "Stellvertretung 3": "Deputy 3",
    "Stück": "piece",
    "Suchen": "Search",
    "Summe im Zeitraum": "Total in the period",
    "Svenska": "Swedish",
    "Systemdienste": "System services",
    "Testmail abgeschickt": "Test mail sent",
    "Testmail an": "Test mail to",
    "Testmail senden": "Send test mail",
    "Testzugang": "Test access",
    "Treffer": "hits",
    "Umsatz als CSV": "Revenue as CSV",
    "Unter der Kopfzeile fehlt noch eine Produktzeile.": "A product row under the header is still missing.",
    "Upload fehlgeschlagen": "Upload failed",
    "Verantwortliche + Stellvertretung im CC": "Responsible person + deputies in CC",
    "Verantwortliche und Stellvertretung": "Responsible person and deputies",
    "Verantwortung": "Responsibility",
    "Informationen über das Produkt": "Product information",
    "Vergangene Events": "Past events",
    "Umbenennen": "Rename",
    "Umbenannt": "Renamed",
    "Sichtbarkeit je Abteilung": "Visibility per department",
    "Produkte in andere Abteilung kopieren": "Copy products to another department",
    "Aus Abteilung": "From department",
    "In Abteilung": "To department",
    "Produkte kopieren nach": "products copy to",
    "schon vorhanden": "already there",
    "Welche Lagerorte, Quantitäten und eigenen Merkmale in einer Abteilung zur Auswahl stehen. Abgewählt heißt: in dieser Abteilung ausgeblendet.": "Which locations, units and custom fields are offered in a department. Unchecked means hidden there.",
    "Spart das Neuanlegen. Die Kopien haben gleiche Bezeichnung und EAN, aber eigenen Bestand (startet bei 0), eigene Kennzahlen und neue QR-Codes.": "Saves creating them again. Copies keep name and EAN but get their own stock (starts at 0), own figures and new QR codes.",
    "Abteilung": "Department",
    "Abteilungen": "Departments",
    "Ganze Firma": "Whole company",
    "Alle Abteilungen": "All departments",
    "Neue Abteilung": "New department",
    "Abteilung anlegen": "Create department",
    "Sortieren nach": "Sort by",
    "In weitere Abteilung übernehmen …": "Copy to another department …",
    "Übernehmen": "Copy",
    "übernommen nach ": "copied to ",
    "Bestand 0": "stock 0",
    "angelegt": "created",
    "Link zum Lieferanten": "Supplier link",
    "MHD der Nachfüllung (optional)": "Best-before of refill (optional)",
    "MHD (optional)": "Best-before (optional)",
    "Die inhabende Person sieht immer alle Abteilungen.": "The owner always sees all departments.",
    "Keiner Abteilung zugeordnet — diese Person sieht keine Produkte.": "Not in any department — this person sees no products.",
    "Zuordnen darf nur die inhabende Person.": "Only the owner can assign.",
    "Wird sofort gespeichert.": "Saved right away.",
    "Erst alle Produkte dieser Abteilung löschen oder verschieben.": "Delete or move all products of this department first.",
    "Bestellte Menge": "Ordered quantity",
    "Alle mit Bestellmenge in Bestellung": "Order all with order quantity",
    "Zurück in Bestellliste": "Back to order list",
    "eingebucht": "booked in",
    "mit Bestand ok.": "with stock ok.",
    "Ohne Menge übersprungen: ": "Skipped without quantity: ",
    "noch unter Mindestbestand — zurück in der Bestellliste.": "still below minimum — back on the order list.",
    "Bucht bei allen Produkten die bestellte Menge ein und setzt den Status neu.": "Books in the ordered quantity for all products and updates the status.",
    "Wareneingang": "Goods received",
    "danach: ": "then: ",
    "Bestellte Menge eintragen, dann zurück in Bestand buchen.": "Enter the ordered quantity, then book back to stock.",
    "Bestand ok — aus beiden Listen entfernt.": "Stock ok — removed from both lists.",
    "Noch unter Mindestbestand — zurück in der Bestellliste.": "Still below minimum — back on the order list.",
    "Aktuell gespeichert": "Currently saved",
    "1 · Wann wird gemailt?": "1 · When to mail?",
    "2 · Wer bekommt die Mail?": "2 · Who gets the mail?",
    "Änderungen speichern": "Save changes",
    "Alles gespeichert": "All saved",
    "Ungespeicherte Änderungen — erst mit „Speichern\" werden sie übernommen.": "Unsaved changes — they only apply after “Save”.",
    "Produkt scannen": "Scan product",
    "Jetzt die Menge eintragen.": "Now enter the amount.",
    "kein passendes Produkt, weiter suchen …": "no matching product, still looking …",
    "QR-Code vom Etikett oder EAN-Strichcode in den Rahmen halten. Das Produkt wird nur ausgewählt.": "Hold the label QR code or EAN barcode in the frame. The product is only selected.",
    "Merkzettel": "Notes",
    "Meine Merkzettel": "My notes",
    "Neuer Merkzettel": "New note",
    "Seite: Merkzettel": "Page: Notes",
    "Merkzettel bearbeiten": "Edit note",
    "Name des Merkzettels": "Note name",
    "Produkt": "Product",
    "Kein Produkt gefunden.": "No product found.",
    "Zum Merkzettel hinzufügen": "Add to note",
    "Noch keine Positionen.": "No items yet.",
    "Alle abhaken und ausbuchen": "Check all and book out",
    "Wieder alle zeigen": "Show all again",
    "Alle Positionen sind abgehakt und ausgebucht.": "All items are checked and booked out.",
    "Noch kein Merkzettel gespeichert.": "No note saved yet.",
    "Rückgängig": "Undo",
    "Rückgängig gemacht": "Undone",
    "alles erledigt": "all done",
    "Verwerfen": "Discard",
    "Gespeichert": "Saved",
    "Bestellliste jetzt mailen": "Mail order list now",
    "Mail verschickt": "Mail sent",
    "Nichts zu bestellen": "Nothing to order",
    "Du darfst keine Entnahmen buchen — abhaken ist deshalb gesperrt.": "You may not book withdrawals — checking off is locked.",
    "Produkte und Mengen vormerken. Abhaken bucht die Position sofort aus dem Bestand aus. Gespeicherte Merkzettel lassen sich immer wieder verwenden.": "Note products and amounts. Checking off books the item out of stock right away. Saved notes can be reused.",
    "Nicht gespeichert — ohne „Speichern\" wird nichts übernommen.": "Not saved — nothing is applied without “Save”.",
    "Schickt sofort alles unter Mindestbestand an Inhaber und Lagerleitung — unabhängig vom Zeitplan.": "Sends everything below minimum to owner and managers right away — regardless of schedule.",
    "Aus der Bestellmail: Positionen wählen": "From the order mail: pick items",
    "Alles wählen": "Select all",
    "Alles abwählen": "Deselect all",
    "gewählt": "selected",
    "Auf „ist bestellt\" setzen": "Mark as ordered",
    "Alle Produkte mit dem Status „in Bestellung\". Solange ein Artikel hier steht, taucht er nicht wieder in der Bestellliste auf und löst keine Mail aus.": "All products with the status “on order”. While an item is listed here it won't reappear on the order list or trigger a mail.",
    "Keine kommenden Events.": "No upcoming events.",
    "Keine vergangenen Events.": "No past events.",
    "bestellt": "ordered",
    "für Event bestellt": "ordered for event",
    "in Bestellung": "on order",
    "offen": "open",
    "abgearbeitet": "done",
    "alles abgearbeitet": "all done",
    "offene Positionen": "open items",
    "Vorschau": "Preview",
    "Alle kommenden": "All upcoming",
    "Bestimmter Zeitraum": "Specific period",
    "Von": "From",
    "Bis": "To",
    "Produkte": "Products",
    "Nur noch nicht bestellte": "Only not yet ordered",
    "Im gewählten Zeitraum ist kein kommendes Event geplant.": "No upcoming event in the chosen period.",
    "Was kommende Events brauchen, zusammengerechnet und gegen den heutigen Bestand gestellt. Vergangene Events zählen nicht mit.": "What upcoming events need, added up and set against today's stock. Past events don't count.",
    "Alles unter Mindestbestand und aus abgeschickten Events. Antippen öffnet die Liste unter „Bestellungen\".": "Everything below minimum stock and from sent events. Tap to open the list under “Orders”.",
    "Strichcode waagerecht und ruhig in den Rahmen halten. Übernommen wird nur eine gültige EAN mit stimmender Prüfziffer.": "Hold the barcode level and steady in the frame. Only a valid EAN with a correct check digit is taken.",
    "Bestandsverlauf dieses Produkts": "Stock history of this product",
    "Für dieses Produkt gibt es noch keine Buchungen.": "There are no bookings for this product yet.",
    "Zurück": "Back",
    "EAN scannen": "Scan EAN",
    "Scannen": "Scan",
    "EAN gescannt": "EAN scanned",
    "Eingetragen — zum Speichern noch bestätigen.": "Filled in — confirm to save.",
    "Gelesen: ": "Read: ",
    "Strichcode waagerecht in den Rahmen halten. Die Nummer wird automatisch eingetragen.": "Hold the barcode level inside the frame. The number is filled in automatically.",
    "Öffnen": "Open",
    "Schließen": "Close",
    "Bestellung abschicken": "Send order",
    "Bestellung abgeschickt": "Order sent",
    "für Event: ": "for event: ",
    "Nur Events in der Zukunft lassen sich bestellen.": "Only future events can be ordered.",
    "Das Event liegt in der Vergangenheit — keine Bestellung mehr möglich.": "The event is in the past — no order possible anymore.",
    "Die Fehlmengen stehen auf der Bestellliste und den Bestelllisten der Verantwortlichen.": "The shortfalls are on the order list and the order lists of the responsible people.",
    "Setzt die Fehlmengen dieses Events auf die Bestellliste und die Bestelllisten der Verantwortlichen.": "Puts this event's shortfalls on the order list and the order lists of the responsible people.",
    "Alles unter Mindestbestand und aus abgeschickten Events, gesammelt für die nächste Bestellung": "Everything below minimum stock and from sent events, gathered for the next order",
    "Verantwortung je Artikel": "Responsibility per item",
    "Verhältnis": "Ratio",
    "Vorbereitet": "Prepared",
    "Vorgang": "Operation",
    "Vorgemerkt": "Noted",
    "Warnmail bei Entnahme": "Warning mail on withdrawal",
    "Was kostet es wirklich?": "What does it really cost?",
    "Was meistens gefragt wird.": "What people usually ask.",
    "Wechseln": "Switch",
    "Wer bekommt die Mail?": "Who gets the mail?",
    "Wer bekommt die Warnmails?": "Who gets the warning mails?",
    "Wie MHD überwachen": "How to watch best-before dates",
    "Wie kommen wir wieder heraus?": "How do we get out again?",
    "Wie mache ich …?": "How do I …?",
    "Wieder aktiv": "Active again",
    "Wiederholung stimmt überein": "The repeat matches",
    "Wird hochgeladen": "Uploading",
    "Zeilen gelesen": "rows read",
    "Zeilen ohne Namen verworfen": "rows without a name dropped",
    "Zeilen übersprungen (Name fehlt oder doppelt)": "rows skipped (name missing or duplicate)",
    "Zeitraum": "Period",
    "Zu ": "For ",
    "Zugang aktivieren": "Activate access",
    "Zugang sofort gesperrt, Buchungen bleiben im Verlauf": "Access blocked at once, bookings stay in the history",
    "Zugang sperren": "Block access",
    "ausgewählt": "selected",
    "davon nachzubestellen": "of those to reorder",
    "deaktiviert": "deactivated",
    "derzeit gratis": "free for now",
    "erkannt": "recognised",
    "erster Preis": "first price",
    "für immer": "for ever",
    "gebucht": "booked",
    "gerade eben": "just now",
    "größer als ": "larger than ",
    "gültig 3 Stunden": "valid for 3 hours",
    "gültig ab ": "valid from ",
    "ja": "yes",
    "ja — erscheint in allen Listen": "yes — appears in every list",
    "je Monat, geplant": "per month, planned",
    "keine Regel": "no rule",
    "kleiner als ": "smaller than ",
    "kleinste Einheit": "smallest unit",
    "nachbestellen": "reorder",
    "nein — aus Listen ausgeblendet": "no — hidden from lists",
    "neue Einheit": "new unit",
    "neue Lagerorte": "new locations",
    "niedrig": "low",
    "ohne CC an Stellvertretung": "without CC to deputies",
    "sichtbaren Artikeln": "visible items",
    "unten bestätigen": "confirm below",
    "unter Mindestbestand ": "below minimum stock ",
    "unterwegs": "in flight",
    "verbergen": "hide",
    "verbleibende Zeit": "time remaining",
    "vorhanden": "available",
    "wird die neue kleinste Einheit": "becomes the new smallest unit",
    "zeigen": "show",
    "Änderungen übernehmen": "Apply changes",
    "Übernommen": "Applied",
    "— bitte wählen —": "— please choose —",
    "— keine —": "— none —",
    "Lager": "Stock",
    "Verwaltung": "Administration",
    " gibt es keinen Zugang. Bitte Adresse prüfen oder Firma neu registrieren.": " there is no access. Check the address or register the company again.",
    "Absender nicht verifiziert — in Brevo unter Senders freischalten.": "Sender not verified — approve it in Brevo under Senders.",
    "Alles, was ein Betriebslager braucht — und nichts, was danach noch erklärt werden muss.": "Everything a company stockroom needs — and nothing that needs explaining afterwards.",
    "Beispieldaten, nichts wird gespeichert. Systemdienste und Kostenbremse sind sichtbar.": "Sample data, nothing is saved. System services and the cost brake are visible.",
    "Bestehende Listen mit Vorlage übernehmen. Artikelnummer, Mindestbestand, Ort und Lieferant kommen mit.": "Bring existing lists over with the template. Item number, minimum stock, location and supplier come along.",
    "Bilder geprüft — noch kein Code erkannt. Näher heran, mehr Licht, Code gerade halten.": "frames checked — no code yet. Move closer, add light, hold the code straight.",
    "Danach läuft das Lager von selbst. Jeder Schritt hakt sich ab, sobald er erledigt ist.": "After that the stockroom runs itself. Each step ticks itself off once it is done.",
    "Das Anlegen in der Datenbank schlägt fehl. schema.sql im SQL-Editor erneut ausführen.": "Creating the record in the database fails. Run schema.sql again in the SQL editor.",
    "Den Bestellstatus dürfen nur die verantwortliche Person und ihre Stellvertretungen setzen.": "Only the responsible person and their deputies may set the order status.",
    "Den Namen gibt es schon — mit anderem Lagerort oder anderer Quantität ist das in Ordnung.": "The name already exists — that is fine with a different location or quantity.",
    "Der Zugriff wurde abgelehnt. In der Adresszeile auf das Schloss tippen, die Kamera erlauben und erneut starten.": "Access was denied. Tap the padlock in the address bar, allow the camera and start again.",
    "Die Antwort von Brevo steht in ein paar Sekunden in der Tabelle.": "Brevo's reply will be in the table within a few seconds.",
    "Die Erkennung konnte nicht geladen werden. Bitte den Code unten eintippen.": "The reader could not be loaded. Please type the code below.",
    "Die Kamera ist von einem anderen Programm belegt. Andere Apps schließen und erneut versuchen.": "Another program is using the camera. Close other apps and try again.",
    "Die Tagesgrenze für Mails ist erreicht. Die Einladung ist gespeichert und gilt drei Stunden.": "The daily mail limit is reached. The invitation is saved and valid for three hours.",
    "Die genaue Meldung steht oben. Die Schritte zum Mailversand stehen in „Registrierung und Mail\".": "The exact message is above. The mail-delivery steps are in \"Registrierung und Mail\".",
    "Diese E-Mail-Adresse ist bereits registriert. Bitte anmelden oder das Passwort zurücksetzen.": "This email address is already registered. Please sign in or reset the password.",
    "Diese Einstellung gilt firmenweit und kann nur im höchsten Rechtelevel geändert werden.": "This setting applies company-wide and can only be changed at the highest permission level.",
    "Dieser Code gehört zu einer anderen Firma. Innerhalb dieses Zugangs lässt er sich nicht öffnen.": "This code belongs to another company. It cannot be opened from this account.",
    "Dieses Produkt gibt es schon: gleicher Name, gleicher Lagerort, gleiche Quantität. Ändere eines davon.": "This product already exists: same name, same location, same quantity. Change one of them.",
    "Ein QR-Code je Artikel oder Regalplatz. Scannen, Menge tippen, fertig — auch mit Handschuhen bedienbar.": "One QR code per item or shelf slot. Scan, type the quantity, done — usable with gloves on.",
    "Eine neue Rolle startet mit den Rechten für Ansehen und Buchen. Alles Weitere hier ankreuzen.": "A new role starts with viewing and booking rights. Tick everything else here.",
    "Eine verantwortliche Person und bis zu drei Stellvertretungen. Die Warnmail geht an sie, in CC an die Stellvertretung.": "One responsible person and up to three deputies. The warning mail goes to them, with the deputies in CC.",
    "Entnahme oder Nachfüllung eintragen. Der Bestand schreibt sich fort, die Buchung bleibt mit Person und Zeit im Verlauf.": "Enter a withdrawal or a refill. The stock updates itself, the booking stays in the history with person and time.",
    "Firma anlegen, Artikel importieren, Etiketten drucken. Danach scannt das Team.": "Create the company, import the items, print the labels. After that the team scans.",
    "In Excel über „Speichern unter\" als CSV ablegen (Trennzeichen Semikolon) und die CSV-Datei wählen.": "In Excel use Save As to write a CSV (semicolon separated) and pick that file.",
    "In der Kopfzeile fehlt eine Spalte „Name\" (oder „Artikelname\"). Ohne sie ist nicht erkennbar, was ein Produkt ist.": "The header has no \"Name\" column (or \"Artikelname\"). Without it there is no way to tell what a product is.",
    "Inhabende Person, Lagerleitung, Mitarbeitende, Leser — und einzelne Rechte pro Person, wenn eine Rolle nicht passt.": "Owner, stock manager, worker, viewer — plus individual rights per person when a role does not fit.",
    "Kein Artikel mit dieser Kennung. Etikett neu drucken oder Code eintippen.": "No item with that identifier. Print a new label or type the code.",
    "Kein Eintrag passt zu diesem Stichwort. Versuche ein einzelnes Wort — etwa „Mail\", „Etikett\" oder „Import\".": "No entry matches that keyword. Try a single word — \"Mail\", \"Etikett\" or \"Import\".",
    "Keine Karte nötig · Einrichtung in einer Stunde · jederzeit kündbar": "No card needed · set up in an hour · cancel any time",
    "Keine Mails, kein Tracking. Sichtbar nur für Verantwortliche und Stellvertretung.": "No mails, no tracking. Visible only to the responsible person and the deputies.",
    "Kurze Antworten zu allem, was im Lager täglich vorkommt. Tippe ein Stichwort ein, um zu filtern.": "Short answers to everything that comes up in the stockroom day to day. Type a keyword to filter.",
    "Lagerverwaltung für Betriebe. Betrieben von der Internet GmbH.": "Stock management for companies. Operated by Internet GmbH.",
    "Name, Lagerort und Quantität stimmen mit einem bestehenden Produkt überein.": "Name, location and quantity match an existing product.",
    "Nichts ausgewählt — gerechnet wird über alle aktiven Produkte.": "Nothing selected — the figures cover every active product.",
    "Nur Personen aus dieser Firma — an ihre hinterlegten Adressen gehen die Bestandsmails.": "Only people from this company — the stock mails go to their stored addresses.",
    "Nur die Kopfzeile mit allen Feldern. Zeile für Zeile ausfüllen, eine Zeile ist ein Produkt.": "Just the header with every field. Fill it in row by row — one row is one product.",
    "Produkt, Bestand und alle Buchungen werden entfernt. Das lässt sich nicht zurückholen.": "Product, stock and every booking are removed. This cannot be undone.",
    "QR-Code am Regal mit dem Handy scannen. Kein Gerät kaufen, keine App installieren — die Kamera genügt.": "Scan the shelf QR code with a phone. No device to buy, no app to install — the camera is enough.",
    "QR-Etiketten in fünf Formaten, von 2×4 bis 5×13 je Blatt, dazu die Endlosrolle mit 62 mm.": "QR labels in five formats, from 2×4 to 5×13 per sheet, plus the 62 mm continuous roll.",
    "Registrierung ist abgeschaltet: Authentication → Providers → Email → Enable Sign-ups einschalten.": "Registration is switched off: turn on Authentication → Providers → Email → Enable Sign-ups.",
    "Rolle: Mitarbeitende Person. Rechte setzt die inhabende Person.": "Role: worker. The owner sets the rights.",
    "Sofort, täglich, wöchentlich oder monatlich. Sammelmails fassen alles zu einer Bestellliste zusammen.": "At once, daily, weekly or monthly. Digest mails gather everything into one order list.",
    "Supabase konnte die Mail nicht übergeben. SMTP-Zugang prüfen: Project Settings → Authentication → SMTP Settings.": "Supabase could not hand the mail over. Check the SMTP access: Project Settings → Authentication → SMTP Settings.",
    "Unter dem Mindestbestand geht die Warnung raus — sofort oder gesammelt als Bestellliste, je nach Einstellung.": "Below the minimum the warning goes out — at once or gathered into an order list, depending on the setting.",
    "Wer etwas herausnimmt, scannt. Alles andere passiert von selbst.": "Whoever takes something out scans it. Everything else happens by itself.",
    "Zu dieser Adresse gibt es schon ein Konto. Anmelden oder Passwort zurücksetzen.": "There is already an account for this address. Sign in or reset the password.",
    "Zu viele Fehlversuche. Das Konto ist 15 Minuten gesperrt, eine Warnmail ist raus.": "Too many failed attempts. The account is locked for 15 minutes and a warning mail has gone out.",
    "Alle Tarife sind derzeit kostenlos. Bevor sich daran etwas ändert, melden wir uns — ohne Zustimmung wird nichts abgebucht.": "Every plan is free at the moment. Before that changes we will get in touch — nothing is charged without consent.",
    "Artikel und Mengen eintragen — auch deaktivierte. Beim Anlegen entsteht automatisch die Bedarfs- und Bestellliste mit den Fehlmengen.": "Enter items and quantities — deactivated ones too. Saving creates the requirement and order list with the shortfalls.",
    "Demo-Daten: Im verbundenen Betrieb stehen hier die echten Firmen. Zugang erhält nur, wer in der Liste platform_admins eingetragen ist.": "Sample data: in live operation the real companies appear here. Only people listed in platform_admins get access.",
    "Der Mailversand ist noch nicht eingerichtet. In Supabase im SQL-Editor die Datei supabase/mail.sql ausführen und dort im Block sc_config den Brevo-Schlüssel eintragen. Die Einladung ist gespeichert und gilt drei Stunden — der Link lässt sich auch von Hand weitergeben.": "Mail delivery is not set up yet. Run supabase/mail.sql in the Supabase SQL editor and enter the Brevo key in the sc_config block. The invitation is saved and valid for three hours — the link can also be passed on by hand.",
    "Derzeit nichts. Die Tarife stehen oben, damit klar ist, was später wofür gilt. Wird abgerechnet, fragen wir vorher — ohne Zustimmung passiert nichts.": "Nothing at the moment. The plans are above so it is clear what will apply later. If billing starts we ask first — nothing happens without consent.",
    "Die Anmeldung verlangt Passwort und Bot-Prüfung. Der zweite Faktor über eine Authenticator-App ist im Programm angelegt, aber noch abgeschaltet — er lässt sich später zuschalten, ohne dass Konten neu eingerichtet werden müssen.": "Signing in requires a password and a bot check. The second factor via an authenticator app is built in but switched off — it can be enabled later without setting up accounts again.",
    "Die Auswahl, die beim Anlegen eines Produkts und in allen Filtern erscheint. Ein Lagerort lässt sich nur löschen, wenn kein Produkt mehr darin liegt.": "The choices offered when creating a product and in every filter. A location can only be deleted once no product sits in it.",
    "Die Kamera funktioniert nur über eine verschlüsselte Verbindung. Beim ersten Mal fragt der Browser um Erlaubnis — ohne Zustimmung bleibt das Bild schwarz.": "The camera only works over an encrypted connection. The first time, the browser asks for permission — without consent the picture stays black.",
    "Die Trennung steckt nicht in der Oberfläche, sondern in der Datenbank: jede Zeile trägt eine Firmenkennung, und die Regel dazu lässt nur die eigene durch. Auch ein Zugriff an der Oberfläche vorbei bringt nichts.": "The separation is not in the interface but in the database: every row carries a company identifier and the rule only lets your own through. Going around the interface gains nothing.",
    "Die kleinste Einheit hat den Faktor 1. Eine Kiste mit zwölf Flaschen bekommt den Faktor 12, eine Palette mit 32 Kisten den Faktor 384. Gebucht wird immer in der kleinsten Einheit.": "The smallest unit has factor 1. A crate of twelve bottles gets factor 12, a pallet of 32 crates gets 384. Bookings are always in the smallest unit.",
    "Die verantwortliche Person des Artikels, in CC die Stellvertretung. Auf Wunsch statt Einzelmails eine gesammelte Bestellliste zu einer festen Uhrzeit.": "The item's responsible person, with the deputies in CC. On request a gathered order list at a fixed time instead of single mails.",
    "Dieser Browser gibt keinen Zugriff auf die Kamera. Das ist meist der Fall, wenn die Seite nicht über https:// geladen wurde. Bitte den Code unten eintippen.": "This browser gives no camera access. That usually means the page was not loaded over https://. Please type the code below.",
    "Dieses Produkt ist deaktiviert: keine Buchungen, keine Mails, kein Bestandsverlauf. Es taucht nur noch bei Verantwortlichen und Stellvertretungen auf.": "This product is deactivated: no bookings, no mails, no stock history. It only shows up for responsible people and deputies.",
    "Eine Rolle ist eine Vorlage: Wer sie bekommt, startet mit genau diesen Rechten. Einzelne Personen lassen sich danach weiter oben abweichend einstellen. Die inhabende Person darf immer alles und ist deshalb nicht änderbar.": "A role is a template: whoever gets it starts with exactly these rights. Individual people can then be set differently above. The owner may always do everything and therefore cannot be changed.",
    "Enthält den heutigen Stand. Zum Ändern eines Bestands die Zahl überschreiben und die Datei wieder hochladen — bestehende Produkte werden dabei übersprungen, nur neue Zeilen kommen hinzu.": "Contains today's figures. To change a stock level overwrite the number and upload the file again — existing products are skipped, only new rows are added.",
    "Entnahme am Regal scannen, Bestand ist sofort aktuell. Unterschreitet ein Artikel den Mindestbestand, geht die Mail an die verantwortliche Person — nicht an alle.": "Scan the withdrawal at the shelf and the stock is current at once. If an item drops below its minimum the mail goes to the responsible person — not to everyone.",
    "In Supabase ist der Captcha-Schutz aktiv. Dann braucht config.js den TURNSTILE_SITE_KEY, und in Supabase muss der passende Secret Key stehen.": "Captcha protection is active in Supabase. Then config.js needs TURNSTILE_SITE_KEY and Supabase needs the matching secret key.",
    "Ja. Die Importvorlage herunterladen, eigene Daten hineinkopieren, hochladen. Artikelnummer, Mindestbestand, Ort und Lieferant kommen mit.": "Yes. Download the import template, copy your own data in, upload. Item number, minimum stock, location and supplier come along.",
    "Jede Preisänderung gilt ab ihrem Datum. Der Umsatz nimmt für jede Entnahme den Preis, der an diesem Tag gültig war — über ein Produkt oder über mehrere zusammen.": "Every price change applies from its date. Revenue takes, for each withdrawal, the price valid on that day — for one product or several together.",
    "Kündigung jederzeit. Produktliste, Bestandsverlauf und Bestellliste lassen sich als CSV herunterladen, danach wird die Firma samt Daten gelöscht.": "Cancel at any time. Product list, stock history and order list can be downloaded as CSV, after which the company and its data are deleted.",
    "Liegt config.js neben der Seite, und stehen dort SUPABASE_URL und SUPABASE_ANON_KEY? Nach dem Hochladen die Seite mit Strg+Umschalt+R (Mac: Cmd+Umschalt+R) neu laden.": "Is config.js next to the page, and does it hold SUPABASE_URL and SUPABASE_ANON_KEY? After uploading, reload with Ctrl+Shift+R (Mac: Cmd+Shift+R).",
    "Mailgrenze erreicht. Ohne eigenen SMTP-Zugang erlaubt Supabase nur wenige Mails pro Stunde — SMTP-Daten von Brevo eintragen.": "Mail limit reached. Without your own SMTP access Supabase allows only a few mails per hour — enter the Brevo SMTP details.",
    "Nein. Jede Zeile trägt eine Firmenkennung, und die Datenbank gibt nur Zeilen der eigenen Firma heraus. Das gilt auch für Zugriffe an der Oberfläche vorbei.": "No. Every row carries a company identifier and the database only hands out rows of your own company. That also holds for access that bypasses the interface.",
    "Nein. Jedes Handy mit Kamera genügt, der QR-Code klebt am Regal. Etiketten druckst du selbst, auf normalem Papier oder mit einem Rollendrucker.": "No. Any phone with a camera is enough, the QR code sticks to the shelf. You print the labels yourself, on ordinary paper or with a roll printer.",
    "Preise ohne Umsatzsteuer. Ein Wechsel ist jederzeit möglich, eine Kündigung ebenso — die eigenen Daten lassen sich vorher als CSV herausziehen.": "Prices exclude VAT. Switching is possible at any time, as is cancelling — your own data can be pulled out as CSV beforehand.",
    "Produktbilder liegen in einer geschlossenen Ablage und werden über Adressen geladen, die nach einer Stunde verfallen. Der Mailschlüssel liegt in der Datenbank, nicht im Browser.": "Product images sit in a closed store and load through addresses that expire after an hour. The mail key sits in the database, not in the browser.",
    "Scheidet jemand aus dem Unternehmen aus, können Profildaten hier geändert, der Zugang gesperrt oder die Person entfernt werden.": "When someone leaves the company, profile data can be changed here, access blocked, or the person removed.",
    "Wer den Verlauf behalten will, schaltet das Produkt stattdessen auf „nicht aktiv\" — es verschwindet dann aus allen Listen, bleibt aber auffindbar.": "To keep the history, set the product to \"not active\" instead — it then disappears from every list but stays findable.",
    "Zusätzliche Felder für jedes Produkt. Wähle Name und Art — und wenn gewünscht, was das Feld in der Bestandsverwaltung auslöst.": "Extra fields for every product. Choose a name and a type — and, if you like, what the field triggers in stock management.",
    "Lagerorte anlegen": "Create locations",
    "Einstellungen → Lagerorte: Regal, Schrank, Halle.": "Settings → Locations: shelf, cabinet, hall.",
    "Produkte anlegen oder Tabelle importieren": "Create products or import a spreadsheet",
    "Stammdaten → Produktverwaltung: einzeln eintragen oder eine CSV hochladen.": "Master data → Product management: enter them one by one or upload a CSV.",
    "QR-Etiketten drucken": "Print QR labels",
    "Ein Code je Produkt, ans Regal geklebt.": "One code per product, stuck to the shelf.",
    "Team einladen": "Invite someone",
    "Wer bucht, braucht einen Zugang.": "Whoever books needs an account.",
    "Einmal testen, damit Warnungen ankommen.": "Test it once so warnings arrive.",
    "Quantitäten": "Quantities",
    "Name der Quantität": "Quantity name",
    "Quantität anlegen": "Create quantity",
    "Größe": "Size",
    "Größen": "sizes",
    "Import nicht gespeichert": "Import not saved",
    "Buchung nicht gespeichert": "Booking not saved",
    "Zugang nicht eingerichtet": "Access not set up",
    "Konto angelegt": "Account created",
    "Bitte Vor- und Nachnamen eintragen.": "Please enter a first and last name.",
    "Bitte die Adresse eintragen, an die die Einladung ging.": "Please enter the address the invitation went to.",
    "Quantität": "Unit",
    "Quantitäten verwalten": "Manage quantities",
    "Verhältnis zu": "Relative to",
    "Enthält wie viele": "Contains how many",
    "eigenständig": "standalone",
    "eigenständig — ohne Bezug": "standalone — no relation",
    "steht für sich, ohne Umrechnung.": "stands on its own, no conversion.",
    "Diese Quantität gibt es schon.": "That quantity already exists.",
    "Zuerst einen Namen eintragen.": "Enter a name first.",
    "frei": "unused",
    "Namen sind schon vergeben": "Names are already taken",
    "Alles überschreiben": "Overwrite everything",
    "Nichts überschreiben": "Overwrite nothing",
    "Import ausführen": "Run import",
    "Verantwortliche und stellvertretende Person": "Responsible person and deputies",
    "Person": "Person",
    "Produkt aktualisiert": "product updated",
    "Produkte aktualisiert": "products updated",
    "neu hinzugefügt": "newly added",
    "keine neuen Zeilen": "no new rows",
    "nicht im Team: ": "not in the team: ",
    "weitere werden gleich behandelt.": "more are treated the same way.",
    "Captcha fehlt": "Captcha missing",
    "In welchen Gebinden wird dieses Produkt bewegt? Angehakte Quantitäten bekommen oben ein eigenes Buchungsfeld. Angelegt und ins Verhältnis gesetzt werden sie in den Einstellungen.": "In which packaging units is this product moved? Ticked quantities get their own booking field above. They are created and related to one another in the settings.",
    "Es gibt noch keine Quantitäten. Unter Einstellungen → Quantitäten lassen sich Flasche, Kiste oder Palette anlegen.": "There are no quantities yet. Bottle, crate or pallet can be created under Settings → Quantities.",
    "Gebinde, in denen eure Ware ankommt und rausgeht: Flasche, Kiste, Palette, Rolle, Sack. Eine Quantität kann für sich stehen oder sich auf eine andere beziehen — dann rechnet das Lager beim Buchen um.": "The packaging your goods arrive and leave in: bottle, crate, pallet, roll, sack. A quantity can stand on its own or relate to another — then the stockroom converts when booking.",
    "„Kiste, Verhältnis zu Flasche, 12\" ergibt 1 Kiste = 12 Flaschen. Eine Palette mit 32 Kisten wird auf die Kiste bezogen, nicht auf die Flasche — die Kette rechnet sich von selbst durch. Gebinde ohne Bezug bleiben eigenständig.": "\"Crate, relative to bottle, 12\" gives 1 crate = 12 bottles. A pallet of 32 crates relates to the crate, not the bottle — the chain works itself out. Packaging without a relation stays standalone.",
    "Bitte zuerst den Haken im Sicherheitsfeld setzen. Erscheint kein Feld, fehlt in config.js der TURNSTILE_SITE_KEY.": "Please tick the security box first. If no box appears, config.js is missing the TURNSTILE_SITE_KEY.",
    "Ein Produkt aus der Liste trägt den Namen eines vorhandenen, weicht aber ab. Wähle aus, was übernommen wird.": "One product in the list carries the name of an existing one but differs. Choose what gets applied.",
    "Produkte aus der Liste tragen den Namen vorhandener Produkte, weichen aber ab. Wähle aus, was übernommen wird.": "products in the list carry the names of existing products but differ. Choose what gets applied.",
    "neue Zeilen kommen in jedem Fall hinzu.": "new rows are added in any case.",
    "Neue Zeilen sind nicht dabei — die Liste enthält nur bekannte Namen.": "There are no new rows — the list contains only known names.",
    "neue Zeile kommt in jedem Fall hinzu.": "new row is added in any case.",
    "Artikelkennung": "Item code",
    "Diese Kennung steht auf dem Etikett und ändert sich nie. Sie lässt sich beim Scannen auch von Hand eintippen.": "This code is printed on the label and never changes. It can also be typed in by hand when scanning.",
    "Artikelkennung fehlt": "Item code missing",
    "Die Spalte „code“ gibt es noch nicht. Bitte schema.sql im SQL-Editor erneut ausführen — sonst sind gedruckte Etiketten nicht scannbar.": "The \"code\" column does not exist yet. Please run schema.sql again in the SQL editor — otherwise printed labels cannot be scanned.",
    "Etiketten": "Labels",
    "Kennung vergeben": "code assigned",
    "Kennungen vergeben": "codes assigned",
    "Neu drucken: ": "Reprint: ",
    "Gespeichert, aber ohne Kennung: die Spalte „code“ gibt es noch nicht. Bitte schema.sql im SQL-Editor ausführen — sonst sind gedruckte Etiketten nicht scannbar.": "Saved, but without a code: the \"code\" column does not exist yet. Please run schema.sql in the SQL editor — otherwise printed labels cannot be scanned.",
    "Übersicht": "Overview",
    "Produktverwaltung": "Product management",
    "Rollen": "Roles",
    "Rollen und ihre Standardrechte": "Roles and their default rights",
    "Standardrechte": "Default rights",
    "Neue Rolle": "New role",
    "Rolle anlegen": "Create role",
    "Rechte": "Rights",
    "Personen": "People",
    "Fremdes Etikett": "Foreign label",
    "Kein Zugriff": "No access",
    "Bearbeiten": "Edit",
    "Produkt löschen": "Delete product",
    "Wirklich vollständig löschen?": "Delete this permanently?",
    "Endgültig löschen": "Delete permanently",
    "Aktiv": "Active",
    "Gelesener Code": "Code read",
    "Noch kein Code gelesen": "No code read yet",
    "Vorlage herunterladen": "Download template",
    "Ausgefüllte Liste hier hochladen": "Upload your filled-in list here",
    "Datei hierher ziehen oder klicken · .csv bis 5 MB": "Drag a file here or click · .csv up to 5 MB",
    "Leere Liste — nur Kopfzeile": "Empty list — header only",
    "Mit allen vorhandenen Produkten": "With every existing product",
    "Vorlage mit Bestand": "Template with stock",
    "Leere Vorlage": "Empty template",
    "Vorlage": "Template",
    "Datei unten hochladen, Spalten prüfen, importieren": "Upload the file below, check the columns, import",
    "Vorlage wählen: leer oder mit dem heutigen Bestand": "Pick a template: empty, or with today’s stock",
    "Produkt anlegen": "Add product",
    "QR-Codes": "QR codes",
    "Team & Rechte": "Team & rights",
    "Einstellungen": "Settings",
    "Betriebs-Konsole": "Operator console",
    "Angemeldet als": "Signed in as",
    "Abmelden": "Sign out",
    "Hell": "Light",
    "Dunkel": "Dark",
    "System": "System",
    "Artikel im Lager": "Items in stock",
    "in": "across",
    "Lagerorten": "locations",
    "Unter Mindestbestand": "Below minimum",
    "Benachrichtigung ausgelöst": "notification triggered",
    "Bestellt, offen": "Ordered, open",
    "warten auf Lieferung": "awaiting delivery",
    "Entnahmen heute": "Withdrawals today",
    "Bestellliste": "Order list",
    "Alles unter Mindestbestand, gesammelt für die nächste Bestellung": "Everything below minimum, collected for the next order",
    "Artikel": "Items",
    "Ist": "Actual",
    "Min": "Min",
    "Bestellmenge": "Order qty",
    "Lieferant": "Supplier",
    "Status": "Status",
    "Als Excel exportieren": "Export to Excel",
    "Als PDF drucken": "Print as PDF",
    "Letzte Bewegungen": "Recent movements",
    "Suche": "Search",
    "Lagerort": "Location",
    "Name": "Name",
    "Istbestand": "Actual stock",
    "Mindestbestand": "Minimum stock",
    "Details": "Details",
    "von": "of",
    "Artikeln": "items",
    "Neues Produkt": "New product",
    "Entnehmen oder nachfüllen": "Withdraw or refill",
    "Menge eingeben und buchen. Jede Buchung wird mit Person und Zeitstempel protokolliert.": "Enter a quantity and book it. Every booking is logged with person and timestamp.",
    "Entnahme buchen": "Book withdrawal",
    "Nachfüllung buchen": "Book refill",
    "QR-Code dieses Produkts": "QR code for this product",
    "Nur dieses Produkt. Scan öffnet direkt diese Detailansicht.": "This product only. Scanning opens this detail view.",
    "Etikett drucken": "Print label",
    "Bestandsverlauf": "Stock history",
    "Verantwortlich": "Responsible",
    "Stellvertretung": "Deputies",
    "MHD": "Best before",
    "Preis": "Price",
    "Letzte Entnahme": "Last withdrawal",
    "Letzte Auffüllung": "Last refill",
    "Geändert von": "Changed by",
    "Produktlink": "Product link",
    "Am Lagerort den QR-Code am Regal scannen. Der Code passt nur auf ein Produkt und öffnet dessen Detailansicht.": "Scan the shelf QR code at the location. Each code matches exactly one product and opens its detail view.",
    "QR-Code im Rahmen halten": "Hold the QR code in the frame",
    "Demo: Code auswählen": "Demo: pick a code",
    "Einzelnes Produkt anlegen": "Add a single product",
    "EAN": "EAN",
    "Verantwortliche Person": "Responsible person",
    "Kategorien": "Categories",
    "Link zum Produkt": "Product link",
    "Produkt speichern": "Save product",
    "Abbrechen": "Cancel",
    "Viele Produkte aus einer Tabelle importieren": "Import many products from a spreadsheet",
    "Vorlage mit allen Feldern herunterladen": "Download the template with every field",
    "Zeile für Zeile ausfüllen, eine Zeile ist ein Produkt": "Fill it in row by row — one row is one product",
    "CSV hier hochladen, Spalten prüfen, importieren": "Upload the CSV, check the columns, import",
    "In Excel über „Speichern unter\" als CSV ablegen (Trennzeichen Semikolon)": "In Excel, use Save As to write a CSV (semicolon separated)",
    "CSV-Vorlage herunterladen": "Download CSV template",
    "Datei hierher ziehen": "Drag a file here",
    ".csv, bis 5 MB — Excel-Dateien vorher als CSV speichern": ".csv, up to 5 MB — save Excel files as CSV first",
    "Beispieldatei prüfen": "Check sample file",
    "Spalte in Datei": "Column in file",
    "Feld im System": "Field in system",
    "Prüfung": "Check",
    "Produkte importieren": "products — import",
    "1 Produkt importieren": "Import 1 product",
    "Produkt importiert": "product imported",
    "Zeile übersprungen (Name fehlt oder doppelt)": "row skipped (name missing or duplicate)",
    "neuer Lagerort": "new location",
    "Zeile gelesen": "row read",
    "wird übersprungen": "skipped",
    "Spalte erkannt": "column recognised",
    "Zeile ohne Namen verworfen": "row without a name dropped",
    "Zeile": "row",
    "Zeile unter der Kopfzeile": "row under the header",
    "Zeilen unter der Kopfzeile": "rows under the header",
    "„Liste prüfen\" drücken": "press Check list",
    "Text über dem Code": "Text above the code",
    "Text unter dem Code": "Text below the code",
    "Etikettgröße": "Label size",
    "Drucken / PDF": "Print / PDF",
    "Team": "Team",
    "Rolle": "Role",
    "Feinrechte": "Fine-grained rights",
    "Die Einladung gilt 3 Stunden. Läuft sie ab, kannst du erneut einladen.": "The invitation is valid for 3 hours. If it expires you can invite again.",
    "E-Mail-Adresse": "Email address",
    "Einladung senden": "Send invitation",
    "Die Rolle setzt die Voreinstellung. Einzelne Rechte kannst du hier abweichend erlauben oder sperren.": "The role sets the default. Individual rights can be allowed or blocked here.",
    "Alles erlauben": "Allow everything",
    "Alles sperren": "Block everything",
    "Benachrichtigung bei Unterschreitung": "Notification when stock runs low",
    "Die Mail geht an die verantwortliche Person, Stellvertretungen stehen im CC.": "The mail goes to the responsible person, deputies are in CC.",
    "Sofort bei jeder Unterschreitung": "Immediately, every time",
    "Einmal am Tag, gesammelt": "Once a day, collected",
    "Einmal in der Woche": "Once a week",
    "Einmal im Monat": "Once a month",
    "Uhrzeit": "Time",
    "Wochentag": "Weekday",
    "Tag im Monat": "Day of month",
    "Aktuell aktiv": "Currently active",
    "Bei gesammelten Mails entsteht automatisch eine Bestellliste mit allen Produktinfos.": "Collected mails automatically produce an order list with all product details.",
    "Sprache und Darstellung": "Language and appearance",
    "Sprache dieses Kontos": "Language of this account",
    "Design": "Appearance",
    "Passwort ändern": "Change password",
    "Aktuelles Passwort": "Current password",
    "Neues Passwort": "New password",
    "Neues Passwort wiederholen": "Repeat new password",
    "Passwort speichern": "Save password",
    "Firmen": "Companies",
    "Firma": "Company",
    "Abo": "Plan",
    "Angelegt": "Created",
    "Passwort": "Password",
    "Löschen": "Delete",
    "Betriebszugang: Firmen und Personen sperren, löschen, Passwort-Neuanforderung schicken. Produktdaten der Firmen sind hier nicht sichtbar — jede Firma sieht nur ihr eigenes Lager.": "Operator access: block or delete companies and people, trigger password resets. Company product data is not visible here — each company only ever sees its own stock.",
    "Anmelden": "Sign in",
    "Registrieren": "Register",
    "Einladung": "Invitation",
    "Ich habe schon ein Konto": "I already have an account",
    "Neue Firma anlegen": "Create a new company",
    "Konto anlegen": "Create account",
    "Ich bin kein Bot": "I am not a bot",
    "Derzeit kostenlos, jederzeit kündbar.": "Free for now, cancel anytime.",
    "E-Mail bestätigen": "Confirm your email",
    "Wir haben dir einen Link geschickt. Er gilt 15 Minuten.": "We sent you a link. It is valid for 15 minutes.",
    "Neue Mail anfordern": "Request a new mail",
    "Zugang einrichten": "Set up access",
    "Einladung zu Internet GmbH · läuft in 2 Std. 41 Min. ab": "Invitation to Internet GmbH · expires in 2 h 41 min",
    "Wir schicken dir einen Link, der 15 Minuten gültig ist.": "We will send you a link, valid for 15 minutes.",
    "Zurück zur Anmeldung": "Back to sign in",
    "Zweiter Faktor": "Second factor",
    "Anmeldung": "Sign-in",
    "E-Mail oder Passwort falsch": "Wrong email or password",
    "Kostenbremse": "Cost guard",
    "Kosten": "Cost",
    "Grenze erreicht": "Limit reached",
    "Scannen statt suchen": "Scan, don't search",
    "Nie wieder leer": "Never run out",
    "Jede Person ihr Maß": "Rights that fit",
    "Nur euer Lager": "Only your stock",
    "Jeder Code gehört zu genau einem Artikel und öffnet dessen Detailansicht. Etiketten mit eigenem Text drucken.": "Each code belongs to exactly one item and opens its detail view. Print labels with your own text.",
    "Warnung sofort oder gesammelt — täglich, wöchentlich, monatlich. Verantwortliche Person direkt, Stellvertretung im CC.": "Alerts immediately or collected — daily, weekly, monthly. The responsible person directly, deputies in CC.",
    "Vier Rollen als Vorlage, jedes Recht einzeln anpassbar — von Buchen bis Exportieren.": "Four roles as templates, every right adjustable one by one — from booking to exporting.",
    "Daten in der EU, streng pro Firma getrennt. Das steckt in der Datenbank, nicht in der Oberfläche.": "Data in the EU, strictly separated per company. That sits in the database, not in the interface.",
    "Bot-Schutz und Sperre nach fünf Fehlversuchen": "Bot check and lockout after five failed attempts",
    "Bestätigungslink gültig 15 Minuten": "Confirmation link valid for 15 minutes",
    "Bilder nur über signierten Zugriff": "Images only via signed access",
    "Nicht eingerichtet": "Not set up",
    "Konto sofort aktiv — keine Mail": "Account active immediately — no mail",
    "In Supabase ist „Confirm email\" ausgeschaltet. Einschalten unter Authentication → Providers → Email.": "\"Confirm email\" is switched off in Supabase. Turn it on under Authentication → Providers → Email.",
    "Die Registrierung wurde abgelehnt:": "The registration was rejected:",
    "Mail erneut angefordert": "Mail requested again",
    "Scannen, Menge eingeben, fertig. Den Rest macht das System.": "Scan, enter the quantity, done. The system does the rest.",
    "Mindestbestand erreicht": "Minimum reached",
    "vor 12 Wochen": "12 weeks ago",
    "heute": "today",
    "In config.js fehlen SUPABASE_URL und SUPABASE_ANON_KEY. Ohne sie gibt es keine Datenbank und keine Mail. Die Schritte stehen in SETUP.md.": "SUPABASE_URL and SUPABASE_ANON_KEY are missing in config.js. Without them there is no database and no mail. The steps are in SETUP.md.",
    "Code eingeben": "Enter code",
    "Artikel-ID oder EAN": "Item ID or EAN",
    "Scan-Adresse": "Scan address",
    "Person verdeckt": "Person hidden",
    "Nur zum Ansehen": "View only",
    "Eine Spalte pro Feld. In „Quantität 1–3\" die Namen aus den Einstellungen eintragen.": "One column per field. In Quantity 1–3 enter the names from the settings.",
    "Bestellmenge eintragen": "Enter order quantity",
    "Alle Positionen nachfüllen": "Refill all positions",
    "Nachfüllen": "Refill",
    "nachgefüllt": "refilled",
    "Bestellung abschließen": "Close order",
    "Keine Menge eingetragen": "No quantity entered",
    "Menge und Quantität eintragen, dann nachfüllen.": "Enter amount and unit, then refill.",
    "Bestand erhöht": "Stock increased",
    "Nachfüllung aus Bestellung": "Refill from order",
    "Abgeschlossen": "Closed",
    "Bestandswert im Zeitverlauf": "Stock value over time",
    "Bestandswert": "Stock value",
    "Preisänderung — anklicken": "Price change — click",
    "Markierung lösen": "Clear marker",
    "Markierungen ausblenden": "Hide markers",
    "Preisänderungen markieren": "Mark price changes",
    "Bestand × gültiger Preis · letzte ": "Stock × valid price · last ",
    " Tage": " days",
    "jetzt ": "now ",
    "Bestandswert an dem Tag: ": "Stock value that day: ",
    "Menge in ": "Quantity in ",
    "in der kleinsten Einheit": "in the smallest unit",
    "Zu den Quantitäten": "To quantities",
    "Zu den Abteilungen": "To departments",
    "Zur Produktverwaltung": "To product management",
    "Zu den Einstellungen": "To settings",
    "Zu den Bestellungen": "To orders",
    "Zu den Events": "To events",
    "Zum Bestandswert": "To stock value",
    "Zu den Lagerorten": "To storage locations",
    "Einkauf": "Purchasing",
    "Bestellliste und Bestellungen": "Order list and orders",
    "Planung": "Planning",
    "Konto": "Account",
    "Anmeldung und Sprache": "Sign-in and language",
    "Wie übernehme ich eine bestehende Liste?": "How do I bring in an existing list?",
    "Stammdaten → Produktverwaltung, Karte „Viele Produkte aus einer Tabelle importieren\". Vorlage herunterladen — leer oder mit dem heutigen Bestand —, in Excel ausfüllen und wieder hochladen. Gelesen werden Excel (.xlsx) und CSV.": "Master data → Product management, card “Import many products from a table”. Download the template — empty or with today's stock —, fill it in Excel and upload it again. Excel (.xlsx) and CSV are read.",
    "Istbestand, Mindestbestand und Bestellmenge stehen in der Standardquantität des Produkts. Zeilen mit Fehlern werden vor dem Übernehmen einzeln angezeigt.": "Stock, minimum and order quantity are in the product's default quantity. Rows with errors are listed one by one before importing.",
    "Auf dem Buchungsschirm zählt das Hauptfeld in der Standardquantität. Darunter steht für jede weitere Quantität ein eigenes Feld — zwei Kästen und drei Flaschen ergeben automatisch die richtige Gesamtmenge.": "On the booking screen the main field counts in the default quantity. Below it each further quantity has its own field — two crates and three bottles give the right total automatically.",
    "Welche Quantitäten ein Produkt hat, steht in seinem Detail unter „Bearbeiten\".": "Which quantities a product has is set in its detail under “Edit”.",
    "Wie lege ich Quantitäten und die Standardquantität fest?": "How do I set quantities and the default quantity?",
    "Einstellungen → Quantitäten: Gebinde wie Flasche, Kasten oder Palette anlegen und angeben, wie viele der kleineren darin stecken — 1 Kasten = 12 Flaschen.": "Settings → Quantities: create packs such as bottle, crate or pallet and state how many of the smaller ones they hold — 1 crate = 12 bottles.",
    "Im Produkt die passenden Quantitäten anhaken und eine als Standardquantität wählen. In ihr werden Bestand, Mindestbestand und Bestellmenge gezeigt, gebucht und in Mails genannt; was nicht aufgeht, steht in den kleineren Quantitäten daneben.": "In the product tick the matching quantities and choose one as the default. Stock, minimum and order quantity are shown, booked and mailed in it; any remainder appears in the smaller quantities.",
    "Wie trage ich das Mindesthaltbarkeitsdatum ein?": "How do I enter the best-before date?",
    "Beim Nachfüllen und in offenen Bestellungen gibt es ein Feld „MHD\". Jede Lieferung behält ihr eigenes Datum.": "When refilling and in open orders there is a “Best before” field. Each delivery keeps its own date.",
    "Entnommen wird nach „first in, first out\": das älteste MHD zuerst.": "Withdrawals follow “first in, first out”: the oldest date first.",
    "Wie verschicke ich die Bestellliste sofort?": "How do I send the order list right away?",
    "Einstellungen → Benachrichtigungen → „Bestellliste jetzt mailen\". Inhaber und Lagerleitung bekommen alles unter Mindestbestand, die Mengen in der Standardquantität jedes Produkts.": "Settings → Notifications → “Mail order list now”. Owner and warehouse management get everything below minimum, quantities in each product's default quantity.",
    "Was zeigt der Bestandswert?": "What does the stock value show?",
    "In der Karte „Preisverlauf und Umsatz\": Bestand × Preis, der an dem Tag galt, über den gewählten Zeitraum. Bei einem einzelnen Produkt zeigt die gestrichelte Linie den Wert des Mindestbestands.": "In the card “Price history and revenue”: stock × the price valid that day, over the chosen period. For a single product the dashed line shows the value of the minimum stock.",
    "Tage mit Preisänderung sind als Raute markiert. Ein Klick darauf — oder auf die Zeile in der Tabelle „Preisänderungen\" — zeigt alten und neuen Preis.": "Days with a price change carry a diamond. Clicking it — or the row in the “Price changes” table — shows old and new price.",
    "Wie arbeite ich mit Abteilungen?": "How do I work with departments?",
    "Einstellungen → Abteilungen: Abteilungen anlegen und Personen zuordnen. Eine Person kann in mehreren Abteilungen sein.": "Settings → Departments: create departments and assign people. One person can be in several departments.",
    "Oben in der Menüleiste wird die Abteilung gewechselt. Produkte, Bestellungen, Events, Merkzettel und Verlauf zeigen dann nur ihre Daten; „Ganze Firma\" zählt alles zusammen.": "Switch the department at the top of the menu bar. Products, orders, events, notes and history then show only its data; “Whole company” adds everything up.",
    "Wie kopiere ich Produkte in eine andere Abteilung?": "How do I copy products to another department?",
    "Stammdaten → Produktverwaltung: ein oder mehrere Produkte auswählen, Zielabteilung wählen, kopieren. Die Kopie bekommt eine eigene Kennung und einen neuen QR-Code; der Bestand wird getrennt geführt.": "Master data → Product management: select one or more products, choose the target department, copy. The copy gets its own ID and a new QR code; stock is kept separately.",
    "Das Etikett der Kopie neu drucken — sonst bucht der Scan im ursprünglichen Produkt.": "Print a new label for the copy — otherwise scanning books on the original product.",
    "Was sieht welche Abteilung?": "What does each department see?",
    "Einstellungen → Sichtbarkeit je Abteilung: Lagerorte, Quantitäten und Merkmale lassen sich für einzelne Abteilungen ausblenden. Wer dort arbeitet, bekommt sie in Auswahllisten nicht angeboten.": "Settings → Visibility per department: storage locations, quantities and attributes can be hidden for single departments. People working there no longer see them in pick lists.",
    "Wie benenne ich einen Lagerort um?": "How do I rename a storage location?",
    "Einstellungen → Lagerorte, beim Lagerort „Umbenennen\" wählen. Alle Produkte an diesem Ort ziehen automatisch mit.": "Settings → Storage locations, choose “Rename” on the location. All products there move along automatically.",
    "Warum ist eine Seite für mich gesperrt?": "Why is a page locked for me?",
    "Welche Seiten und Aktionen jemand nutzen darf, legt die Rolle fest; einzelne Rechte können je Person abweichen. Freigeben kann, wer das Recht „Rechte ändern\" hat.": "The role sets which pages and actions someone may use; single rights can differ per person. Anyone with the right “Change rights” can unlock them.",
    "Die Hilfe ist für alle immer offen.": "Help is always open to everyone.",
    "Wie entsteht die Bestellliste?": "How is the order list built?",
    "Lager → Bestellungen. Jedes aktive Produkt unter Mindestbestand steht dort bei der verantwortlichen Person — verschiebbar zu jeder anderen. Oben lässt sich nach Abteilung filtern.": "Stock → Orders. Every active product below minimum is listed with its responsible person — movable to anyone else. Filter by department at the top.",
    "„Alle mit Bestellmenge in Bestellung\" übernimmt die hinterlegte Bestellmenge. Sie steht zuerst in der Standardquantität; nur was darin nicht aufgeht, kommt in die kleineren Quantitäten.": "“Order all with order quantity” takes the stored order quantity. It goes into the default quantity first; only a remainder goes into the smaller quantities.",
    "Die Ware ist da — was jetzt?": "The goods have arrived — now what?",
    "In der offenen Bestellung die gelieferte Menge prüfen, bei Bedarf das MHD eintragen und zurück in den Bestand buchen. Der Bestand steigt, das Produkt verlässt die Bestellung.": "In the open order check the delivered amount, enter the best-before date if needed and book it back into stock. Stock rises and the product leaves the order.",
    "Wie plane ich ein Event?": "How do I plan an event?",
    "Lager → Events: Name, Datum, Ort und die benötigten Artikel mit Menge eintragen. Beim Anlegen entsteht die Bedarfsliste mit den Fehlmengen gegenüber dem heutigen Bestand.": "Stock → Events: enter name, date, place and the needed items with amounts. Saving creates the demand list with shortfalls against today's stock.",
    "„Bestellung abschicken\" setzt die Fehlmengen auf die Bestelllisten der Verantwortlichen.": "“Send order” puts the shortfalls on the responsible people's order lists.",
    "Was zeigt die Vorschau?": "What does the preview show?",
    "Alle kommenden Events — oder die eines Zeitraums — zusammengerechnet und gegen den heutigen Bestand gestellt. „Nur noch nicht bestellte\" blendet aus, was schon unterwegs ist. Das Ergebnis lässt sich als Excel exportieren.": "All upcoming events — or those in a period — added up and set against today's stock. “Only not yet ordered” hides what is already on its way. The result can be exported to Excel.",
    "Auf der Anmeldeseite „Passwort vergessen?\" wählen. Der Link in der Mail gilt 15 Minuten.": "Choose “Forgot password?” on the sign-in page. The link in the mail is valid for 15 minutes.",
    "Wie schütze ich mein Konto zusätzlich?": "How do I protect my account further?",
    "In den Einstellungen Zwei-Faktor einrichten. Danach fragt die Anmeldung zusätzlich einen Code aus der Authenticator-App ab.": "Set up two-factor in the settings. Sign-in then also asks for a code from the authenticator app.",
    "Wie ändere ich die Sprache?": "How do I change the language?",
    "Oben rechts in der Menüleiste DE, EN oder SV wählen.": "Choose DE, EN or SV at the top right of the menu bar.",
    "Sprache": "Language",
    "Nur beim Bearbeiten": "Only while editing",
    "Zuweisen nur beim Bearbeiten oder über die Excel-Tabelle.": "Assign only while editing or via the Excel sheet.",
    "Oben auf „Bearbeiten\" tippen, dann lassen sich Quantitäten zuweisen.": "Tap Edit above, then quantities can be assigned.",
    "Standardquantität": "Default quantity",
    "Standardquantität wählen.": "Choose a default quantity.",
    "Standardquantität fehlt.": "Default quantity missing.",
    "Mindestens eine Quantität anhaken.": "Tick at least one quantity.",
    "Gebucht und angezeigt wird in ": "Booked and shown in ",
    "Bestände und Mindestmengen zählen in der kleinsten Einheit": "Stock and minimums count in the smallest unit",
    "Menge eintragen, dann buchen.": "Enter a quantity, then book.",
    "Buchung": "Booking",
    "Rechte speichern": "Save rights",
    "Rechte gespeichert": "Rights saved",
    "Rechte nicht gespeichert": "Rights not saved",
    "Nicht gespeicherte Änderungen": "Unsaved changes",
    "Alle Rechte sind gespeichert.": "All rights are saved.",
    "Nur in dieser Sitzung — ohne Datenbank.": "This session only — no database.",
    "Quantität unbekannt: ": "Unknown quantity: ",
    "Standardquantität unbekannt: ": "Unknown default quantity: ",
    "Standardquantität fehlt — vorläufig gesetzt: ": "Default quantity missing — set for now: ",
    "Keine Quantität zugewiesen": "No quantity assigned",
    "ist keine ganze Zahl ab 0 — als 0 übernommen": "is not a whole number from 0 — imported as 0",
    "wirkt unplausibel hoch — bitte prüfen": "looks implausibly high — please check",
    "Preis nicht lesbar: ": "Price not readable: ",
    "MHD nicht lesbar: ": "Best-before not readable: ",
    "Verantwortliche Person nicht im Team: ": "Responsible person not in team: ",
    "Stellvertretung nicht im Team: ": "Deputy not in team: ",
    "Mehr als 3 Stellvertretungen — nur die ersten 3 übernommen": "More than 3 deputies — only the first 3 imported",
    "Zeile wurde nicht so übernommen, wie sie in der Datei steht.": "row was not imported exactly as in the file.",
    "Zeilen wurden nicht so übernommen, wie sie in der Datei stehen.": "rows were not imported exactly as in the file.",
    "Korrigieren lässt sich das in der Produktbearbeitung oder mit einem neuen Import.": "Fix it in product editing or with a new import.",
    "Fehler beim Import": "Import errors",
    "Verstanden": "Got it",
    "Fehlerliste herunterladen": "Download error list",
    "Standard": "default",
    "Etiketten gestalten": "Design labels",
    "Format": "Format",
    "Texte für alle Etiketten": "Texts for all labels",
    "Schriftgrößen": "Font sizes",
    "Produktname": "Product name",
    "Artikel-ID": "Item ID",
    "ID-Größe": "ID size",
    "Ein Etikett in der Vorschau anklicken, um es einzeln zu beschriften.": "Click a label in the preview to customise it individually.",
    "Einzelnes Etikett": "Single label",
    "Produktname zeigen": "Show product name",
    "Artikel-ID zeigen": "Show item ID",
    "Fertig": "Done",
    "Auf Vorgabe zurücksetzen": "Reset to defaults",
    "A4 · 1 Code je Blatt": "A4 · 1 code per sheet",
    "A5 · 2 je Blatt": "A5 · 2 per sheet",
    "A6 · 4 je Blatt": "A6 · 4 per sheet",
    "Bestelllisten je Person": "Order lists per person",
    "Alles, was offen ist — aus der Bestellliste, aus Bestellungen und aus kommenden Events — landet zuerst bei der verantwortlichen Person. Einzelne Positionen lassen sich zu einer anderen Person verschieben.": "Everything open — from the order list, from orders and from upcoming events — goes to the responsible person first. Single items can be moved to another person.",
    "Quelle": "Source",
    "Verschieben zu": "Move to",
    "Verschoben": "Moved",
    "Für diese Person ist gerade nichts offen.": "Nothing is open for this person right now.",
    "Eigene Personenbestellliste für alle sichtbar": "Own personal order list visible to everyone",
    "Nur die inhabende Person": "Owner only",
    "Ob eine Personenbestellliste für alle sichtbar ist, legt die inhabende Person fest.": "The owner decides whether a personal order list is visible to everyone.",
    "Bestellung": "Order",
    "Seite: Übersicht": "Page: Overview",
    "Seite: Produkte": "Page: Products",
    "Seite: Scannen": "Page: Scan",
    "Seite: Bestellungen": "Page: Orders",
    "Seite: Events": "Page: Events",
    "Seite: Bestandsverlauf": "Page: Stock history",
    "Seite: Produktverwaltung": "Page: Product management",
    "Seite: QR-Codes": "Page: QR codes",
    "Seite: Team & Rechte": "Page: Team & rights",
    "Seite: Einstellungen": "Page: Settings",
    "Seite: Hilfe": "Page: Help",
    "Diese Seite ist für dich gesperrt.": "This page is locked for you.",
    "Freigeben kann sie, wer das Recht „Rechte ändern\" hat.": "Anyone with the “Change rights” permission can unlock it.",
    "Event bearbeiten": "Edit event",
    "Name, Datum und mindestens ein Artikel sind nötig.": "Name, date and at least one item are required.",
    "Name und Datum fehlen": "Name and date missing",
    "Ein Event braucht einen Namen und ein Datum.": "An event needs a name and a date.",
    "Event löschen": "Delete event",
    "Das Event und seine Bedarfsliste werden entfernt. Bestände und Buchungen bleiben unberührt.": "The event and its requirement list are removed. Stock and bookings stay untouched.",
    "Bewegungen rückgängig machen": "Undo movements",
    "Buchung rückgängig machen": "Undo booking",
    "Die Buchung wird durch eine Gegenbuchung aufgehoben und verschwindet aus Verlauf und Auswertungen.": "The booking is cancelled by a counter-booking and disappears from history and analytics.",
    "Geht nicht": "Not possible",
    "Der Bestand würde unter 0 fallen.": "Stock would drop below 0.",
    "Die Buchung wird noch gespeichert — gleich noch einmal versuchen.": "The booking is still being saved — try again in a moment.",
    "Geändert": "Changed",
    "Produkte angepasst": "products updated",
    "Ersetzen durch": "Replace with",
    "— keine, nur entfernen —": "— none, just remove —",
    "Wähle, durch welche Quantität sie in Produkten ersetzt wird. Quantitäten, die sich darauf beziehen, zeigen dann auf die Ersatzquantität.": "Choose which quantity replaces it in products. Quantities that refer to it then point to the replacement.",
    "Bitte einen Wert aus der Liste wählen.": "Please choose a value from the list.",
    "Lagerort, Quantitäten und Personen sind Auswahllisten.": "Location, quantities and people are drop-down lists.",
    "Keine gültige Excel-Datei": "Not a valid Excel file",
    "Dieser Browser kann Excel-Dateien nicht entpacken — bitte als CSV speichern.": "This browser cannot unpack Excel files — please save as CSV.",
    "Keine Tabelle in der Datei gefunden": "No sheet found in the file",
    "Datei hierher ziehen oder klicken · .xlsx oder .csv bis 5 MB": "Drag a file here or click · .xlsx or .csv up to 5 MB",
    "dazu einzeln": "plus single",
    "Istbestand einzeln": "Stock single",
    "ist keine Zahl ab 0 — als 0 übernommen": "is not a number from 0 — imported as 0",
    "ergibt keine ganze Einzelmenge — gerundet auf ": "does not give a whole single amount — rounded to ",
    "ist keine ganze Zahl ab 0 — nicht übernommen": "is not a whole number from 0 — not imported",
    "Istbestand, Mindestbestand und Bestellmenge in dieser Quantität angeben": "Enter stock, minimum and order quantity in this quantity",
    "einzelne im Feld „dazu einzeln“": "single ones in the field “plus single”",
    "Istbestand einzeln ohne größere Standardquantität — zum Istbestand addiert": "Single stock without a larger default quantity — added to stock",
    "Istbestand einzeln ist ein volles Gebinde oder mehr — trotzdem addiert: ": "Single stock is a full pack or more — added anyway: ",
    "Kein Zugriff auf die Rechteverwaltung": "No access to rights administration",
    "Wer welche Rechte hat, sehen und ändern nur die inhabende Person und wer das Recht „Rechte ändern\" ausdrücklich bekommen hat.": "Who holds which rights is visible and editable only to the owner and to anyone expressly given the right to change rights.",
    "Bestellung nicht gespeichert": "Order not saved",
    "Bitte supabase/schema.sql im SQL-Editor erneut ausführen.": "Please run supabase/schema.sql in the SQL editor again.",
    "Bestellungen": "Orders",
    "Offene Bestellungen": "Open orders",
    "In Bestellung": "Order placed",
    "Alle in Bestellung": "Order all",
    "Zurück in Bestand": "Back to stock",
    "Alles zurück in Bestand": "All back to stock",
    "Nichts in Bestellung": "Nothing on order",
    "Zur Bestellliste": "To the order list",
    "bestellt von ": "ordered by ",
    "Ohne Zuordnung": "Unassigned",
    "früher gesetzt": "set earlier",
    "Ohne Bestellmengen — erst über die Bestellliste in Bestellung setzen, dann lässt sich hier nachgefüllt werden.": "No order amounts — put it on order from the order list first, then it can be refilled here.",
    "Nichts offen": "Nothing open",
    "Kein Artikel unter Mindestbestand.": "No item below minimum.",
    "steht schon in Bestellung": "is already on order",
    "Bestand ": "Stock ",
    "Min ": "Min ",
    "am": "on the",
    "Samstag": "Saturday",
    "Sonntag": "Sunday",
    "Zurück zu den Produkten": "Back to products",
    "Was über die Bestellmail oder aus der Bestellliste in Bestellung gesetzt wurde, steht hier als Bündel. Solange ein Artikel hier steht, taucht er nicht wieder in der Bestellliste auf und löst keine Mail aus.": "Whatever was put on order from the order mail or the order list appears here as a batch. While an item sits here it will not reappear in the order list and triggers no mail.",
    "Sobald ein Artikel in Bestellung gesetzt wird — hier, im Produkt oder über den Knopf in der Bestellmail — erscheint er an dieser Stelle.": "As soon as an item is put on order — here, on the product, or via the button in the order mail — it shows up in this place.",
    "Artikel suchen": "Search items",
    "Name, Kennung, EAN, Lagerort …": "Name, code, EAN, location …",
    "Weniger anzeigen": "Show fewer",
    "weitere anzeigen": "more",
    "Nicht genug Bestand": "Not enough stock",
    "Vorhanden: ": "Available: ",
    "Die Entnahme wurde nicht gebucht.": "The withdrawal was not booked.",
    "Vorhanden sind nur ": "Only available: ",
    "so viel lässt sich nicht entnehmen.": "that much cannot be withdrawn.",
    "Leere Liste mit einer Beispielzeile": "Empty list with one example row",
    "Quantität löschen": "Delete quantity",
    "wird verwendet": "is in use",
    "Stelle": "place",
    "Stellen": "places",
    "Diese Quantität ist im Einsatz: ": "This quantity is in use: ",
    "Wird sie gelöscht, verlieren diese Produkte ihre Umrechnung — die gebuchten Mengen bleiben stehen. Quantitäten, die sich darauf beziehen, werden eigenständig.": "If it is deleted, these products lose their conversion — booked amounts stay as they are. Quantities that refer to it become standalone.",
    "Betroffen": "Affected",
    "weitere": "more",
    "Trotzdem löschen": "Delete anyway",
    "bezieht sich darauf": "refers to it",
    "Vorschau bis Datum": "Preview up to a date",
    "Stichtag": "Cut-off date",
    "Vorschau rechnen": "Calculate preview",
    "Alles, was bis zu einem Stichtag in Events gebraucht wird, zusammengerechnet und gegen den heutigen Bestand gestellt.": "Everything needed for events up to a cut-off date, added up and set against today's stock.",
    "Bedarf": "Needed",
    "Rest": "Left",
    "Vorschau schließen": "Close preview",
    "Vorschau exportiert": "Preview exported",
    "Bis zu diesem Datum ist kein Event geplant.": "No event is planned up to that date.",
    "nicht ausreichend": "not sufficient",
    "Bestand reicht überall": "stock is sufficient throughout",
    "fehlt: ": "short by: ",
    "danach unter Mindestbestand": "below minimum afterwards",
    "Lager und Artikel": "Stock and items",
    "Lagerorte, Gebinde und eigene Felder": "Locations, packs and custom fields",
    "Warnungen und Mail": "Alerts and mail",
    "Wann wer eine Nachricht bekommt": "Who gets notified, and when",
    "Mein Konto": "My account",
    "Sprache, Darstellung, Anmeldung": "Language, appearance, sign-in",
    "System und Kosten": "System and cost",
    "Dienste, Mailversand prüfen, Grenzen": "Services, mail check, limits",
    "Nicht gefunden": "Not found",
    "Kein Artikel mit dieser ID oder EAN.": "No item with that ID or EAN.",
    "Datei auswählen": "Choose file",
    "Spalten geprüft — unten bestätigen.": "Columns checked — confirm below.",
    "Keine Datenbank verbunden": "No database connected",
    "Mail-Tagesgrenze erreicht — Sammelversand morgen.": "Daily mail limit reached — collected send tomorrow.",
    "In config.js FREE_TIER_GUARD auf false setzen oder die Grenze anheben.": "Set FREE_TIER_GUARD to false in config.js, or raise the limit.",
    "aktiv": "on",
    "aus": "off",
    "Mails heute": "Mails today",
    "Mails am Tag": "mails per day",
    "Zeilen je Import": "rows per import",
    "MB je Datei": "MB per file",
    "MB Speicher": "MB of storage",
    "Speicher": "Storage",
    "gesetzt": "fixed",
    "Das geht nicht": "Not possible",
    "Mindestens eine aktive Person muss die Rechte verwalten können. Vergib die Rolle zuerst an jemand anderen.": "At least one active person must be able to manage rights. Assign the role to someone else first.",
    "Diese Person verwaltet aktuell allein die Rechte. Rolle, Zugang und das Recht „Rechte ändern\" sind deshalb gesperrt — vergib die Rolle zuerst an jemand anderen.": "This person is currently the only one managing rights. Role, access and the \"change rights\" permission are therefore locked — assign the role to someone else first.",
    "Aktionen, die eine Grenze überschreiten würden, werden abgelehnt. So entstehen bei keinem der vier Dienste Kosten.": "Actions that would exceed a limit are refused, so none of the four services can incur cost.",
    "Keine Sperre. Alles ist erlaubt — auch über die Gratis-Kontingente hinaus, wodurch Kosten entstehen können.": "No guard. Everything is allowed, including beyond the free tiers, which may incur cost.",
    "Umschalten in config.js: FREE_TIER_GUARD auf false setzen hebt die Sperre auf, einzelne Grenzen stehen in FREE_TIER_LIMITS.": "Toggle in config.js: setting FREE_TIER_GUARD to false lifts the guard; individual limits live in FREE_TIER_LIMITS.",
    "Bitte noch einmal versuchen.": "Please try again.",
    "Mehr erfahren": "Learn more",
    "Sechsstelligen Code aus deiner Authenticator-App eingeben.": "Enter the six-digit code from your authenticator app.",
    "Code": "Code",
    "Bestätigen": "Confirm",
    "Code falsch": "Wrong code",
    "Zwei-Faktor-Anmeldung": "Two-factor sign-in",
    "Zusätzlich zum Passwort ein Code aus einer App. Schützt auch dann, wenn das Passwort bekannt wird.": "A code from an app on top of your password. Protects you even if the password leaks.",
    "Einrichten": "Set up",
    "Entfernen": "Remove",
    "QR-Code in der App scannen, dann den ersten Code eingeben.": "Scan the QR code in the app, then enter the first code.",
    "Zwei-Faktor aktiv": "Two-factor active",
    "Zwei-Faktor entfernt": "Two-factor removed",
    "Nur noch Passwort.": "Password only from now on.",
    "Beim nächsten Anmelden wird ein Code verlangt.": "A code will be required at the next sign-in.",
    "Nur im verbundenen Betrieb": "Only when connected",
    "Zwei-Faktor braucht Supabase.": "Two-factor needs Supabase.",
    "Buchungen anzeigen": "Show entries",
    "Buchungen ausblenden": "Hide entries",
    "Einzelne Buchungen": "Individual entries",
    "Kostenlos starten": "Start for free",
    "QR-Code am Regal scannen": "Scan the code on the shelf",
    "Warenüberblick mit Warnung und Bestellliste": "Stock overview with alerts and order list",
    "Daten in der EU, pro Firma getrennt": "Data in the EU, separated per company",
    "Das Lager im Griff — mit einem Scan.": "Your stock, one scan away.",
    "QR-Code am Regal scannen, Entnahme buchen, fertig. Fällt der Bestand unter das Minimum, geht automatisch eine Mail an die verantwortliche Person — und die Bestellliste schreibt sich selbst.": "Scan the shelf code, book the withdrawal, done. Drop below the minimum and the responsible person gets a mail automatically — and the order list writes itself.",
    "Firma registrieren": "Register your company",
    "Ich habe ein Konto": "I have an account",
    "Sprachen": "languages",
    "im Einstieg": "to start",
    "Datenhaltung": "data residency",
    "Nach dem Scan": "After the scan",
    "Bestellen": "Order",
    "QR-Code am Regal": "A code on every shelf",
    "Automatisch": "Automatic",
    "Warnung sofort oder gesammelt — täglich, wöchentlich, monatlich. Die Bestellliste entsteht von allein.": "Alerts instantly or collected — daily, weekly, monthly. The order list builds itself.",
    "Getrennt": "Separated",
    "Jede Firma sieht ausschließlich eigene Artikel. Das steckt in der Datenbank, nicht in der Oberfläche.": "Every company sees only its own items. That lives in the database, not the interface.",
    "So läuft es im Alltag": "How it works day to day",
    "Anlegen": "Set up",
    "Etikettieren": "Label",
    "Buchen": "Book",
    "Artikel einzeln eintragen oder eine Excel-Tabelle hochladen.": "Enter items one by one or upload a spreadsheet.",
    "QR-Codes drucken und ans Regal kleben.": "Print QR codes and stick them on the shelf.",
    "Scannen, Menge eingeben, entnehmen. Wer und wann steht im Protokoll.": "Scan, enter a quantity, take it. Who and when is logged.",
    "Mail kommt, Liste steht, Status auf „ist bestellt\" setzen.": "The mail arrives, the list is ready, set the status to ordered.",
    "In zehn Minuten eingerichtet": "Set up in ten minutes",
    "Eine Person aus dem Unternehmen registriert sich, lädt das Team ein und legt die ersten Artikel an.": "One person from the company registers, invites the team and adds the first items.",
    "Jetzt registrieren": "Register now",
    "Daten in der EU · Jede Firma getrennt · Kein öffentlicher Zugriff": "Data in the EU · Every company separated · No public access",
    "Zur Startseite": "Back to start",
    "Startseite": "Start",
    "Lagerverwaltung, die dem Regal folgt.": "Stock management that follows the shelf.",
    "Scannen, buchen, nachbestellen — und jede Firma sieht ausschließlich ihr eigenes Lager.": "Scan, book, reorder — and every company sees only its own stock.",
    "QR-Code scannen, Entnahme in Sekunden buchen": "Scan a code, book a withdrawal in seconds",
    "Warnmail und Bestellliste entstehen von allein": "Alert mails and order lists build themselves",
    "Rechte pro Person, bis auf das einzelne Recht": "Rights per person, down to the single permission",
    "Mail an Marie Kohl, Stellvertretung im CC: Bestand 6 unter Mindestbestand 10.": "Mail to Marie Kohl, deputies in CC: stock 6 below minimum 10.",
    "Registrierung und Anmeldung sind durch Rate-Limit, Bot-Prüfung und Sperre nach fünf Fehlversuchen geschützt.": "Registration and sign-in are protected by rate limiting, a bot check and a lockout after five failed attempts.",
    "Zu Mein Konto": "Go to my account",
    "Tutorials": "Tutorials",
    "Tutorial starten": "Start tutorial",
    "Tutorial beenden": "End tutorial",
    "Schritt für Schritt auf den echten Seiten — jedes Tutorial für sich": "Step by step on the real pages — each tutorial on its own",
    "Persönliche Einstellungen wie Sprache, Design und Passwort findest du unter „Mein Konto\".": "Personal settings such as language, theme and password are under “My account”.",
    "Keine Einstellungen freigegeben": "No settings available",
    "Die Bereiche „Lager und Artikel\" und „Warnungen und Mail\" hat die inhabende Person für dich gesperrt. Deine persönlichen Einstellungen findest du unter „Mein Konto\".": "The owner has locked “Storage and items” and “Warnings and mail” for you. Your personal settings are under “My account”.",
    "Diese Seite gehört dir: Sprache, Design und Passwort gelten nur für dein Konto. Niemand kann sie für dich sperren.": "This page is yours: language, theme and password apply only to your account. Nobody can lock it for you.",
    "Meine Rechte": "My permissions",
    "Was du in dieser Firma darfst. Ändern kann das nur, wer das Recht „Rechte ändern\" hat.": "What you may do in this company. Only people with “Change permissions” can change it.",
    "Buchen ist für dich gesperrt. Freigeben kann das, wer das Recht „Rechte ändern\" hat.": "Booking is locked for you. Anyone with “Change permissions” can unlock it.",
    "Dieser Bereich ist gerade nicht zu sehen — etwa weil er für dich gesperrt ist oder noch Daten fehlen. Mit „Weiter\" geht es trotzdem.": "This part isn't visible right now — perhaps it is locked for you or data is missing. “Next” continues anyway.",
    "Einklappen": "Collapse",
    "Aufklappen": "Expand",
    "Weiter": "Next",
    "Schritt": "Step",
    "Schritte": "steps",
    "erlaubt": "allowed",
    "gesperrt": "locked",
    "Seiten": "Pages",
    "Produkte und Buchungen": "Products and bookings",
    "Team und Profile": "Team and profiles",
    "Auswertung und Dateien": "Reports and files",
    "Einstellungen: Lager und Artikel": "Settings: storage and items",
    "Einstellungen: Warnungen und Mail": "Settings: warnings and mail",
    "Für dich gesperrt — dafür fehlt dir ein Recht.": "Locked for you — a permission is missing."
  },
  // Platzhalter in Eingabefeldern
  platzhalter: {
    "Name, EAN, Lieferant …": "Name, EAN, supplier …",
    "z. B. Kaffeebohnen 1 kg": "e.g. coffee beans 1 kg",
    "Einzelflasche, Kasten …": "Single bottle, crate …",
    "Getränke Nord GmbH": "Supplier name",
    "Getränke, Küche, Verbrauchsmaterial — mit Komma trennen": "Drinks, kitchen, consumables — comma separated",
    "z. B. Keller · Regal B2": "e.g. Basement · Shelf B2",
    "z. B. Bei Entnahme scannen": "e.g. Scan when taking stock"
  }
};
