// Schwedisch — Übersetzungen der Oberfläche.
// Links steht der deutsche Originaltext (genau wie in der Oberfläche), rechts die Übersetzung.
// Fehlt ein Eintrag, erscheint automatisch der deutsche Text.
(window.SC = window.SC || {}).sprachen = window.SC.sprachen || {};
window.SC.sprachen.sv = {
  // Beschriftungen, Knöpfe, Meldungen
  texte: {
    " oder die Stellvertretung.": " eller ersättarna.",
    "15 Personen": "15 personer",
    "2 000 Artikel": "2 000 artiklar",
    "3 Personen": "3 personer",
    "300 Artikel": "300 artiklar",
    "4 von 128": "4 av 128",
    "Abgelehnt": "Avvisad",
    "Adresse fehlt": "Adress saknas",
    "Adresse prüfen": "Kontrollera adressen",
    "Alle": "Alla",
    "Alle Arten": "Alla typer",
    "Alle Felder sind änderbar.": "Alla fält går att ändra.",
    "Alle Lagerorte": "Alla lagerplatser",
    "Alle Lieferanten": "Alla leverantörer",
    "Alle Personen": "Alla personer",
    "Alle Produkte": "Alla artiklar",
    "Alle Zeilen übernommen": "Alla rader övertagna",
    "Alle anderen Sitzungen wurden abgemeldet.": "Alla andra sessioner loggades ut.",
    "Alle auswählen": "Välj alla",
    "Als bestellt markieren": "Markera som beställd",
    "Anfrage läuft noch — in ein paar Sekunden erneut abrufen.": "Förfrågan pågår — hämta igen om några sekunder.",
    "Angelegt, aber nicht verschickt": "Skapad, men inte skickad",
    "Angemeldet als Marie Kohl": "Inloggad som Marie Kohl",
    "Anhalten": "Stoppa",
    "Anmeldung fehlgeschlagen": "Inloggningen misslyckades",
    "Ansehen": "Visa",
    "Antwort am nächsten Werktag": "Svar nästa arbetsdag",
    "Antwort von Brevo": "Svar från Brevo",
    "Antworten abrufen": "Hämta svar",
    "Anzahl": "Antal",
    "Artikel auswählen": "Välj artiklar",
    "Artikel in der Auswahl": "artiklar i urvalet",
    "Artikel unbegrenzt": "Obegränsat antal artiklar",
    "Artikel vermerkt": "artiklar noterade",
    "Artikel zusammengefasst": "artiklar sammanslagna",
    "Artikel-ID auf dem Etikett": "Artikel-ID på etiketten",
    "Auf Etikett drucken": "Skriv ut på etikett",
    "Aufgefüllt": "Påfylld",
    "Ausblenden": "Dölj",
    "Auswahl": "Urval",
    "Auswahl leeren": "Töm urvalet",
    "Auswahl zurücksetzen": "Återställ urvalet",
    "Bedarfsliste erstellt": "Behovslista skapad",
    "Bedarfsliste exportiert": "Behovslista exporterad",
    "Bedarfslisten für Events": "Behovslistor för evenemang",
    "Beim Lieferanten öffnen": "Öppna hos leverantören",
    "Beliebig kombinierbar. Leer heißt: alles.": "Kombinera fritt. Tomt betyder allt.",
    "Benachrichtigungen und Bestandsverlauf laufen wieder.": "Aviseringar och lagerhistorik fungerar igen.",
    "Benötigt": "Behövs",
    "Bestand danach": "Lager efteråt",
    "Bestand im Zeitverlauf": "Lager över tid",
    "Bestand ok": "Lager ok",
    "Bestand umgerechnet": "Lagret omräknat",
    "Bestandsverlauf dieses Produkts ansehen": "Visa artikelns lagerhistorik",
    "Bestandsverlauf exportiert": "Lagerhistorik exporterad",
    "Bestandsverlauf mit Grafik": "Lagerhistorik med diagram",
    "Bestellliste exportiert": "Beställningslista exporterad",
    "Bestellung zurücknehmen": "Ångra beställningen",
    "Betreff": "Ämne",
    "Bild gespeichert": "Bilden sparad",
    "Bild hochladen": "Ladda upp bild",
    "Bild wird noch geladen …": "Bilden laddas fortfarande …",
    "Bilder und Datenblätter je Artikel": "Bilder och datablad per artikel",
    "Bitte eine vollständige E-Mail-Adresse eintragen.": "Ange en fullständig e-postadress.",
    "Bot-Prüfung bei Anmeldung und Registrierung": "Botkontroll vid inloggning och registrering",
    "Brauchen wir besondere Geräte?": "Behöver vi särskild utrustning?",
    "Brevo hat die Mail angenommen.": "Brevo tog emot meddelandet.",
    "Buchung sperren, wenn gesetzt": "Spärra bokning när satt",
    "CC: ": "Kopia: ",
    "Das Passwort erfüllt die Vorgaben von Supabase nicht.": "Lösenordet uppfyller inte Supabases krav.",
    "Datei nicht lesbar": "Filen går inte att läsa",
    "Datenbank in einer EU-Region": "Databas i en EU-region",
    "Datenquelle": "Datakälla",
    "Datum": "Datum",
    "Deaktiviert": "Inaktiverad",
    "Demo": "Demo",
    "Demo-Modus": "Demoläge",
    "Demo: lokal ablegen": "Demo: spara lokalt",
    "Der Link gilt 15 Minuten.": "Länken gäller i 15 minuter.",
    "Derzeit kostenlos": "Gratis just nu",
    "Deutsch": "Tyska",
    "Die Anzahl muss eine ganze Zahl ab 2 sein.": "Antalet måste vara ett heltal från 2 och uppåt.",
    "Die Datei ist leer.": "Filen är tom.",
    "Die ersten fünf Schritte": "De första fem stegen",
    "Dienstag": "Tisdag",
    "Diese Datei kann der Browser nicht lesen": "Webbläsaren kan inte läsa den här filen",
    "Diese Einheit gibt es schon.": "Den enheten finns redan.",
    "Dieses Gerät erlaubt das Licht nicht über den Browser.": "Enheten tillåter inte lampan via webbläsaren.",
    "Donnerstag": "Torsdag",
    "Drei Handgriffe, kein Papier.": "Tre handgrepp, inget papper.",
    "Eigene Daten jederzeit als CSV heraus": "Egna data ut som CSV när som helst",
    "Eigene Merkmale": "Egna egenskaper",
    "Eigene Merkmale mit Regeln": "Egna egenskaper med regler",
    "Ein Lager, eine Stunde Einrichtung.": "Ett lager, en timmes installation.",
    "Eine Firma sieht nur ihre eigenen Zeilen.": "Ett företag ser bara sina egna rader.",
    "Eine Spalte pro Feld, inklusive eigener Merkmale.": "En kolumn per fält, egna egenskaper inkluderade.",
    "Eingefügte Liste": "Inklistrad lista",
    "Einheit": "Enhet",
    "Einheit anlegen": "Skapa enhet",
    "Einheiten dieses Produkts": "Artikelns enheter",
    "Einladung gesendet": "Inbjudan skickad",
    "Einrichtung": "Installation",
    "Einträge": "poster",
    "Einzelnes Produkt": "Enskild artikel",
    "Endlosrolle · 62 mm breit": "Löpande rulle · 62 mm bred",
    "English": "Engelska",
    "Entnahme": "Uttag",
    "Entnommen": "Uttaget",
    "Entsperren": "Lås upp",
    "Erkannt und zugeordnet.": "Identifierad och kopplad.",
    "Erledigen": "Gör det",
    "Erst Artikel und Mengen hinzufügen.": "Lägg till artiklar och antal först.",
    "Erst arbeiten, dann zahlen.": "Arbeta först, betala sedan.",
    "Erst eine CSV-Datei wählen.": "Välj en CSV-fil först.",
    "Es wurde keine Kamera gefunden.": "Ingen kamera hittades.",
    "Etiketten 62 mm": "Etiketter 62 mm",
    "Etiketten drucken": "Skriv ut etiketter",
    "Etiketten in allen Formaten": "Etiketter i alla format",
    "Etikettformat": "Etikettformat",
    "Event": "Evenemang",
    "Event anlegen und Bedarfsliste erstellen": "Skapa evenemang och behovslista",
    "Events": "Evenemang",
    "Excel- und CSV-Import": "Excel- och CSV-import",
    "Excel-Import": "Excel-import",
    "Excel-Import, Events, Bestandsverlauf": "Excel-import, evenemang, lagerhistorik",
    "Fehler": "Fel",
    "Fehlmengen berechnet": "Bristtal beräknade",
    "Fehlt": "Saknas",
    "Feinrechte pro Person": "Detaljerade rättigheter per person",
    "Feld steht ab jetzt in jedem Produkt.": "Fältet finns nu på varje artikel.",
    "Firma, Personen, Produkte und Verlauf entfernt": "Företag, personer, artiklar och historik borttagna",
    "Fragen": "Frågor",
    "Freitag": "Fredag",
    "Funktionen": "Funktioner",
    "Für das Lager gedacht, nicht für die Buchhaltung.": "Gjort för lagret, inte för bokföringen.",
    "Für ein Lager und ein kleines Team": "För ett lager och ett litet team",
    "Für gewachsene Lagerstrukturen": "För vuxna lagerstrukturer",
    "Gelesen, aber kein Produkt mit dieser Kennung.": "Läst, men ingen artikel med den beteckningen.",
    "Gelöscht": "Borttagen",
    "Geplante Events": "Planerade evenemang",
    "Gesamter Zeitraum": "Hela perioden",
    "Gescannt": "Skannad",
    "Grund: ": "Orsak: ",
    "Gültig ab": "Gäller från",
    "Hilfe": "Hjälp",
    "Hinzufügen": "Lägg till",
    "Im Demo-Modus wird nichts verschickt.": "I demoläge skickas ingenting.",
    "In Bestellliste aufnehmen": "Ta med i beställningslistan",
    "In config.js ist SUPABASE_ANON_KEY leer.": "SUPABASE_ANON_KEY är tom i config.js.",
    "In config.js ist SUPABASE_URL leer.": "SUPABASE_URL är tom i config.js.",
    "Inhabende Person": "Ägare",
    "Ist bestellt": "Är beställd",
    "Ja / Nein": "Ja / Nej",
    "Jede Buchung bleibt mit Person und Zeit nachvollziehbar": "Varje bokning går att spåra med person och tid",
    "Kamera aus": "Kameran av",
    "Kamera läuft": "Kameran igång",
    "Kamera nicht verfügbar": "Kameran är inte tillgänglig",
    "Kamera starten": "Starta kameran",
    "Kamera starten, dann den Code am Regal erfassen": "Starta kameran och fånga koden på hyllan",
    "Kamera starten, dann einen Code vor die Linse halten.": "Starta kameran och håll en kod framför linsen.",
    "Kein Konto zu dieser Adresse": "Inget konto för den adressen",
    "Kein Tracking, keine Werbe-Cookies": "Ingen spårning, inga reklamkakor",
    "Keine Bewegungen für diese Auswahl.": "Inga rörelser för det här urvalet.",
    "Keine Verbindung zu Supabase.": "Ingen anslutning till Supabase.",
    "Keine Zeile erkannt": "Ingen rad identifierad",
    "Konto aktiv": "Kontot aktivt",
    "Kopfzeile und mindestens eine Produktzeile einfügen.": "Klistra in en rubrikrad och minst en artikelrad.",
    "Kurz gesagt": "Kort sagt",
    "Können wir unsere bestehende Liste übernehmen?": "Kan vi ta med vår befintliga lista?",
    "Laden fehlgeschlagen": "Inläsningen misslyckades",
    "Lagerleitung": "Lageransvarig",
    "Lagerort anlegen": "Skapa lagerplats",
    "Lagerorte": "Lagerplatser",
    "Lesezugriff": "Läsbehörighet",
    "Letzte 12 Monate": "Senaste 12 månaderna",
    "Letzte 3 Monate": "Senaste 3 månaderna",
    "Letzte 30 Tage": "Senaste 30 dagarna",
    "Licht": "Lampa",
    "Licht an": "Lampa på",
    "Licht aus": "Lampa av",
    "Link senden": "Skicka länk",
    "Link verfallen": "Länken har gått ut",
    "Löst aus": "Utlöser",
    "Mail an ": "Mejl till ",
    "Mail ist unterwegs": "Mejlet är på väg",
    "Mailversand": "Mejlutskick",
    "Mailversand prüfen": "Kontrollera mejlutskick",
    "Mehrere Lager, mehrere Schichten": "Flera lager, flera skift",
    "Meistbewegte Artikel": "Mest rörliga artiklar",
    "Menge buchen": "Boka antal",
    "Menge oben eintragen oder hier nach Einheiten aufteilen.": "Ange antalet ovan, eller dela upp det i enheter här.",
    "Merkmal": "Egenskap",
    "Merkmal anlegen": "Skapa egenskap",
    "Min.": "Min.",
    "Mindestbestand und Mail": "Miniminivå och mejl",
    "Mit verbundenem R2 landet die Datei im Bucket der Firma.": "Med R2 ansluten hamnar filen i företagets bucket.",
    "Mitarbeitende Person": "Medarbetare",
    "Mittwoch": "Onsdag",
    "Montag": "Måndag",
    "Nachbestellen": "Beställ på nytt",
    "Nachfüllung": "Påfyllning",
    "Name des Events": "Evenemangets namn",
    "Name des Merkmals": "Egenskapens namn",
    "Name fehlt": "Namn saknas",
    "Name ist frei.": "Namnet är ledigt.",
    "Neuer Bestand: ": "Nytt lager: ",
    "Neuer Lagerort": "Ny lagerplats",
    "Neuer Preis": "Nytt pris",
    "Neues Event": "Nytt evenemang",
    "Neues Event planen": "Planera ett nytt evenemang",
    "Nicht gespeichert": "Sparades inte",
    "Nicht möglich": "Inte möjligt",
    "Nichts gefunden": "Inget hittades",
    "Nichts zu importieren": "Inget att importera",
    "Noch keine Artikel": "Inga artiklar än",
    "Noch nicht übernommen.": "Inte tillämpat än.",
    "Nur verantwortliche Person": "Endast ansvarig person",
    "Oder Code eingeben": "Eller skriv koden",
    "Ohne Datenbank wird nichts verschickt.": "Utan databas skickas ingenting.",
    "Ohne Namen kann nicht gespeichert werden.": "Inget sparas utan namn.",
    "Ohne Namen wird nicht gespeichert.": "Inget sparas utan namn.",
    "Ohne Namen wird nicht übernommen.": "Inget tillämpas utan namn.",
    "Passwort geändert": "Lösenordet ändrat",
    "Passwort vergessen?": "Glömt lösenordet?",
    "Passwort wiederholen": "Upprepa lösenordet",
    "Passwort zurücksetzen": "Återställ lösenordet",
    "Passwort-Mail gesendet": "Lösenordsmejl skickat",
    "Person entfernt": "Personen borttagen",
    "Personen unbegrenzt": "Obegränsat antal personer",
    "Pflichtfeld — ohne Namen wird nicht gespeichert.": "Obligatoriskt — inget sparas utan namn.",
    "Positionen": "Poster",
    "Preis eintragen": "Ange pris",
    "Preis heute": "Pris i dag",
    "Preisverlauf und Umsatz": "Prishistorik och omsättning",
    "Preisänderungen": "Prisändringar",
    "Produkt ausgewählt": "artikel vald",
    "Produkt deaktivieren": "Inaktivera artikeln",
    "Produkt wieder aktivieren": "Aktivera artikeln igen",
    "Produktart": "Artikeltyp",
    "Produkte ausgewählt": "artiklar valda",
    "Produkte exportiert": "Artiklar exporterade",
    "Produkte importiert": "artiklar importerade",
    "Produktname auf dem Etikett": "Artikelnamn på etiketten",
    "Profil": "Profil",
    "Profil und Feinrechte": "Profil och detaljrättigheter",
    "Profildaten und Rechte darf nur die inhabende Person ändern.": "Bara ägaren får ändra profiluppgifter och rättigheter.",
    "QR-Etiketten in fünf Formaten": "QR-etiketter i fem format",
    "R2 · privat, signierter Zugriff": "R2 · privat, signerad åtkomst",
    "Rechte unten ankreuzen": "Kryssa i rättigheterna nedan",
    "Regel aktiv: ": "Regel aktiv: ",
    "Registrierung": "Registrering",
    "Registrierung fehlgeschlagen": "Registreringen misslyckades",
    "Rollen und Rechte": "Roller och rättigheter",
    "Rollen und Rechte pro Person": "Roller och rättigheter per person",
    "Sammelmail: ": "Samlingsmejl: ",
    "Scan, Mindestbestand, Bestellliste": "Skanning, miniminivå, beställningslista",
    "Scan-Entnahme": "Uttag via skanning",
    "Schlüssel abgelehnt — brevo_api_key in sc_config prüfen.": "Nyckeln avvisades — kontrollera brevo_api_key i sc_config.",
    "Schon vorhanden": "Finns redan",
    "Sehen andere Firmen unsere Daten?": "Kan andra företag se våra data?",
    "So läuft es": "Så fungerar det",
    "Spalten erkannt": "kolumner identifierade",
    "Sperren": "Spärra",
    "Stammdaten": "Grunddata",
    "Stand gespeichert.": "Sparat som det står.",
    "Status setzen darf nur ": "Statusen får bara sättas av ",
    "Status zurückgesetzt": "Statusen återställd",
    "Status: ist bestellt": "Status: beställd",
    "Stellvertretung 1": "Ersättare 1",
    "Stellvertretung 2": "Ersättare 2",
    "Stellvertretung 3": "Ersättare 3",
    "Stück": "styck",
    "Suchen": "Sök",
    "Summe im Zeitraum": "Summa i perioden",
    "Svenska": "Svenska",
    "Systemdienste": "Systemtjänster",
    "Testmail abgeschickt": "Testmejl skickat",
    "Testmail an": "Testmejl till",
    "Testmail senden": "Skicka testmejl",
    "Testzugang": "Testinloggning",
    "Treffer": "träffar",
    "Umsatz als CSV": "Omsättning som CSV",
    "Unter der Kopfzeile fehlt noch eine Produktzeile.": "Det saknas fortfarande en artikelrad under rubriken.",
    "Upload fehlgeschlagen": "Uppladdningen misslyckades",
    "Verantwortliche + Stellvertretung im CC": "Ansvarig + ersättare som kopia",
    "Verantwortliche und Stellvertretung": "Ansvarig och ersättare",
    "Verantwortung": "Ansvar",
    "Verantwortung je Artikel": "Ansvar per artikel",
    "Verhältnis": "Förhållande",
    "Vorbereitet": "Förberett",
    "Vorgang": "Åtgärd",
    "Vorgemerkt": "Noterat",
    "Warnmail bei Entnahme": "Varningsmejl vid uttag",
    "Was kostet es wirklich?": "Vad kostar det egentligen?",
    "Was meistens gefragt wird.": "Det som oftast frågas.",
    "Wechseln": "Byt",
    "Wer bekommt die Mail?": "Vem får mejlet?",
    "Wer bekommt die Warnmails?": "Vem får varningsmejlen?",
    "Wie MHD überwachen": "Hur bäst före-datum bevakas",
    "Wie kommen wir wieder heraus?": "Hur tar vi oss ut igen?",
    "Wie mache ich …?": "Hur gör jag …?",
    "Wieder aktiv": "Aktiv igen",
    "Wiederholung stimmt überein": "Upprepningen stämmer",
    "Wird hochgeladen": "Laddas upp",
    "Zeilen gelesen": "rader lästa",
    "Zeilen ohne Namen verworfen": "rader utan namn borttagna",
    "Zeilen übersprungen (Name fehlt oder doppelt)": "rader hoppades över (namn saknas eller dubblett)",
    "Zeitraum": "Period",
    "Zu ": "För ",
    "Zugang aktivieren": "Aktivera åtkomst",
    "Zugang sofort gesperrt, Buchungen bleiben im Verlauf": "Åtkomsten spärras genast, bokningar blir kvar i historiken",
    "Zugang sperren": "Spärra åtkomst",
    "ausgewählt": "valda",
    "bestellt": "beställd",
    "davon nachzubestellen": "varav att beställa",
    "deaktiviert": "inaktiverad",
    "derzeit gratis": "gratis just nu",
    "erkannt": "identifierad",
    "erster Preis": "första priset",
    "für immer": "för alltid",
    "gebucht": "bokat",
    "gerade eben": "nyss",
    "größer als ": "större än ",
    "gültig 3 Stunden": "gäller i 3 timmar",
    "gültig ab ": "gäller från ",
    "ja": "ja",
    "ja — erscheint in allen Listen": "ja — syns i alla listor",
    "je Monat, geplant": "per månad, planerat",
    "keine Regel": "ingen regel",
    "kleiner als ": "mindre än ",
    "kleinste Einheit": "minsta enhet",
    "nachbestellen": "beställ på nytt",
    "nein — aus Listen ausgeblendet": "nej — dold i listor",
    "neue Einheit": "ny enhet",
    "neue Lagerorte": "nya lagerplatser",
    "niedrig": "låg",
    "ohne CC an Stellvertretung": "utan kopia till ersättare",
    "sichtbaren Artikeln": "synliga artiklar",
    "unten bestätigen": "bekräfta nedan",
    "unter Mindestbestand ": "under miniminivån ",
    "unterwegs": "på väg",
    "verbergen": "dölj",
    "verbleibende Zeit": "återstående tid",
    "vorhanden": "finns",
    "wird die neue kleinste Einheit": "blir den nya minsta enheten",
    "zeigen": "visa",
    "Änderungen übernehmen": "Tillämpa ändringar",
    "Übernommen": "Tillämpat",
    "— bitte wählen —": "— välj —",
    "— keine —": "— ingen —",
    "Lager": "Lager",
    "Verwaltung": "Administration",
    " gibt es keinen Zugang. Bitte Adresse prüfen oder Firma neu registrieren.": " finns ingen åtkomst. Kontrollera adressen eller registrera företaget på nytt.",
    "Absender nicht verifiziert — in Brevo unter Senders freischalten.": "Avsändaren är inte verifierad — godkänn den i Brevo under Senders.",
    "Alles, was ein Betriebslager braucht — und nichts, was danach noch erklärt werden muss.": "Allt ett företagslager behöver — och inget som måste förklaras efteråt.",
    "Beispieldaten, nichts wird gespeichert. Systemdienste und Kostenbremse sind sichtbar.": "Exempeldata, inget sparas. Systemtjänster och kostnadsbromsen syns.",
    "Bestehende Listen mit Vorlage übernehmen. Artikelnummer, Mindestbestand, Ort und Lieferant kommen mit.": "Ta med befintliga listor via mallen. Artikelnummer, miniminivå, plats och leverantör följer med.",
    "Bilder geprüft — noch kein Code erkannt. Näher heran, mehr Licht, Code gerade halten.": "bildrutor kontrollerade — ingen kod än. Kom närmare, mer ljus, håll koden rakt.",
    "Danach läuft das Lager von selbst. Jeder Schritt hakt sich ab, sobald er erledigt ist.": "Sedan sköter lagret sig självt. Varje steg bockas av när det är klart.",
    "Das Anlegen in der Datenbank schlägt fehl. schema.sql im SQL-Editor erneut ausführen.": "Det går inte att skapa posten i databasen. Kör schema.sql igen i SQL-editorn.",
    "Den Bestellstatus dürfen nur die verantwortliche Person und ihre Stellvertretungen setzen.": "Bara ansvarig person och ersättarna får sätta beställningsstatusen.",
    "Den Namen gibt es schon — mit anderem Lagerort oder anderer Quantität ist das in Ordnung.": "Namnet finns redan — det går bra med en annan lagerplats eller kvantitet.",
    "Der Zugriff wurde abgelehnt. In der Adresszeile auf das Schloss tippen, die Kamera erlauben und erneut starten.": "Åtkomsten nekades. Tryck på hänglåset i adressfältet, tillåt kameran och starta om.",
    "Die Antwort von Brevo steht in ein paar Sekunden in der Tabelle.": "Brevos svar står i tabellen om några sekunder.",
    "Die Erkennung konnte nicht geladen werden. Bitte den Code unten eintippen.": "Läsaren kunde inte laddas. Skriv koden nedan.",
    "Die Kamera ist von einem anderen Programm belegt. Andere Apps schließen und erneut versuchen.": "Ett annat program använder kameran. Stäng andra appar och försök igen.",
    "Die Tagesgrenze für Mails ist erreicht. Die Einladung ist gespeichert und gilt drei Stunden.": "Dagsgränsen för mejl är nådd. Inbjudan är sparad och gäller i tre timmar.",
    "Die genaue Meldung steht oben. Die Schritte zum Mailversand stehen in „Registrierung und Mail\".": "Det exakta meddelandet står ovan. Stegen för mejlutskick finns i \"Registrierung und Mail\".",
    "Diese E-Mail-Adresse ist bereits registriert. Bitte anmelden oder das Passwort zurücksetzen.": "Den här e-postadressen är redan registrerad. Logga in eller återställ lösenordet.",
    "Diese Einstellung gilt firmenweit und kann nur im höchsten Rechtelevel geändert werden.": "Inställningen gäller hela företaget och kan bara ändras på högsta behörighetsnivån.",
    "Dieser Code gehört zu einer anderen Firma. Innerhalb dieses Zugangs lässt er sich nicht öffnen.": "Koden tillhör ett annat företag. Den går inte att öppna från det här kontot.",
    "Dieses Produkt gibt es schon: gleicher Name, gleicher Lagerort, gleiche Quantität. Ändere eines davon.": "Artikeln finns redan: samma namn, samma lagerplats, samma kvantitet. Ändra något av dem.",
    "Ein QR-Code je Artikel oder Regalplatz. Scannen, Menge tippen, fertig — auch mit Handschuhen bedienbar.": "En QR-kod per artikel eller hyllplats. Skanna, skriv antalet, klart — går att använda med handskar.",
    "Eine neue Rolle startet mit den Rechten für Ansehen und Buchen. Alles Weitere hier ankreuzen.": "En ny roll börjar med rättigheter att visa och boka. Kryssa i allt annat här.",
    "Eine verantwortliche Person und bis zu drei Stellvertretungen. Die Warnmail geht an sie, in CC an die Stellvertretung.": "En ansvarig person och upp till tre ersättare. Varningsmejlet går till dem, med ersättarna som kopia.",
    "Entnahme oder Nachfüllung eintragen. Der Bestand schreibt sich fort, die Buchung bleibt mit Person und Zeit im Verlauf.": "Ange uttag eller påfyllning. Lagret uppdateras, bokningen ligger kvar i historiken med person och tid.",
    "Firma anlegen, Artikel importieren, Etiketten drucken. Danach scannt das Team.": "Skapa företaget, importera artiklarna, skriv ut etiketterna. Sedan skannar teamet.",
    "In Excel über „Speichern unter\" als CSV ablegen (Trennzeichen Semikolon) und die CSV-Datei wählen.": "Använd Spara som i Excel för att skapa en CSV (semikolon) och välj den filen.",
    "In der Kopfzeile fehlt eine Spalte „Name\" (oder „Artikelname\"). Ohne sie ist nicht erkennbar, was ein Produkt ist.": "Rubrikraden saknar en kolumn \"Name\" (eller \"Artikelname\"). Utan den går det inte att se vad som är en artikel.",
    "Inhabende Person, Lagerleitung, Mitarbeitende, Leser — und einzelne Rechte pro Person, wenn eine Rolle nicht passt.": "Ägare, lageransvarig, medarbetare, läsare — plus enskilda rättigheter per person när en roll inte passar.",
    "Kein Artikel mit dieser Kennung. Etikett neu drucken oder Code eintippen.": "Ingen artikel med den beteckningen. Skriv ut en ny etikett eller skriv koden.",
    "Kein Eintrag passt zu diesem Stichwort. Versuche ein einzelnes Wort — etwa „Mail\", „Etikett\" oder „Import\".": "Ingen post matchar sökordet. Prova ett enda ord — \"Mail\", \"Etikett\" eller \"Import\".",
    "Keine Karte nötig · Einrichtung in einer Stunde · jederzeit kündbar": "Inget kort behövs · klart på en timme · säg upp när som helst",
    "Keine Mails, kein Tracking. Sichtbar nur für Verantwortliche und Stellvertretung.": "Inga mejl, ingen spårning. Syns bara för ansvarig person och ersättarna.",
    "Kurze Antworten zu allem, was im Lager täglich vorkommt. Tippe ein Stichwort ein, um zu filtern.": "Korta svar på allt som händer i lagret varje dag. Skriv ett sökord för att filtrera.",
    "Lagerverwaltung für Betriebe. Betrieben von der Internet GmbH.": "Lagerhantering för företag. Drivs av Internet GmbH.",
    "Name, Lagerort und Quantität stimmen mit einem bestehenden Produkt überein.": "Namn, lagerplats och kvantitet stämmer med en befintlig artikel.",
    "Nichts ausgewählt — gerechnet wird über alle aktiven Produkte.": "Inget valt — siffrorna gäller alla aktiva artiklar.",
    "Nur Personen aus dieser Firma — an ihre hinterlegten Adressen gehen die Bestandsmails.": "Bara personer från det här företaget — lagermejlen går till deras sparade adresser.",
    "Nur die Kopfzeile mit allen Feldern. Zeile für Zeile ausfüllen, eine Zeile ist ein Produkt.": "Bara rubriken med alla fält. Fyll i rad för rad — en rad är en artikel.",
    "Produkt, Bestand und alle Buchungen werden entfernt. Das lässt sich nicht zurückholen.": "Artikel, lager och alla bokningar tas bort. Det går inte att ångra.",
    "QR-Code am Regal mit dem Handy scannen. Kein Gerät kaufen, keine App installieren — die Kamera genügt.": "Skanna hyllans QR-kod med mobilen. Ingen utrustning att köpa, ingen app att installera — kameran räcker.",
    "QR-Etiketten in fünf Formaten, von 2×4 bis 5×13 je Blatt, dazu die Endlosrolle mit 62 mm.": "QR-etiketter i fem format, från 2×4 till 5×13 per ark, plus löprullen på 62 mm.",
    "Registrierung ist abgeschaltet: Authentication → Providers → Email → Enable Sign-ups einschalten.": "Registrering är avstängd: slå på Authentication → Providers → Email → Enable Sign-ups.",
    "Rolle: Mitarbeitende Person. Rechte setzt die inhabende Person.": "Roll: medarbetare. Ägaren sätter rättigheterna.",
    "Sofort, täglich, wöchentlich oder monatlich. Sammelmails fassen alles zu einer Bestellliste zusammen.": "Direkt, dagligen, veckovis eller månadsvis. Samlingsmejl samlar allt i en beställningslista.",
    "Supabase konnte die Mail nicht übergeben. SMTP-Zugang prüfen: Project Settings → Authentication → SMTP Settings.": "Supabase kunde inte lämna över mejlet. Kontrollera SMTP: Project Settings → Authentication → SMTP Settings.",
    "Unter dem Mindestbestand geht die Warnung raus — sofort oder gesammelt als Bestellliste, je nach Einstellung.": "Under miniminivån går varningen ut — direkt eller samlad i en beställningslista, beroende på inställning.",
    "Wer etwas herausnimmt, scannt. Alles andere passiert von selbst.": "Den som tar ut något skannar. Allt annat sker av sig självt.",
    "Zu dieser Adresse gibt es schon ein Konto. Anmelden oder Passwort zurücksetzen.": "Det finns redan ett konto för adressen. Logga in eller återställ lösenordet.",
    "Zu viele Fehlversuche. Das Konto ist 15 Minuten gesperrt, eine Warnmail ist raus.": "För många misslyckade försök. Kontot är låst i 15 minuter och ett varningsmejl har skickats.",
    "Alle Tarife sind derzeit kostenlos. Bevor sich daran etwas ändert, melden wir uns — ohne Zustimmung wird nichts abgebucht.": "Alla planer är gratis just nu. Innan det ändras hör vi av oss — inget dras utan samtycke.",
    "Artikel und Mengen eintragen — auch deaktivierte. Beim Anlegen entsteht automatisch die Bedarfs- und Bestellliste mit den Fehlmengen.": "Ange artiklar och antal — även inaktiverade. När du sparar skapas behovs- och beställningslistan med bristerna.",
    "Demo-Daten: Im verbundenen Betrieb stehen hier die echten Firmen. Zugang erhält nur, wer in der Liste platform_admins eingetragen ist.": "Exempeldata: i skarp drift står de riktiga företagen här. Bara den som står i platform_admins får åtkomst.",
    "Der Mailversand ist noch nicht eingerichtet. In Supabase im SQL-Editor die Datei supabase/mail.sql ausführen und dort im Block sc_config den Brevo-Schlüssel eintragen. Die Einladung ist gespeichert und gilt drei Stunden — der Link lässt sich auch von Hand weitergeben.": "Mejlutskicket är inte klart än. Kör supabase/mail.sql i Supabases SQL-editor och ange Brevo-nyckeln i sc_config-blocket. Inbjudan är sparad och gäller i tre timmar — länken går också att skicka för hand.",
    "Derzeit nichts. Die Tarife stehen oben, damit klar ist, was später wofür gilt. Wird abgerechnet, fragen wir vorher — ohne Zustimmung passiert nichts.": "Ingenting just nu. Planerna står ovan så att det är tydligt vad som gäller senare. Om fakturering börjar frågar vi först — inget sker utan samtycke.",
    "Die Anmeldung verlangt Passwort und Bot-Prüfung. Der zweite Faktor über eine Authenticator-App ist im Programm angelegt, aber noch abgeschaltet — er lässt sich später zuschalten, ohne dass Konten neu eingerichtet werden müssen.": "Inloggning kräver lösenord och botkontroll. Andra faktorn via en autentiseringsapp finns inbyggd men är avstängd — den kan slås på senare utan att konton måste läggas upp igen.",
    "Die Auswahl, die beim Anlegen eines Produkts und in allen Filtern erscheint. Ein Lagerort lässt sich nur löschen, wenn kein Produkt mehr darin liegt.": "De val som erbjuds när en artikel skapas och i alla filter. En lagerplats går bara att ta bort när ingen artikel ligger där.",
    "Die Kamera funktioniert nur über eine verschlüsselte Verbindung. Beim ersten Mal fragt der Browser um Erlaubnis — ohne Zustimmung bleibt das Bild schwarz.": "Kameran fungerar bara över en krypterad anslutning. Första gången frågar webbläsaren om lov — utan samtycke förblir bilden svart.",
    "Die Trennung steckt nicht in der Oberfläche, sondern in der Datenbank: jede Zeile trägt eine Firmenkennung, und die Regel dazu lässt nur die eigene durch. Auch ein Zugriff an der Oberfläche vorbei bringt nichts.": "Åtskillnaden ligger inte i gränssnittet utan i databasen: varje rad bär en företagsbeteckning och regeln släpper bara igenom den egna. Att gå förbi gränssnittet ger ingenting.",
    "Die kleinste Einheit hat den Faktor 1. Eine Kiste mit zwölf Flaschen bekommt den Faktor 12, eine Palette mit 32 Kisten den Faktor 384. Gebucht wird immer in der kleinsten Einheit.": "Minsta enheten har faktor 1. En back med tolv flaskor får faktor 12, en pall med 32 backar får 384. Bokning sker alltid i minsta enheten.",
    "Die verantwortliche Person des Artikels, in CC die Stellvertretung. Auf Wunsch statt Einzelmails eine gesammelte Bestellliste zu einer festen Uhrzeit.": "Artikelns ansvariga person, med ersättarna som kopia. På begäran en samlad beställningslista vid en fast tid i stället för enstaka mejl.",
    "Dieser Browser gibt keinen Zugriff auf die Kamera. Das ist meist der Fall, wenn die Seite nicht über https:// geladen wurde. Bitte den Code unten eintippen.": "Webbläsaren ger ingen kameraåtkomst. Oftast beror det på att sidan inte laddades via https://. Skriv koden nedan.",
    "Dieses Produkt ist deaktiviert: keine Buchungen, keine Mails, kein Bestandsverlauf. Es taucht nur noch bei Verantwortlichen und Stellvertretungen auf.": "Artikeln är inaktiverad: inga bokningar, inga mejl, ingen lagerhistorik. Den syns bara för ansvariga och ersättare.",
    "Eine Rolle ist eine Vorlage: Wer sie bekommt, startet mit genau diesen Rechten. Einzelne Personen lassen sich danach weiter oben abweichend einstellen. Die inhabende Person darf immer alles und ist deshalb nicht änderbar.": "En roll är en mall: den som får den börjar med exakt dessa rättigheter. Enskilda personer kan sedan ställas in avvikande ovan. Ägaren får alltid göra allt och går därför inte att ändra.",
    "Enthält den heutigen Stand. Zum Ändern eines Bestands die Zahl überschreiben und die Datei wieder hochladen — bestehende Produkte werden dabei übersprungen, nur neue Zeilen kommen hinzu.": "Innehåller dagens siffror. För att ändra ett lagersaldo skriver du över talet och laddar upp filen igen — befintliga artiklar hoppas över, bara nya rader läggs till.",
    "Entnahme am Regal scannen, Bestand ist sofort aktuell. Unterschreitet ein Artikel den Mindestbestand, geht die Mail an die verantwortliche Person — nicht an alle.": "Skanna uttaget vid hyllan så är lagret aktuellt direkt. Om en artikel går under miniminivån går mejlet till ansvarig person — inte till alla.",
    "In Supabase ist der Captcha-Schutz aktiv. Dann braucht config.js den TURNSTILE_SITE_KEY, und in Supabase muss der passende Secret Key stehen.": "Captcha-skyddet är aktivt i Supabase. Då behöver config.js TURNSTILE_SITE_KEY och Supabase behöver motsvarande secret key.",
    "Ja. Die Importvorlage herunterladen, eigene Daten hineinkopieren, hochladen. Artikelnummer, Mindestbestand, Ort und Lieferant kommen mit.": "Ja. Ladda ner importmallen, kopiera in egna data, ladda upp. Artikelnummer, miniminivå, plats och leverantör följer med.",
    "Jede Preisänderung gilt ab ihrem Datum. Der Umsatz nimmt für jede Entnahme den Preis, der an diesem Tag gültig war — über ein Produkt oder über mehrere zusammen.": "Varje prisändring gäller från sitt datum. Omsättningen tar, för varje uttag, det pris som gällde den dagen — för en artikel eller flera tillsammans.",
    "Kündigung jederzeit. Produktliste, Bestandsverlauf und Bestellliste lassen sich als CSV herunterladen, danach wird die Firma samt Daten gelöscht.": "Säg upp när som helst. Artikellista, lagerhistorik och beställningslista kan laddas ner som CSV, därefter raderas företaget och dess data.",
    "Liegt config.js neben der Seite, und stehen dort SUPABASE_URL und SUPABASE_ANON_KEY? Nach dem Hochladen die Seite mit Strg+Umschalt+R (Mac: Cmd+Umschalt+R) neu laden.": "Ligger config.js bredvid sidan, och står SUPABASE_URL och SUPABASE_ANON_KEY där? Ladda om med Ctrl+Skift+R (Mac: Cmd+Skift+R) efter uppladdning.",
    "Mailgrenze erreicht. Ohne eigenen SMTP-Zugang erlaubt Supabase nur wenige Mails pro Stunde — SMTP-Daten von Brevo eintragen.": "Mejlgränsen är nådd. Utan egen SMTP tillåter Supabase bara några mejl i timmen — ange Brevos SMTP-uppgifter.",
    "Nein. Jede Zeile trägt eine Firmenkennung, und die Datenbank gibt nur Zeilen der eigenen Firma heraus. Das gilt auch für Zugriffe an der Oberfläche vorbei.": "Nej. Varje rad bär en företagsbeteckning och databasen lämnar bara ut rader från det egna företaget. Det gäller även åtkomst förbi gränssnittet.",
    "Nein. Jedes Handy mit Kamera genügt, der QR-Code klebt am Regal. Etiketten druckst du selbst, auf normalem Papier oder mit einem Rollendrucker.": "Nej. Vilken mobil som helst med kamera räcker, QR-koden sitter på hyllan. Etiketterna skriver du ut själv, på vanligt papper eller med en rulletikettskrivare.",
    "Preise ohne Umsatzsteuer. Ein Wechsel ist jederzeit möglich, eine Kündigung ebenso — die eigenen Daten lassen sich vorher als CSV herausziehen.": "Priser exklusive moms. Byte går när som helst, liksom uppsägning — egna data kan hämtas ut som CSV i förväg.",
    "Produktbilder liegen in einer geschlossenen Ablage und werden über Adressen geladen, die nach einer Stunde verfallen. Der Mailschlüssel liegt in der Datenbank, nicht im Browser.": "Artikelbilder ligger i ett stängt förråd och laddas via adresser som går ut efter en timme. Mejlnyckeln ligger i databasen, inte i webbläsaren.",
    "Scheidet jemand aus dem Unternehmen aus, können Profildaten hier geändert, der Zugang gesperrt oder die Person entfernt werden.": "När någon slutar kan profiluppgifter ändras här, åtkomsten spärras eller personen tas bort.",
    "Wer den Verlauf behalten will, schaltet das Produkt stattdessen auf „nicht aktiv\" — es verschwindet dann aus allen Listen, bleibt aber auffindbar.": "För att behålla historiken sätter du artikeln på \"inte aktiv\" i stället — den försvinner då ur alla listor men går att hitta.",
    "Zusätzliche Felder für jedes Produkt. Wähle Name und Art — und wenn gewünscht, was das Feld in der Bestandsverwaltung auslöst.": "Extra fält för varje artikel. Välj namn och typ — och om du vill, vad fältet utlöser i lagerhanteringen.",
    "Lagerorte anlegen": "Skapa lagerplatser",
    "Einstellungen → Lagerorte: Regal, Schrank, Halle.": "Inställningar → Lagerplatser: hylla, skåp, hall.",
    "Produkte anlegen oder Tabelle importieren": "Skapa artiklar eller importera ett kalkylblad",
    "Stammdaten → Produktverwaltung: einzeln eintragen oder eine CSV hochladen.": "Grunddata → Artikelhantering: ange dem en och en eller ladda upp en CSV.",
    "QR-Etiketten drucken": "Skriv ut QR-etiketter",
    "Ein Code je Produkt, ans Regal geklebt.": "En kod per artikel, fastsatt på hyllan.",
    "Team einladen": "Bjud in någon",
    "Wer bucht, braucht einen Zugang.": "Den som bokar behöver ett konto.",
    "Einmal testen, damit Warnungen ankommen.": "Testa en gång så att varningar kommer fram.",
    "Quantitäten": "Kvantiteter",
    "Name der Quantität": "Kvantitetens namn",
    "Quantität anlegen": "Skapa kvantitet",
    "Größe": "Storlek",
    "Größen": "storlekar",
    "Import nicht gespeichert": "Importen sparades inte",
    "Buchung nicht gespeichert": "Bokningen sparades inte",
    "Zugang nicht eingerichtet": "Åtkomsten kunde inte skapas",
    "Konto angelegt": "Kontot skapat",
    "Bitte Vor- und Nachnamen eintragen.": "Ange för- och efternamn.",
    "Bitte die Adresse eintragen, an die die Einladung ging.": "Ange adressen som inbjudan skickades till.",
    "Quantität": "Enhet",
    "Quantitäten verwalten": "Hantera kvantiteter",
    "Verhältnis zu": "Förhållande till",
    "Enthält wie viele": "Innehåller hur många",
    "eigenständig": "fristående",
    "eigenständig — ohne Bezug": "fristående — utan koppling",
    "steht für sich, ohne Umrechnung.": "står för sig själv, ingen omräkning.",
    "Diese Quantität gibt es schon.": "Den kvantiteten finns redan.",
    "Zuerst einen Namen eintragen.": "Ange ett namn först.",
    "frei": "ledig",
    "Namen sind schon vergeben": "Namnen är redan tagna",
    "Alles überschreiben": "Skriv över allt",
    "Nichts überschreiben": "Skriv över inget",
    "Import ausführen": "Kör import",
    "Verantwortliche und stellvertretende Person": "Ansvarig och ersättare",
    "Person": "Person",
    "Produkt aktualisiert": "artikel uppdaterad",
    "Produkte aktualisiert": "artiklar uppdaterade",
    "neu hinzugefügt": "nytillagda",
    "keine neuen Zeilen": "inga nya rader",
    "nicht im Team: ": "inte i teamet: ",
    "weitere werden gleich behandelt.": "till behandlas på samma sätt.",
    "Captcha fehlt": "Captcha saknas",
    "In welchen Gebinden wird dieses Produkt bewegt? Angehakte Quantitäten bekommen oben ein eigenes Buchungsfeld. Angelegt und ins Verhältnis gesetzt werden sie in den Einstellungen.": "I vilka förpackningar rör sig den här artikeln? Ikryssade kvantiteter får ett eget bokningsfält ovanför. De skapas och sätts i relation i inställningarna.",
    "Es gibt noch keine Quantitäten. Unter Einstellungen → Quantitäten lassen sich Flasche, Kiste oder Palette anlegen.": "Det finns inga kvantiteter än. Flaska, back eller pall kan skapas under Inställningar → Kvantiteter.",
    "Gebinde, in denen eure Ware ankommt und rausgeht: Flasche, Kiste, Palette, Rolle, Sack. Eine Quantität kann für sich stehen oder sich auf eine andere beziehen — dann rechnet das Lager beim Buchen um.": "Förpackningarna som varorna kommer och går i: flaska, back, pall, rulle, säck. En kvantitet kan stå för sig själv eller kopplas till en annan — då räknar lagret om vid bokning.",
    "„Kiste, Verhältnis zu Flasche, 12\" ergibt 1 Kiste = 12 Flaschen. Eine Palette mit 32 Kisten wird auf die Kiste bezogen, nicht auf die Flasche — die Kette rechnet sich von selbst durch. Gebinde ohne Bezug bleiben eigenständig.": "”Back, förhållande till flaska, 12” ger 1 back = 12 flaskor. En pall med 32 backar kopplas till backen, inte till flaskan — kedjan räknas ut av sig själv. Förpackningar utan koppling förblir fristående.",
    "Bitte zuerst den Haken im Sicherheitsfeld setzen. Erscheint kein Feld, fehlt in config.js der TURNSTILE_SITE_KEY.": "Kryssa först i säkerhetsrutan. Om ingen ruta visas saknas TURNSTILE_SITE_KEY i config.js.",
    "Ein Produkt aus der Liste trägt den Namen eines vorhandenen, weicht aber ab. Wähle aus, was übernommen wird.": "En artikel i listan har samma namn som en befintlig men skiljer sig. Välj vad som ska tas över.",
    "Produkte aus der Liste tragen den Namen vorhandener Produkte, weichen aber ab. Wähle aus, was übernommen wird.": "artiklar i listan har samma namn som befintliga men skiljer sig. Välj vad som ska tas över.",
    "neue Zeilen kommen in jedem Fall hinzu.": "nya rader läggs till i vilket fall som helst.",
    "Neue Zeilen sind nicht dabei — die Liste enthält nur bekannte Namen.": "Det finns inga nya rader — listan innehåller bara kända namn.",
    "neue Zeile kommt in jedem Fall hinzu.": "ny rad läggs till i vilket fall som helst.",
    "Artikelkennung": "Artikelkod",
    "Diese Kennung steht auf dem Etikett und ändert sich nie. Sie lässt sich beim Scannen auch von Hand eintippen.": "Koden står på etiketten och ändras aldrig. Den går också att skriva in för hand vid skanning.",
    "Artikelkennung fehlt": "Artikelkod saknas",
    "Die Spalte „code“ gibt es noch nicht. Bitte schema.sql im SQL-Editor erneut ausführen — sonst sind gedruckte Etiketten nicht scannbar.": "Kolumnen ”code” finns inte än. Kör schema.sql igen i SQL-editorn — annars går utskrivna etiketter inte att skanna.",
    "Etiketten": "Etiketter",
    "Kennung vergeben": "kod tilldelad",
    "Kennungen vergeben": "koder tilldelade",
    "Neu drucken: ": "Skriv ut igen: ",
    "Gespeichert, aber ohne Kennung: die Spalte „code“ gibt es noch nicht. Bitte schema.sql im SQL-Editor ausführen — sonst sind gedruckte Etiketten nicht scannbar.": "Sparat, men utan kod: kolumnen ”code” finns inte än. Kör schema.sql i SQL-editorn — annars går utskrivna etiketter inte att skanna.",
    "Übersicht": "Översikt",
    "Produkte": "Produkter",
    "Produktverwaltung": "Artikelhantering",
    "Rollen": "Roller",
    "Rollen und ihre Standardrechte": "Roller och deras standardrättigheter",
    "Standardrechte": "Standardrättigheter",
    "Neue Rolle": "Ny roll",
    "Rolle anlegen": "Skapa roll",
    "Rechte": "Rättigheter",
    "Personen": "Personer",
    "Fremdes Etikett": "Främmande etikett",
    "Kein Zugriff": "Ingen åtkomst",
    "Bearbeiten": "Redigera",
    "Produkt löschen": "Ta bort artikel",
    "Wirklich vollständig löschen?": "Ta bort helt?",
    "Endgültig löschen": "Ta bort permanent",
    "Aktiv": "Aktiv",
    "Gelesener Code": "Läst kod",
    "Noch kein Code gelesen": "Ingen kod läst än",
    "Vorlage herunterladen": "Ladda ner mall",
    "Ausgefüllte Liste hier hochladen": "Ladda upp din ifyllda lista här",
    "Datei hierher ziehen oder klicken · .csv bis 5 MB": "Dra en fil hit eller klicka · .csv upp till 5 MB",
    "Leere Liste — nur Kopfzeile": "Tom lista — bara rubrik",
    "Mit allen vorhandenen Produkten": "Med alla befintliga artiklar",
    "Vorlage mit Bestand": "Mall med lager",
    "Leere Vorlage": "Tom mall",
    "Vorlage": "Mall",
    "Datei unten hochladen, Spalten prüfen, importieren": "Ladda upp filen nedan, kontrollera kolumnerna, importera",
    "Vorlage wählen: leer oder mit dem heutigen Bestand": "Välj mall: tom eller med dagens lager",
    "Scannen": "Skanna",
    "Produkt anlegen": "Nytt föremål",
    "QR-Codes": "QR-koder",
    "Team & Rechte": "Team & rättigheter",
    "Einstellungen": "Inställningar",
    "Betriebs-Konsole": "Operatörskonsol",
    "Angemeldet als": "Inloggad som",
    "Abmelden": "Logga ut",
    "Hell": "Ljust",
    "Dunkel": "Mörkt",
    "System": "System",
    "Artikel im Lager": "Artiklar i lager",
    "in": "i",
    "Lagerorten": "lagerplatser",
    "Unter Mindestbestand": "Under miniminivå",
    "Benachrichtigung ausgelöst": "avisering skickad",
    "Bestellt, offen": "Beställt, öppet",
    "warten auf Lieferung": "väntar på leverans",
    "Entnahmen heute": "Uttag idag",
    "Bestellliste": "Beställningslista",
    "Alles unter Mindestbestand, gesammelt für die nächste Bestellung": "Allt under miniminivå, samlat för nästa beställning",
    "Artikel": "Artiklar",
    "Ist": "Faktisk",
    "Min": "Min",
    "Bestellmenge": "Beställn.antal",
    "Lieferant": "Leverantör",
    "Status": "Status",
    "Als Excel exportieren": "Exportera till Excel",
    "Als PDF drucken": "Skriv ut som PDF",
    "Letzte Bewegungen": "Senaste rörelser",
    "Suche": "Sök",
    "Lagerort": "Lagerplats",
    "Name": "Namn",
    "Istbestand": "Faktiskt lager",
    "Mindestbestand": "Miniminivå",
    "Details": "Detaljer",
    "von": "av",
    "Artikeln": "artiklar",
    "Neues Produkt": "Ny artikel",
    "Entnehmen oder nachfüllen": "Ta ut eller fylla på",
    "Menge eingeben und buchen. Jede Buchung wird mit Person und Zeitstempel protokolliert.": "Ange antal och bokför. Varje bokning loggas med person och tidsstämpel.",
    "Entnahme buchen": "Bokför uttag",
    "Nachfüllung buchen": "Bokför påfyllning",
    "QR-Code dieses Produkts": "QR-kod för denna artikel",
    "Nur dieses Produkt. Scan öffnet direkt diese Detailansicht.": "Endast denna artikel. Skanning öppnar denna detaljvy.",
    "Etikett drucken": "Skriv ut etikett",
    "Bestandsverlauf": "Lagerhistorik",
    "Verantwortlich": "Ansvarig",
    "Stellvertretung": "Ersättare",
    "MHD": "Bäst före",
    "Preis": "Pris",
    "Letzte Entnahme": "Senaste uttag",
    "Letzte Auffüllung": "Senaste påfyllning",
    "Geändert von": "Ändrad av",
    "Produktlink": "Produktlänk",
    "Am Lagerort den QR-Code am Regal scannen. Der Code passt nur auf ein Produkt und öffnet dessen Detailansicht.": "Skanna QR-koden på hyllan. Varje kod hör till en enda artikel och öppnar dess detaljvy.",
    "QR-Code im Rahmen halten": "Håll QR-koden i ramen",
    "Demo: Code auswählen": "Demo: välj en kod",
    "Einzelnes Produkt anlegen": "Lägg till en artikel",
    "EAN": "EAN",
    "Verantwortliche Person": "Ansvarig person",
    "Kategorien": "Kategorier",
    "Link zum Produkt": "Länk till produkten",
    "Produkt speichern": "Spara artikel",
    "Abbrechen": "Avbryt",
    "Viele Produkte aus einer Tabelle importieren": "Importera många artiklar från ett kalkylblad",
    "Vorlage mit allen Feldern herunterladen": "Ladda ner mallen med alla fält",
    "Zeile für Zeile ausfüllen, eine Zeile ist ein Produkt": "Fyll i rad för rad — en rad är en artikel",
    "CSV hier hochladen, Spalten prüfen, importieren": "Ladda upp CSV-filen, kontrollera kolumnerna, importera",
    "In Excel über „Speichern unter\" als CSV ablegen (Trennzeichen Semikolon)": "Spara som CSV i Excel (semikolon som avgränsare)",
    "CSV-Vorlage herunterladen": "Ladda ner CSV-mall",
    "Datei hierher ziehen": "Dra en fil hit",
    ".csv, bis 5 MB — Excel-Dateien vorher als CSV speichern": ".csv, upp till 5 MB — spara Excel-filer som CSV först",
    "Beispieldatei prüfen": "Kontrollera exempelfil",
    "Spalte in Datei": "Kolumn i filen",
    "Feld im System": "Fält i systemet",
    "Prüfung": "Kontroll",
    "Produkte importieren": "artiklar — importera",
    "1 Produkt importieren": "Importera 1 artikel",
    "Produkt importiert": "artikel importerad",
    "Zeile übersprungen (Name fehlt oder doppelt)": "rad hoppades över (namn saknas eller dubblett)",
    "neuer Lagerort": "ny lagerplats",
    "Zeile gelesen": "rad läst",
    "wird übersprungen": "hoppas över",
    "Spalte erkannt": "kolumn identifierad",
    "Zeile ohne Namen verworfen": "rad utan namn borttagen",
    "Zeile": "rad",
    "Zeile unter der Kopfzeile": "rad under rubriken",
    "Zeilen unter der Kopfzeile": "rader under rubriken",
    "„Liste prüfen\" drücken": "tryck Kontrollera listan",
    "Text über dem Code": "Text ovanför koden",
    "Text unter dem Code": "Text under koden",
    "Etikettgröße": "Etikettstorlek",
    "Drucken / PDF": "Skriv ut / PDF",
    "Team": "Team",
    "Rolle": "Roll",
    "Feinrechte": "Detaljrättigheter",
    "Die Einladung gilt 3 Stunden. Läuft sie ab, kannst du erneut einladen.": "Inbjudan gäller i 3 timmar. Går den ut kan du bjuda in igen.",
    "E-Mail-Adresse": "E-postadress",
    "Einladung senden": "Skicka inbjudan",
    "Die Rolle setzt die Voreinstellung. Einzelne Rechte kannst du hier abweichend erlauben oder sperren.": "Rollen sätter standarden. Enskilda rättigheter kan tillåtas eller blockeras här.",
    "Alles erlauben": "Tillåt allt",
    "Alles sperren": "Blockera allt",
    "Benachrichtigung bei Unterschreitung": "Avisering när lagret är lågt",
    "Die Mail geht an die verantwortliche Person, Stellvertretungen stehen im CC.": "Mejlet går till ansvarig person, ersättare står som CC.",
    "Sofort bei jeder Unterschreitung": "Direkt, varje gång",
    "Einmal am Tag, gesammelt": "En gång om dagen, samlat",
    "Einmal in der Woche": "En gång i veckan",
    "Einmal im Monat": "En gång i månaden",
    "Uhrzeit": "Klockslag",
    "Wochentag": "Veckodag",
    "Tag im Monat": "Dag i månaden",
    "Aktuell aktiv": "Aktivt nu",
    "Bei gesammelten Mails entsteht automatisch eine Bestellliste mit allen Produktinfos.": "Samlade mejl skapar automatiskt en beställningslista med alla artikeluppgifter.",
    "Sprache und Darstellung": "Språk och utseende",
    "Sprache dieses Kontos": "Kontots språk",
    "Design": "Utseende",
    "Passwort ändern": "Byt lösenord",
    "Aktuelles Passwort": "Nuvarande lösenord",
    "Neues Passwort": "Nytt lösenord",
    "Neues Passwort wiederholen": "Upprepa nytt lösenord",
    "Passwort speichern": "Spara lösenord",
    "Firmen": "Företag",
    "Firma": "Företag",
    "Abo": "Abonnement",
    "Angelegt": "Skapad",
    "Passwort": "Lösenord",
    "Löschen": "Ta bort",
    "Betriebszugang: Firmen und Personen sperren, löschen, Passwort-Neuanforderung schicken. Produktdaten der Firmen sind hier nicht sichtbar — jede Firma sieht nur ihr eigenes Lager.": "Operatörsåtkomst: blockera eller ta bort företag och personer, begär nytt lösenord. Företagens artikeldata syns inte här — varje företag ser bara sitt eget lager.",
    "Anmelden": "Logga in",
    "Registrieren": "Registrera",
    "Einladung": "Inbjudan",
    "Schließen": "Stäng",
    "Ich habe schon ein Konto": "Jag har redan ett konto",
    "Neue Firma anlegen": "Skapa nytt företag",
    "Konto anlegen": "Skapa konto",
    "Ich bin kein Bot": "Jag är inte en bot",
    "Derzeit kostenlos, jederzeit kündbar.": "Gratis just nu, avsluta när du vill.",
    "E-Mail bestätigen": "Bekräfta e-post",
    "Wir haben dir einen Link geschickt. Er gilt 15 Minuten.": "Vi har skickat en länk. Den gäller i 15 minuter.",
    "Neue Mail anfordern": "Begär nytt mejl",
    "Zugang einrichten": "Skapa åtkomst",
    "Einladung zu Internet GmbH · läuft in 2 Std. 41 Min. ab": "Inbjudan till Internet GmbH · går ut om 2 tim 41 min",
    "Wir schicken dir einen Link, der 15 Minuten gültig ist.": "Vi skickar en länk som gäller i 15 minuter.",
    "Zurück zur Anmeldung": "Tillbaka till inloggning",
    "Zweiter Faktor": "Andra faktorn",
    "Anmeldung": "Inloggning",
    "E-Mail oder Passwort falsch": "Fel e-post eller lösenord",
    "Kostenbremse": "Kostnadsspärr",
    "Kosten": "Kostnad",
    "Grenze erreicht": "Gräns nådd",
    "Scannen statt suchen": "Skanna i stället för att leta",
    "Nie wieder leer": "Aldrig tomt igen",
    "Jede Person ihr Maß": "Rättigheter som passar",
    "Nur euer Lager": "Bara ert lager",
    "Jeder Code gehört zu genau einem Artikel und öffnet dessen Detailansicht. Etiketten mit eigenem Text drucken.": "Varje kod hör till en enda artikel och öppnar dess detaljvy. Skriv ut etiketter med egen text.",
    "Warnung sofort oder gesammelt — täglich, wöchentlich, monatlich. Verantwortliche Person direkt, Stellvertretung im CC.": "Avisering direkt eller samlat — dagligen, varje vecka, varje månad. Ansvarig person direkt, ersättare som CC.",
    "Vier Rollen als Vorlage, jedes Recht einzeln anpassbar — von Buchen bis Exportieren.": "Fyra roller som mall, varje rättighet justerbar för sig — från bokning till export.",
    "Daten in der EU, streng pro Firma getrennt. Das steckt in der Datenbank, nicht in der Oberfläche.": "Data i EU, strikt åtskilt per företag. Det ligger i databasen, inte i gränssnittet.",
    "Bot-Schutz und Sperre nach fünf Fehlversuchen": "Botskydd och låsning efter fem misslyckade försök",
    "Bestätigungslink gültig 15 Minuten": "Bekräftelselänk giltig i 15 minuter",
    "Bilder nur über signierten Zugriff": "Bilder endast via signerad åtkomst",
    "Nicht eingerichtet": "Inte inställd",
    "Konto sofort aktiv — keine Mail": "Kontot aktivt direkt — inget mejl",
    "In Supabase ist „Confirm email\" ausgeschaltet. Einschalten unter Authentication → Providers → Email.": "\"Confirm email\" är avstängt i Supabase. Slå på det under Authentication → Providers → Email.",
    "Die Registrierung wurde abgelehnt:": "Registreringen avvisades:",
    "Mail erneut angefordert": "Mejl begärt igen",
    "Scannen, Menge eingeben, fertig. Den Rest macht das System.": "Skanna, ange antal, klart. Resten sköter systemet.",
    "Mindestbestand erreicht": "Miniminivå nådd",
    "vor 12 Wochen": "för 12 veckor sedan",
    "heute": "idag",
    "In config.js fehlen SUPABASE_URL und SUPABASE_ANON_KEY. Ohne sie gibt es keine Datenbank und keine Mail. Die Schritte stehen in SETUP.md.": "SUPABASE_URL och SUPABASE_ANON_KEY saknas i config.js. Utan dem finns ingen databas och inga mejl. Stegen står i SETUP.md.",
    "Code eingeben": "Ange kod",
    "Artikel-ID oder EAN": "Artikel-ID eller EAN",
    "Öffnen": "Öppna",
    "Scan-Adresse": "Skanningsadress",
    "Person verdeckt": "Person dold",
    "Nur zum Ansehen": "Endast visning",
    "Eine Spalte pro Feld. In „Quantität 1–3\" die Namen aus den Einstellungen eintragen.": "En kolumn per fält. Ange namnen från inställningarna i Enhet 1–3.",
    "Bestellmenge eintragen": "Ange beställningsantal",
    "Alle Positionen nachfüllen": "Fyll på alla poster",
    "Nachfüllen": "Fyll på",
    "nachgefüllt": "påfylld",
    "Bestellung abschließen": "Avsluta beställningen",
    "Keine Menge eingetragen": "Inget antal angivet",
    "Menge und Quantität eintragen, dann nachfüllen.": "Ange antal och enhet, fyll sedan på.",
    "Bestand erhöht": "Lagret ökat",
    "Nachfüllung aus Bestellung": "Påfyllning från beställning",
    "Abgeschlossen": "Avslutad",
    "Bestandswert im Zeitverlauf": "Lagervärde över tid",
    "Bestandswert": "Lagervärde",
    "Preisänderung — anklicken": "Prisändring — klicka",
    "Markierung lösen": "Ta bort markering",
    "Markierungen ausblenden": "Dölj markeringar",
    "Preisänderungen markieren": "Markera prisändringar",
    "Bestand × gültiger Preis · letzte ": "Lager × gällande pris · senaste ",
    " Tage": " dagar",
    "jetzt ": "nu ",
    "Bestandswert an dem Tag: ": "Lagervärde den dagen: ",
    "Menge in ": "Antal i ",
    "in der kleinsten Einheit": "i minsta enheten",
    "Zu den Quantitäten": "Till kvantiteter",
    "Zu den Abteilungen": "Till avdelningar",
    "Zur Produktverwaltung": "Till artikelhantering",
    "Zu den Einstellungen": "Till inställningar",
    "Zu den Bestellungen": "Till beställningar",
    "Zu den Events": "Till evenemang",
    "Zum Bestandswert": "Till lagervärde",
    "Zu den Lagerorten": "Till lagerplatser",
    "Einkauf": "Inköp",
    "Bestellliste und Bestellungen": "Beställningslista och beställningar",
    "Planung": "Planering",
    "Konto": "Konto",
    "Anmeldung und Sprache": "Inloggning och språk",
    "Wie übernehme ich eine bestehende Liste?": "Hur tar jag in en befintlig lista?",
    "Stammdaten → Produktverwaltung, Karte „Viele Produkte aus einer Tabelle importieren\". Vorlage herunterladen — leer oder mit dem heutigen Bestand —, in Excel ausfüllen und wieder hochladen. Gelesen werden Excel (.xlsx) und CSV.": "Grunddata → Artikelhantering, kortet ”Importera många artiklar från en tabell”. Ladda ner mallen — tom eller med dagens lager —, fyll i den i Excel och ladda upp igen. Excel (.xlsx) och CSV läses.",
    "Istbestand, Mindestbestand und Bestellmenge stehen in der Standardquantität des Produkts. Zeilen mit Fehlern werden vor dem Übernehmen einzeln angezeigt.": "Lager, minimum och beställningsantal anges i artikelns standardkvantitet. Rader med fel visas en och en före importen.",
    "Auf dem Buchungsschirm zählt das Hauptfeld in der Standardquantität. Darunter steht für jede weitere Quantität ein eigenes Feld — zwei Kästen und drei Flaschen ergeben automatisch die richtige Gesamtmenge.": "På bokningsskärmen räknar huvudfältet i standardkvantiteten. Under det har varje ytterligare kvantitet ett eget fält — två backar och tre flaskor ger automatiskt rätt total.",
    "Welche Quantitäten ein Produkt hat, steht in seinem Detail unter „Bearbeiten\".": "Vilka kvantiteter en artikel har ställs in i dess detaljvy under ”Redigera”.",
    "Wie lege ich Quantitäten und die Standardquantität fest?": "Hur ställer jag in kvantiteter och standardkvantitet?",
    "Einstellungen → Quantitäten: Gebinde wie Flasche, Kasten oder Palette anlegen und angeben, wie viele der kleineren darin stecken — 1 Kasten = 12 Flaschen.": "Inställningar → Kvantiteter: skapa förpackningar som flaska, back eller pall och ange hur många mindre de rymmer — 1 back = 12 flaskor.",
    "Im Produkt die passenden Quantitäten anhaken und eine als Standardquantität wählen. In ihr werden Bestand, Mindestbestand und Bestellmenge gezeigt, gebucht und in Mails genannt; was nicht aufgeht, steht in den kleineren Quantitäten daneben.": "Markera passande kvantiteter i artikeln och välj en som standard. Lager, minimum och beställningsantal visas, bokas och mejlas i den; en rest visas i de mindre kvantiteterna.",
    "Wie trage ich das Mindesthaltbarkeitsdatum ein?": "Hur anger jag bäst-före-datum?",
    "Beim Nachfüllen und in offenen Bestellungen gibt es ein Feld „MHD\". Jede Lieferung behält ihr eigenes Datum.": "Vid påfyllning och i öppna beställningar finns fältet ”Bäst före”. Varje leverans behåller sitt eget datum.",
    "Entnommen wird nach „first in, first out\": das älteste MHD zuerst.": "Uttag sker enligt ”first in, first out”: äldsta datum först.",
    "Wie verschicke ich die Bestellliste sofort?": "Hur skickar jag beställningslistan direkt?",
    "Einstellungen → Benachrichtigungen → „Bestellliste jetzt mailen\". Inhaber und Lagerleitung bekommen alles unter Mindestbestand, die Mengen in der Standardquantität jedes Produkts.": "Inställningar → Aviseringar → ”Mejla beställningslistan nu”. Ägare och lagerledning får allt under minimum, antal i varje artikels standardkvantitet.",
    "Was zeigt der Bestandswert?": "Vad visar lagervärdet?",
    "In der Karte „Preisverlauf und Umsatz\": Bestand × Preis, der an dem Tag galt, über den gewählten Zeitraum. Bei einem einzelnen Produkt zeigt die gestrichelte Linie den Wert des Mindestbestands.": "I kortet ”Prishistorik och omsättning”: lager × det pris som gällde den dagen, över vald period. För en enskild artikel visar den streckade linjen minimilagrets värde.",
    "Tage mit Preisänderung sind als Raute markiert. Ein Klick darauf — oder auf die Zeile in der Tabelle „Preisänderungen\" — zeigt alten und neuen Preis.": "Dagar med prisändring har en romb. Ett klick på den — eller på raden i tabellen ”Prisändringar” — visar gammalt och nytt pris.",
    "Wie arbeite ich mit Abteilungen?": "Hur arbetar jag med avdelningar?",
    "Einstellungen → Abteilungen: Abteilungen anlegen und Personen zuordnen. Eine Person kann in mehreren Abteilungen sein.": "Inställningar → Avdelningar: skapa avdelningar och tilldela personer. En person kan vara i flera avdelningar.",
    "Oben in der Menüleiste wird die Abteilung gewechselt. Produkte, Bestellungen, Events, Merkzettel und Verlauf zeigen dann nur ihre Daten; „Ganze Firma\" zählt alles zusammen.": "Byt avdelning högst upp i menyraden. Artiklar, beställningar, evenemang, anteckningar och historik visar då bara dess data; ”Hela företaget” räknar ihop allt.",
    "Wie kopiere ich Produkte in eine andere Abteilung?": "Hur kopierar jag artiklar till en annan avdelning?",
    "Stammdaten → Produktverwaltung: ein oder mehrere Produkte auswählen, Zielabteilung wählen, kopieren. Die Kopie bekommt eine eigene Kennung und einen neuen QR-Code; der Bestand wird getrennt geführt.": "Grunddata → Artikelhantering: välj en eller flera artiklar, välj målavdelning, kopiera. Kopian får eget ID och ny QR-kod; lagret förs separat.",
    "Das Etikett der Kopie neu drucken — sonst bucht der Scan im ursprünglichen Produkt.": "Skriv ut en ny etikett för kopian — annars bokar skanningen på originalet.",
    "Was sieht welche Abteilung?": "Vad ser varje avdelning?",
    "Einstellungen → Sichtbarkeit je Abteilung: Lagerorte, Quantitäten und Merkmale lassen sich für einzelne Abteilungen ausblenden. Wer dort arbeitet, bekommt sie in Auswahllisten nicht angeboten.": "Inställningar → Synlighet per avdelning: lagerplatser, kvantiteter och egenskaper kan döljas för enskilda avdelningar. De som arbetar där ser dem inte i vallistor.",
    "Wie benenne ich einen Lagerort um?": "Hur byter jag namn på en lagerplats?",
    "Einstellungen → Lagerorte, beim Lagerort „Umbenennen\" wählen. Alle Produkte an diesem Ort ziehen automatisch mit.": "Inställningar → Lagerplatser, välj ”Byt namn” vid platsen. Alla artiklar där följer med automatiskt.",
    "Warum ist eine Seite für mich gesperrt?": "Varför är en sida låst för mig?",
    "Welche Seiten und Aktionen jemand nutzen darf, legt die Rolle fest; einzelne Rechte können je Person abweichen. Freigeben kann, wer das Recht „Rechte ändern\" hat.": "Rollen avgör vilka sidor och åtgärder någon får använda; enskilda rättigheter kan skilja per person. Den som har rätten ”Ändra rättigheter” kan låsa upp.",
    "Die Hilfe ist für alle immer offen.": "Hjälpen är alltid öppen för alla.",
    "Wie entsteht die Bestellliste?": "Hur skapas beställningslistan?",
    "Lager → Bestellungen. Jedes aktive Produkt unter Mindestbestand steht dort bei der verantwortlichen Person — verschiebbar zu jeder anderen. Oben lässt sich nach Abteilung filtern.": "Lager → Beställningar. Varje aktiv artikel under minimum står hos den ansvariga personen — flyttbar till vem som helst. Filtrera på avdelning högst upp.",
    "„Alle mit Bestellmenge in Bestellung\" übernimmt die hinterlegte Bestellmenge. Sie steht zuerst in der Standardquantität; nur was darin nicht aufgeht, kommt in die kleineren Quantitäten.": "”Beställ alla med beställningsantal” tar det sparade antalet. Det hamnar först i standardkvantiteten; bara en rest går till de mindre kvantiteterna.",
    "Die Ware ist da — was jetzt?": "Varorna har kommit — vad nu?",
    "In der offenen Bestellung die gelieferte Menge prüfen, bei Bedarf das MHD eintragen und zurück in den Bestand buchen. Der Bestand steigt, das Produkt verlässt die Bestellung.": "Kontrollera levererat antal i den öppna beställningen, ange bäst-före vid behov och boka tillbaka till lagret. Lagret ökar och artikeln lämnar beställningen.",
    "Wie plane ich ein Event?": "Hur planerar jag ett evenemang?",
    "Lager → Events: Name, Datum, Ort und die benötigten Artikel mit Menge eintragen. Beim Anlegen entsteht die Bedarfsliste mit den Fehlmengen gegenüber dem heutigen Bestand.": "Lager → Evenemang: ange namn, datum, plats och behövda artiklar med antal. När du sparar skapas behovslistan med bristerna mot dagens lager.",
    "„Bestellung abschicken\" setzt die Fehlmengen auf die Bestelllisten der Verantwortlichen.": "”Skicka beställning” lägger bristerna på de ansvarigas beställningslistor.",
    "Was zeigt die Vorschau?": "Vad visar förhandsvyn?",
    "Alle kommenden Events — oder die eines Zeitraums — zusammengerechnet und gegen den heutigen Bestand gestellt. „Nur noch nicht bestellte\" blendet aus, was schon unterwegs ist. Das Ergebnis lässt sich als Excel exportieren.": "Alla kommande evenemang — eller de inom en period — summerade och ställda mot dagens lager. ”Bara ej beställda” döljer det som redan är på väg. Resultatet kan exporteras till Excel.",
    "Auf der Anmeldeseite „Passwort vergessen?\" wählen. Der Link in der Mail gilt 15 Minuten.": "Välj ”Glömt lösenordet?” på inloggningssidan. Länken i mejlet gäller i 15 minuter.",
    "Wie schütze ich mein Konto zusätzlich?": "Hur skyddar jag mitt konto ytterligare?",
    "In den Einstellungen Zwei-Faktor einrichten. Danach fragt die Anmeldung zusätzlich einen Code aus der Authenticator-App ab.": "Aktivera tvåfaktor i inställningarna. Inloggningen frågar sedan även efter en kod från autentiseringsappen.",
    "Wie ändere ich die Sprache?": "Hur byter jag språk?",
    "Oben rechts in der Menüleiste DE, EN oder SV wählen.": "Välj DE, EN eller SV längst upp till höger i menyraden.",
    "Sprache": "Språk",
    "Zurück": "Tillbaka",
    "Nur beim Bearbeiten": "Bara vid redigering",
    "Zuweisen nur beim Bearbeiten oder über die Excel-Tabelle.": "Tilldela bara vid redigering eller via Excel-tabellen.",
    "Oben auf „Bearbeiten\" tippen, dann lassen sich Quantitäten zuweisen.": "Tryck på Redigera ovan, sedan kan enheter tilldelas.",
    "Standardquantität": "Standardkvantitet",
    "Standardquantität wählen.": "Välj en standardkvantitet.",
    "Standardquantität fehlt.": "Standardkvantitet saknas.",
    "Mindestens eine Quantität anhaken.": "Markera minst en kvantitet.",
    "Gebucht und angezeigt wird in ": "Bokas och visas i ",
    "Bestände und Mindestmengen zählen in der kleinsten Einheit": "Lager och minimum räknas i minsta enheten",
    "Menge eintragen, dann buchen.": "Ange ett antal och boka.",
    "Buchung": "Bokning",
    "Rechte speichern": "Spara rättigheter",
    "Rechte gespeichert": "Rättigheter sparade",
    "Rechte nicht gespeichert": "Rättigheterna sparades inte",
    "Nicht gespeicherte Änderungen": "Osparade ändringar",
    "Alle Rechte sind gespeichert.": "Alla rättigheter är sparade.",
    "Nur in dieser Sitzung — ohne Datenbank.": "Bara i denna session — utan databas.",
    "Quantität unbekannt: ": "Okänd kvantitet: ",
    "Standardquantität unbekannt: ": "Okänd standardkvantitet: ",
    "Standardquantität fehlt — vorläufig gesetzt: ": "Standardkvantitet saknas — tillfälligt satt: ",
    "Keine Quantität zugewiesen": "Ingen kvantitet tilldelad",
    "ist keine ganze Zahl ab 0 — als 0 übernommen": "är inget heltal från 0 — importerat som 0",
    "wirkt unplausibel hoch — bitte prüfen": "verkar orimligt högt — kontrollera",
    "Preis nicht lesbar: ": "Priset kan inte läsas: ",
    "MHD nicht lesbar: ": "Bäst före kan inte läsas: ",
    "Verantwortliche Person nicht im Team: ": "Ansvarig person finns inte i teamet: ",
    "Stellvertretung nicht im Team: ": "Ersättare finns inte i teamet: ",
    "Mehr als 3 Stellvertretungen — nur die ersten 3 übernommen": "Fler än 3 ersättare — bara de första 3 importerade",
    "Zeile wurde nicht so übernommen, wie sie in der Datei steht.": "rad importerades inte exakt som i filen.",
    "Zeilen wurden nicht so übernommen, wie sie in der Datei stehen.": "rader importerades inte exakt som i filen.",
    "Korrigieren lässt sich das in der Produktbearbeitung oder mit einem neuen Import.": "Rätta det i artikelredigeringen eller med en ny import.",
    "Fehler beim Import": "Fel vid import",
    "Verstanden": "Uppfattat",
    "Fehlerliste herunterladen": "Ladda ner fellista",
    "Standard": "standard",
    "Etiketten gestalten": "Utforma etiketter",
    "Format": "Format",
    "Texte für alle Etiketten": "Texter för alla etiketter",
    "Schriftgrößen": "Teckenstorlekar",
    "Produktname": "Artikelnamn",
    "Artikel-ID": "Artikel-ID",
    "ID-Größe": "ID-storlek",
    "Ein Etikett in der Vorschau anklicken, um es einzeln zu beschriften.": "Klicka på en etikett i förhandsvisningen för att anpassa den.",
    "Einzelnes Etikett": "Enskild etikett",
    "Produktname zeigen": "Visa artikelnamn",
    "Artikel-ID zeigen": "Visa artikel-ID",
    "Fertig": "Klar",
    "Auf Vorgabe zurücksetzen": "Återställ till standard",
    "A4 · 1 Code je Blatt": "A4 · 1 kod per ark",
    "A5 · 2 je Blatt": "A5 · 2 per ark",
    "A6 · 4 je Blatt": "A6 · 4 per ark",
    "Bestelllisten je Person": "Beställningslistor per person",
    "Alles, was offen ist — aus der Bestellliste, aus Bestellungen und aus kommenden Events — landet zuerst bei der verantwortlichen Person. Einzelne Positionen lassen sich zu einer anderen Person verschieben.": "Allt som är öppet — från beställningslistan, beställningar och kommande evenemang — hamnar först hos den ansvariga. Enskilda poster kan flyttas till en annan person.",
    "Quelle": "Källa",
    "Verschieben zu": "Flytta till",
    "Verschoben": "Flyttad",
    "offene Positionen": "öppna poster",
    "Für diese Person ist gerade nichts offen.": "Inget är öppet för den här personen just nu.",
    "Eigene Personenbestellliste für alle sichtbar": "Egen beställningslista synlig för alla",
    "Nur die inhabende Person": "Endast ägaren",
    "Ob eine Personenbestellliste für alle sichtbar ist, legt die inhabende Person fest.": "Ägaren bestämmer om en personlig beställningslista är synlig för alla.",
    "Bestellung": "Beställning",
    "Seite: Übersicht": "Sida: Översikt",
    "Seite: Produkte": "Sida: Produkter",
    "Seite: Scannen": "Sida: Skanna",
    "Seite: Bestellungen": "Sida: Beställningar",
    "Seite: Events": "Sida: Evenemang",
    "Seite: Bestandsverlauf": "Sida: Lagerhistorik",
    "Seite: Produktverwaltung": "Sida: Artikelhantering",
    "Seite: QR-Codes": "Sida: QR-koder",
    "Seite: Team & Rechte": "Sida: Team & rättigheter",
    "Seite: Einstellungen": "Sida: Inställningar",
    "Seite: Hilfe": "Sida: Hjälp",
    "Diese Seite ist für dich gesperrt.": "Den här sidan är spärrad för dig.",
    "Freigeben kann sie, wer das Recht „Rechte ändern\" hat.": "Den som har rättigheten ”Ändra rättigheter” kan låsa upp den.",
    "Event bearbeiten": "Redigera evenemang",
    "Name, Datum und mindestens ein Artikel sind nötig.": "Namn, datum och minst en artikel krävs.",
    "Name und Datum fehlen": "Namn och datum saknas",
    "Ein Event braucht einen Namen und ein Datum.": "Ett evenemang behöver ett namn och ett datum.",
    "Event löschen": "Ta bort evenemang",
    "Das Event und seine Bedarfsliste werden entfernt. Bestände und Buchungen bleiben unberührt.": "Evenemanget och dess behovslista tas bort. Lager och bokningar påverkas inte.",
    "Rückgängig": "Ångra",
    "Bewegungen rückgängig machen": "Ångra rörelser",
    "Buchung rückgängig machen": "Ångra bokning",
    "Die Buchung wird durch eine Gegenbuchung aufgehoben und verschwindet aus Verlauf und Auswertungen.": "Bokningen hävs med en motbokning och försvinner ur historik och analyser.",
    "Geht nicht": "Går inte",
    "Der Bestand würde unter 0 fallen.": "Lagret skulle bli under 0.",
    "Die Buchung wird noch gespeichert — gleich noch einmal versuchen.": "Bokningen sparas fortfarande — försök igen strax.",
    "Rückgängig gemacht": "Ångrad",
    "Geändert": "Ändrad",
    "Produkte angepasst": "artiklar uppdaterade",
    "Ersetzen durch": "Ersätt med",
    "— keine, nur entfernen —": "— ingen, bara ta bort —",
    "Wähle, durch welche Quantität sie in Produkten ersetzt wird. Quantitäten, die sich darauf beziehen, zeigen dann auf die Ersatzquantität.": "Välj vilken kvantitet som ersätter den i artiklar. Kvantiteter som hänvisar till den pekar då på ersättningen.",
    "Bitte einen Wert aus der Liste wählen.": "Välj ett värde ur listan.",
    "Lagerort, Quantitäten und Personen sind Auswahllisten.": "Lagerplats, kvantiteter och personer är listrutor.",
    "Keine gültige Excel-Datei": "Ingen giltig Excel-fil",
    "Dieser Browser kann Excel-Dateien nicht entpacken — bitte als CSV speichern.": "Webbläsaren kan inte packa upp Excel-filer — spara som CSV.",
    "Keine Tabelle in der Datei gefunden": "Inget blad hittades i filen",
    "Datei hierher ziehen oder klicken · .xlsx oder .csv bis 5 MB": "Dra hit en fil eller klicka · .xlsx eller .csv upp till 5 MB",
    "Änderungen speichern": "Spara ändringar",
    "dazu einzeln": "plus styck",
    "Istbestand einzeln": "Lager styck",
    "ist keine Zahl ab 0 — als 0 übernommen": "är inget tal från 0 — importerat som 0",
    "ergibt keine ganze Einzelmenge — gerundet auf ": "ger ingen hel styckmängd — avrundat till ",
    "ist keine ganze Zahl ab 0 — nicht übernommen": "är inget heltal från 0 — inte importerat",
    "Istbestand, Mindestbestand und Bestellmenge in dieser Quantität angeben": "Ange lager, minimum och beställningsantal i denna kvantitet",
    "einzelne im Feld „dazu einzeln“": "enstaka i fältet ”plus styck”",
    "Istbestand einzeln ohne größere Standardquantität — zum Istbestand addiert": "Styck utan större standardkvantitet — lagt till lagret",
    "Istbestand einzeln ist ein volles Gebinde oder mehr — trotzdem addiert: ": "Styck är en hel förpackning eller mer — lagt till ändå: ",
    "Kein Zugriff auf die Rechteverwaltung": "Ingen åtkomst till rättighetshanteringen",
    "Wer welche Rechte hat, sehen und ändern nur die inhabende Person und wer das Recht „Rechte ändern\" ausdrücklich bekommen hat.": "Vem som har vilka rättigheter ser och ändrar bara ägaren och den som uttryckligen fått rätten att ändra rättigheter.",
    "Bestellung nicht gespeichert": "Beställningen sparades inte",
    "Bitte supabase/schema.sql im SQL-Editor erneut ausführen.": "Kör supabase/schema.sql i SQL-editorn igen.",
    "Bestellungen": "Beställningar",
    "Offene Bestellungen": "Öppna beställningar",
    "In Bestellung": "Lägg beställning",
    "Alle in Bestellung": "Beställ alla",
    "Zurück in Bestand": "Tillbaka i lager",
    "Alles zurück in Bestand": "Allt tillbaka i lager",
    "Nichts in Bestellung": "Inget beställt",
    "Zur Bestellliste": "Till beställningslistan",
    "bestellt von ": "beställd av ",
    "Ohne Zuordnung": "Utan koppling",
    "früher gesetzt": "satt tidigare",
    "Ohne Bestellmengen — erst über die Bestellliste in Bestellung setzen, dann lässt sich hier nachgefüllt werden.": "Inga beställningsantal — beställ först via beställningslistan, sedan kan den fyllas på här.",
    "Nichts offen": "Inget öppet",
    "Kein Artikel unter Mindestbestand.": "Ingen artikel under miniminivå.",
    "steht schon in Bestellung": "är redan beställd",
    "Bestand ": "Lager ",
    "Min ": "Min ",
    "am": "den",
    "Samstag": "Lördag",
    "Sonntag": "Söndag",
    "Zurück zu den Produkten": "Tillbaka till artiklarna",
    "Was über die Bestellmail oder aus der Bestellliste in Bestellung gesetzt wurde, steht hier als Bündel. Solange ein Artikel hier steht, taucht er nicht wieder in der Bestellliste auf und löst keine Mail aus.": "Det som beställts via beställningsmejlet eller listan står här som en bunt. Så länge en artikel står här kommer den inte tillbaka i beställningslistan och utlöser inget mejl.",
    "Sobald ein Artikel in Bestellung gesetzt wird — hier, im Produkt oder über den Knopf in der Bestellmail — erscheint er an dieser Stelle.": "Så snart en artikel beställs — här, på produkten eller via knappen i beställningsmejlet — visas den på den här platsen.",
    "Artikel suchen": "Sök artiklar",
    "Name, Kennung, EAN, Lagerort …": "Namn, kod, EAN, lagerplats …",
    "Weniger anzeigen": "Visa färre",
    "weitere anzeigen": "fler",
    "Nicht genug Bestand": "Inte tillräckligt lager",
    "Vorhanden: ": "Finns: ",
    "Die Entnahme wurde nicht gebucht.": "Uttaget bokfördes inte.",
    "Vorhanden sind nur ": "Det finns bara ",
    "so viel lässt sich nicht entnehmen.": "så mycket kan inte tas ut.",
    "Leere Liste mit einer Beispielzeile": "Tom lista med en exempelrad",
    "Quantität löschen": "Ta bort kvantitet",
    "wird verwendet": "används",
    "Stelle": "ställe",
    "Stellen": "ställen",
    "Diese Quantität ist im Einsatz: ": "Kvantiteten används: ",
    "Wird sie gelöscht, verlieren diese Produkte ihre Umrechnung — die gebuchten Mengen bleiben stehen. Quantitäten, die sich darauf beziehen, werden eigenständig.": "Om den tas bort förlorar produkterna sin omräkning — bokade mängder står kvar. Kvantiteter som hänvisar till den blir fristående.",
    "Betroffen": "Berörda",
    "weitere": "fler",
    "Trotzdem löschen": "Ta bort ändå",
    "bezieht sich darauf": "hänvisar till den",
    "Vorschau bis Datum": "Förhandsvy till datum",
    "Stichtag": "Brytdatum",
    "Vorschau rechnen": "Räkna förhandsvy",
    "Alles, was bis zu einem Stichtag in Events gebraucht wird, zusammengerechnet und gegen den heutigen Bestand gestellt.": "Allt som behövs för evenemang till ett brytdatum, summerat och ställt mot dagens lager.",
    "Bedarf": "Behov",
    "Rest": "Kvar",
    "Vorschau schließen": "Stäng förhandsvy",
    "Vorschau exportiert": "Förhandsvy exporterad",
    "Bis zu diesem Datum ist kein Event geplant.": "Inget evenemang är planerat till det datumet.",
    "nicht ausreichend": "inte tillräckligt",
    "Bestand reicht überall": "lagret räcker överallt",
    "fehlt: ": "saknas: ",
    "danach unter Mindestbestand": "under miniminivå efteråt",
    "Lager und Artikel": "Lager och artiklar",
    "Lagerorte, Gebinde und eigene Felder": "Lagerplatser, förpackningar och egna fält",
    "Warnungen und Mail": "Varningar och e-post",
    "Wann wer eine Nachricht bekommt": "Vem som får meddelande och när",
    "Mein Konto": "Mitt konto",
    "Sprache, Darstellung, Anmeldung": "Språk, utseende, inloggning",
    "System und Kosten": "System och kostnad",
    "Dienste, Mailversand prüfen, Grenzen": "Tjänster, e-postkontroll, gränser",
    "Nicht gefunden": "Hittades inte",
    "Kein Artikel mit dieser ID oder EAN.": "Ingen artikel med det ID:t eller EAN.",
    "Datei auswählen": "Välj fil",
    "Spalten geprüft — unten bestätigen.": "Kolumner kontrollerade — bekräfta nedan.",
    "Keine Datenbank verbunden": "Ingen databas ansluten",
    "Mail-Tagesgrenze erreicht — Sammelversand morgen.": "Daglig mejlgräns nådd — samlat utskick i morgon.",
    "In config.js FREE_TIER_GUARD auf false setzen oder die Grenze anheben.": "Sätt FREE_TIER_GUARD till false i config.js, eller höj gränsen.",
    "aktiv": "på",
    "aus": "av",
    "Mails heute": "Mejl idag",
    "Mails am Tag": "mejl per dag",
    "Zeilen je Import": "rader per import",
    "MB je Datei": "MB per fil",
    "MB Speicher": "MB lagring",
    "Speicher": "Lagring",
    "gesetzt": "låst",
    "Das geht nicht": "Går inte",
    "Mindestens eine aktive Person muss die Rechte verwalten können. Vergib die Rolle zuerst an jemand anderen.": "Minst en aktiv person måste kunna hantera rättigheter. Ge rollen till någon annan först.",
    "Diese Person verwaltet aktuell allein die Rechte. Rolle, Zugang und das Recht „Rechte ändern\" sind deshalb gesperrt — vergib die Rolle zuerst an jemand anderen.": "Denna person hanterar för tillfället rättigheterna ensam. Roll, åtkomst och rättigheten att ändra rättigheter är därför låsta — ge rollen till någon annan först.",
    "Aktionen, die eine Grenze überschreiten würden, werden abgelehnt. So entstehen bei keinem der vier Dienste Kosten.": "Åtgärder som skulle överskrida en gräns nekas, så ingen av de fyra tjänsterna kan ge kostnader.",
    "Keine Sperre. Alles ist erlaubt — auch über die Gratis-Kontingente hinaus, wodurch Kosten entstehen können.": "Ingen spärr. Allt tillåts, även utöver gratisnivåerna, vilket kan ge kostnader.",
    "Umschalten in config.js: FREE_TIER_GUARD auf false setzen hebt die Sperre auf, einzelne Grenzen stehen in FREE_TIER_LIMITS.": "Ändra i config.js: FREE_TIER_GUARD till false tar bort spärren; gränserna står i FREE_TIER_LIMITS.",
    "Bitte noch einmal versuchen.": "Försök igen.",
    "Mehr erfahren": "Läs mer",
    "Sechsstelligen Code aus deiner Authenticator-App eingeben.": "Ange den sexsiffriga koden från din autentiseringsapp.",
    "Code": "Kod",
    "Bestätigen": "Bekräfta",
    "Code falsch": "Fel kod",
    "Zwei-Faktor-Anmeldung": "Tvåfaktorsinloggning",
    "Zusätzlich zum Passwort ein Code aus einer App. Schützt auch dann, wenn das Passwort bekannt wird.": "En kod från en app utöver lösenordet. Skyddar även om lösenordet läcker.",
    "Einrichten": "Ställ in",
    "Entfernen": "Ta bort",
    "QR-Code in der App scannen, dann den ersten Code eingeben.": "Skanna QR-koden i appen och ange den första koden.",
    "Zwei-Faktor aktiv": "Tvåfaktor aktiv",
    "Zwei-Faktor entfernt": "Tvåfaktor borttagen",
    "Nur noch Passwort.": "Endast lösenord nu.",
    "Beim nächsten Anmelden wird ein Code verlangt.": "En kod krävs vid nästa inloggning.",
    "Nur im verbundenen Betrieb": "Endast i ansluten drift",
    "Zwei-Faktor braucht Supabase.": "Tvåfaktor kräver Supabase.",
    "Buchungen anzeigen": "Visa poster",
    "Buchungen ausblenden": "Dölj poster",
    "Einzelne Buchungen": "Enskilda poster",
    "Kostenlos starten": "Börja gratis",
    "QR-Code am Regal scannen": "Skanna koden på hyllan",
    "Warenüberblick mit Warnung und Bestellliste": "Lageröversikt med avisering och beställningslista",
    "Daten in der EU, pro Firma getrennt": "Data i EU, åtskilt per företag",
    "Das Lager im Griff — mit einem Scan.": "Lagret i handen — med en skanning.",
    "QR-Code am Regal scannen, Entnahme buchen, fertig. Fällt der Bestand unter das Minimum, geht automatisch eine Mail an die verantwortliche Person — und die Bestellliste schreibt sich selbst.": "Skanna koden på hyllan, bokför uttaget, klart. Understiger lagret miniminivån går ett mejl automatiskt till ansvarig person — och beställningslistan skriver sig själv.",
    "Firma registrieren": "Registrera företag",
    "Ich habe ein Konto": "Jag har ett konto",
    "Sprachen": "språk",
    "im Einstieg": "till start",
    "Datenhaltung": "datalagring",
    "Nach dem Scan": "Efter skanningen",
    "Bestellen": "Beställ",
    "QR-Code am Regal": "En kod på varje hylla",
    "Automatisch": "Automatiskt",
    "Warnung sofort oder gesammelt — täglich, wöchentlich, monatlich. Die Bestellliste entsteht von allein.": "Avisering direkt eller samlat — dagligen, veckovis, månadsvis. Beställningslistan skapas av sig själv.",
    "Getrennt": "Åtskilt",
    "Jede Firma sieht ausschließlich eigene Artikel. Das steckt in der Datenbank, nicht in der Oberfläche.": "Varje företag ser enbart sina egna artiklar. Det ligger i databasen, inte i gränssnittet.",
    "So läuft es im Alltag": "Så fungerar det i vardagen",
    "Anlegen": "Lägg upp",
    "Etikettieren": "Märk upp",
    "Buchen": "Bokför",
    "Artikel einzeln eintragen oder eine Excel-Tabelle hochladen.": "Lägg in artiklar en och en eller ladda upp ett kalkylblad.",
    "QR-Codes drucken und ans Regal kleben.": "Skriv ut QR-koder och sätt dem på hyllan.",
    "Scannen, Menge eingeben, entnehmen. Wer und wann steht im Protokoll.": "Skanna, ange antal, ta ut. Vem och när står i loggen.",
    "Mail kommt, Liste steht, Status auf „ist bestellt\" setzen.": "Mejlet kommer, listan finns, sätt status till beställd.",
    "In zehn Minuten eingerichtet": "Klart på tio minuter",
    "Eine Person aus dem Unternehmen registriert sich, lädt das Team ein und legt die ersten Artikel an.": "En person från företaget registrerar sig, bjuder in teamet och lägger upp de första artiklarna.",
    "Jetzt registrieren": "Registrera nu",
    "Daten in der EU · Jede Firma getrennt · Kein öffentlicher Zugriff": "Data i EU · Varje företag åtskilt · Ingen offentlig åtkomst",
    "Zur Startseite": "Till startsidan",
    "Startseite": "Start",
    "Lagerverwaltung, die dem Regal folgt.": "Lagerhantering som följer hyllan.",
    "Scannen, buchen, nachbestellen — und jede Firma sieht ausschließlich ihr eigenes Lager.": "Skanna, bokför, beställ om — och varje företag ser bara sitt eget lager.",
    "QR-Code scannen, Entnahme in Sekunden buchen": "Skanna en kod, bokför ett uttag på sekunder",
    "Warnmail und Bestellliste entstehen von allein": "Aviseringar och beställningslistor skapas automatiskt",
    "Rechte pro Person, bis auf das einzelne Recht": "Rättigheter per person, ner till enskild rättighet",
    "Mail an Marie Kohl, Stellvertretung im CC: Bestand 6 unter Mindestbestand 10.": "Mejl till Marie Kohl, ersättare som CC: lager 6 under miniminivå 10.",
    "Registrierung und Anmeldung sind durch Rate-Limit, Bot-Prüfung und Sperre nach fünf Fehlversuchen geschützt.": "Registrering och inloggning skyddas av hastighetsgräns, botkontroll och låsning efter fem misslyckade försök.",
    "Zu Mein Konto": "Till mitt konto",
    "Tutorials": "Guider",
    "Tutorial starten": "Starta guiden",
    "Tutorial beenden": "Avsluta guiden",
    "Schritt für Schritt auf den echten Seiten — jedes Tutorial für sich": "Steg för steg på de riktiga sidorna — varje guide för sig",
    "Persönliche Einstellungen wie Sprache, Design und Passwort findest du unter „Mein Konto\".": "Personliga inställningar som språk, tema och lösenord finns under ”Mitt konto”.",
    "Keine Einstellungen freigegeben": "Inga inställningar tillgängliga",
    "Die Bereiche „Lager und Artikel\" und „Warnungen und Mail\" hat die inhabende Person für dich gesperrt. Deine persönlichen Einstellungen findest du unter „Mein Konto\".": "Ägaren har låst ”Lager och artiklar” och ”Varningar och mejl” för dig. Dina personliga inställningar finns under ”Mitt konto”.",
    "Diese Seite gehört dir: Sprache, Design und Passwort gelten nur für dein Konto. Niemand kann sie für dich sperren.": "Den här sidan är din: språk, tema och lösenord gäller bara ditt konto. Ingen kan låsa den för dig.",
    "Meine Rechte": "Mina rättigheter",
    "Was du in dieser Firma darfst. Ändern kann das nur, wer das Recht „Rechte ändern\" hat.": "Vad du får göra i företaget. Bara den med ”Ändra rättigheter” kan ändra det.",
    "Buchen ist für dich gesperrt. Freigeben kann das, wer das Recht „Rechte ändern\" hat.": "Bokföring är låst för dig. Den med ”Ändra rättigheter” kan låsa upp.",
    "Dieser Bereich ist gerade nicht zu sehen — etwa weil er für dich gesperrt ist oder noch Daten fehlen. Mit „Weiter\" geht es trotzdem.": "Den här delen syns inte just nu — kanske är den låst eller data saknas. ”Nästa” fortsätter ändå.",
    "Einklappen": "Fäll ihop",
    "Aufklappen": "Fäll ut",
    "Weiter": "Nästa",
    "Schritt": "Steg",
    "Schritte": "steg",
    "erlaubt": "tillåtet",
    "gesperrt": "låst",
    "Seiten": "Sidor",
    "Produkte und Buchungen": "Produkter och bokningar",
    "Team und Profile": "Team och profiler",
    "Auswertung und Dateien": "Rapporter och filer",
    "Einstellungen: Lager und Artikel": "Inställningar: lager och artiklar",
    "Einstellungen: Warnungen und Mail": "Inställningar: varningar och mejl",
    "Für dich gesperrt — dafür fehlt dir ein Recht.": "Låst för dig — en rättighet saknas."
  },
  // Platzhalter in Eingabefeldern
  platzhalter: {
    "Name, EAN, Lieferant …": "Namn, EAN, leverantör …",
    "z. B. Kaffeebohnen 1 kg": "t.ex. kaffebönor 1 kg",
    "Einzelflasche, Kasten …": "Enstaka flaska, back …",
    "Getränke Nord GmbH": "Leverantörens namn",
    "Getränke, Küche, Verbrauchsmaterial — mit Komma trennen": "Dryck, kök, förbrukning — separera med komma",
    "z. B. Keller · Regal B2": "t.ex. Källare · Hylla B2",
    "z. B. Bei Entnahme scannen": "t.ex. Skanna vid uttag"
  }
};
